// Package generation2boundaryrawmomentgeneratingfunctionandcubicstopaudit implements
// Gate 783: Boundary Raw-Moment Generating Function and Cubic Stop Audit.
//
// Gate 782 made kappa_lambda_red formula-level independent by rewriting it as a
// boundary-flavor response expression. Gate 783 isolates the boundary response
// substructure F_wall_3_red and asks whether the raw-moment polynomial is native,
// generated by a lawful boundary response map, or still bridge-layer source
// typing. This gate is forensic only: it does not derive scalar runtime lambda,
// Higgs pole mass, Yukawa operators, PMNS, CKM, flavor hierarchy, G_F, VEV, or a
// native HistoryLoopUnit theorem.
package generation2boundaryrawmomentgeneratingfunctionandcubicstopaudit

import (
	"fmt"
	"math"
	"strings"
	"sync"
)

const (
	AuditID = "GATE783-BOUNDARY-RAW-MOMENT-GENERATING-FUNCTION-CUBIC-STOP-AUDIT"

	StatusGate782BoundaryFlavorComplementInherited              = "PASS_GATE782_BOUNDARY_FLAVOR_COMPLEMENT_INHERITED"
	StatusProjectorPowerDegeneracyAudited                       = "PASS_PROJECTOR_POWER_DEGENERACY_AUDITED"
	StatusRawMomentsReduceToScalarResponseCoordinates           = "PASS_RAW_MOMENTS_REDUCE_TO_SCALAR_RESPONSE_COORDINATES"
	StatusResponseFunctionRepresentationDefined                 = "PASS_RESPONSE_FUNCTION_REPRESENTATION_DEFINED"
	StatusCubicCoefficientRewrittenAs2P                         = "PASS_CUBIC_COEFFICIENT_REWRITTEN_AS_2P"
	StatusCubicStopCandidatesAudited                            = "PASS_CUBIC_STOP_CANDIDATES_AUDITED"
	StatusUntypedM4FitRejected                                  = "PASS_UNTYPED_M4_FIT_REJECTED"
	StatusRawMomentCoordinatePreserved                          = "PASS_RAW_MOMENT_COORDINATE_PRESERVED"
	StatusFWallFormulaLevelRuntimeTargetAbsenceAudited          = "PASS_F_WALL_FORMULA_LEVEL_RUNTIME_TARGET_ABSENCE_AUDITED"
	StatusRelationToKappaLambdaRedAndCHistoryRecorded           = "PASS_RELATION_TO_KAPPA_LAMBDA_RED_AND_C_HISTORY_RECORDED"
	StatusPredictionLevelClassificationRecorded                 = "PASS_PREDICTION_LEVEL_CLASSIFICATION_RECORDED"
	StatusPhysicalFirewallsEnforced                             = "PASS_PHYSICAL_FIREWALLS_ENFORCED"
	StatusBoundaryResponseLivesInScalarRawMomentCoordinate      = "CONDITIONAL_SUPPORT_BOUNDARY_RESPONSE_LIVES_IN_SCALAR_RAW_MOMENT_COORDINATE"
	StatusFWall3RedTypedBoundaryRawMomentResponse               = "CONDITIONAL_SUPPORT_F_WALL_3_RED_IS_TYPED_BOUNDARY_RAW_MOMENT_RESPONSE"
	StatusFWall3RedExpectationOfCubicResponseFunction           = "CONDITIONAL_SUPPORT_F_WALL_3_RED_CAN_BE_WRITTEN_AS_EXPECTATION_OF_CUBIC_RESPONSE_FUNCTION"
	Status2PBoundaryPairK7EventWeightSourceType                 = "CONDITIONAL_SUPPORT_2P_HAS_BOUNDARY_PAIR_TIMES_K7_EVENT_WEIGHT_SOURCE_TYPE"
	StatusCubicStopBoundaryPairExteriorDegreeCandidate          = "CONDITIONAL_SUPPORT_CUBIC_STOP_HAS_BOUNDARY_PAIR_EXTERIOR_DEGREE_CANDIDATE"
	StatusFWall3RedEvaluableWithoutDirectHiggsRuntimeVariables  = "CONDITIONAL_SUPPORT_F_WALL_3_RED_CAN_BE_EVALUATED_WITHOUT_DIRECT_HIGGS_RUNTIME_VARIABLES"
	StatusFWall3RedNowBoundarySubBottleneck                     = "CONDITIONAL_SUPPORT_F_WALL_3_RED_IS_NOW_THE_BOUNDARY_SUB_BOTTLENECK"
	StatusProjectorPowersDoNotSupplyIndependentOperatorGeometry = "FAILED_ROUTE_PROJECTOR_POWERS_DO_NOT_SUPPLY_INDEPENDENT_OPERATOR_GEOMETRY"
	StatusResponseFunctionNotYetNativeGeneratingFunction        = "FAILED_ROUTE_RESPONSE_FUNCTION_FORM_NOT_YET_NATIVE_GENERATING_FUNCTION_THEOREM"
	StatusNoNativeBoundaryResponseGeneratingFunctionTheorem     = "FAILED_ROUTE_NO_NATIVE_BOUNDARY_RESPONSE_GENERATING_FUNCTION_THEOREM"
	StatusNoNativeRawMomentCoordinateTheorem                    = "FAILED_ROUTE_NO_NATIVE_RAW_MOMENT_COORDINATE_THEOREM"
	StatusNoNativeBoundaryPairStressPullTheorem                 = "FAILED_ROUTE_NO_NATIVE_BOUNDARY_PAIR_STRESS_PULL_THEOREM"
	StatusNoTypedOperatorMapSourcingCubicCoefficient            = "FAILED_ROUTE_NO_TYPED_OPERATOR_MAP_SOURCING_CUBIC_COEFFICIENT"
	StatusProjectorIdempotenceDoesNotForceCubicStop             = "FAILED_ROUTE_PROJECTOR_IDEMPOTENCE_DOES_NOT_FORCE_CUBIC_STOP"
	StatusNoNativeRawMomentToBoundaryExteriorDegreeMap          = "FAILED_ROUTE_NO_NATIVE_RAW_MOMENT_TO_BOUNDARY_EXTERIOR_DEGREE_MAP"
	StatusNoNativeCubicStopTheorem                              = "FAILED_ROUTE_NO_NATIVE_CUBIC_STOP_THEOREM"
	StatusNoTypedFourthOrderCoefficientSource                   = "FAILED_ROUTE_NO_TYPED_FOURTH_ORDER_COEFFICIENT_SOURCE"
	StatusVarianceCoordinateNotActive                           = "FAILED_ROUTE_VARIANCE_COORDINATE_NOT_ACTIVE"
	StatusCentralMomentFormNotActive                            = "FAILED_ROUTE_CENTRAL_MOMENT_FORM_NOT_ACTIVE"
	StatusFWall3RedNotYetNativeBoundaryResponseTheorem          = "FAILED_ROUTE_F_WALL_3_RED_NOT_YET_NATIVE_BOUNDARY_RESPONSE_THEOREM"
	StatusCHistoryNotYetFullIndependentPredictionComponent      = "FAILED_ROUTE_C_HISTORY_NOT_YET_FULL_INDEPENDENT_PREDICTION_COMPONENT"
	StatusTreeProxyNotPoleMass                                  = "FAILED_ROUTE_TREE_PROXY_NOT_POLE_MASS"
	StatusNoYukawaOperatorOrEigenvalueTheorem                   = "FAILED_ROUTE_NO_YUKAWA_OPERATOR_OR_EIGENVALUE_THEOREM"
	StatusFirewallPreservedGate783                              = "FIREWALL_PRESERVED_GATE783_BOUNDARY_RAW_MOMENT_GENERATING_FUNCTION_BOUNDARY"
)

const (
	pK7Snapshot       = 7.0 / 72.0
	sSplitSnapshot    = 0.0012924448188162962
	kappaERedSnapshot = 0.005503554218475772
	fWall3Snapshot    = 0.00012565521035653708
)

type Gate782Inheritance struct {
	Inherited                bool
	KappaLambdaFormula       string
	SelectedSubBottleneck    string
	FormulaLevelIndependence string
	Verdict                  string
}

type MomentLedger struct {
	P       float64
	S       float64
	M1      float64
	M2      float64
	M3      float64
	KappaE  float64
	FWall3  float64
	Matches bool
}

type OperatorBoardAudit struct {
	Audited                     bool
	Operator                    string
	ProjectorIdempotent         bool
	PowerLaw                    string
	Moments                     []string
	AllMomentsSameSupport       bool
	IndependentOperatorGeometry bool
	ScalarRawMomentCoordinate   bool
	Verdict                     string
}

type ResponseFunctionAudit struct {
	Audited                  bool
	Function                 string
	ExpectationFormula       string
	ComputedExpectation      float64
	MatchesLedger            bool
	WrittenAsExpectation     bool
	NativeGeneratingFunction bool
	Distinction              string
	Verdict                  string
}

type CoefficientSourceAudit struct {
	Audited                      bool
	LeadingCoefficient           string
	QuadraticCoefficient         string
	CubicCoefficient             string
	TwoP                         float64
	BoundaryPairCandidate        string
	BoundaryEndpoints            []string
	NativeBoundaryPairTheorem    bool
	TypedOperatorMapSourcesCubic bool
	Verdict                      string
}

type CubicStopAudit struct {
	Audited                         bool
	ProjectorAlgebraStopsPowers     bool
	BoundaryPairExteriorCandidate   bool
	RequiredExteriorMap             string
	RawMomentToExteriorMapCertified bool
	NativeCubicStopTheorem          bool
	UntypedM4FitRejected            bool
	TypedFourthOrderCoefficient     bool
	Verdict                         string
}

type RawMomentCoordinateAudit struct {
	Audited                   bool
	RawMomentForm             string
	VarianceForm              string
	CentralThirdMomentForm    string
	ActiveCoordinate          string
	VarianceActive            bool
	CentralMomentActive       bool
	NativeRawMomentCoordinate bool
	Verdict                   string
}

type RuntimeIndependenceAudit struct {
	Audited                                     bool
	Formula                                     string
	UsesLambdaRuntime                           bool
	UsesLambdaRuntimeEff                        bool
	UsesTreeMass                                bool
	UsesPoleMass                                bool
	UsesCHiggs                                  bool
	UsesGF                                      bool
	UsesVEV                                     bool
	FormulaLevelRuntimeTargetAbsence            bool
	EvaluableWithoutDirectHiggsRuntimeVariables bool
	NativeBoundaryResponseTheorem               bool
	NativeCubicCoefficientTheorem               bool
	NativeCubicStopTheorem                      bool
	KappaERedFlavorSealed                       bool
	Verdict                                     string
}

type RelationStatus struct {
	Recorded              bool
	KappaLambdaRelation   string
	FWallLevel            string
	KappaLambdaLevel      string
	CHistoryLevel         string
	CHiggsLevel           string
	BoundarySubBottleneck string
	CHistoryIndependent   bool
	Verdict               string
}

type PredictionLevelClassification struct {
	Recorded         bool
	LevelA           string
	LevelB           string
	LevelC           string
	LevelD           string
	FWall3Level      string
	KappaLambdaLevel string
	CHistoryLevel    string
	CHiggsLevel      string
}

type Firewalls struct {
	Enforced                          bool
	ResponseFunctionNative            bool
	BoundaryGeneratingFunctionNative  bool
	RawMomentCoordinateNative         bool
	BoundaryPairStressPullNative      bool
	RawMomentExteriorDegreeMapNative  bool
	CubicStopNative                   bool
	TypedFourthOrderCoefficientSource bool
	FWallNativeBoundaryResponse       bool
	CHistoryFullIndependentPrediction bool
	TreeProxyPoleMass                 bool
	YukawaNativeTheorem               bool
	Verdict                           string
}

type Audit struct {
	Gate782        Gate782Inheritance
	Ledger         MomentLedger
	Operator       OperatorBoardAudit
	Response       ResponseFunctionAudit
	Coefficients   CoefficientSourceAudit
	CubicStop      CubicStopAudit
	Coordinate     RawMomentCoordinateAudit
	Runtime        RuntimeIndependenceAudit
	Relation       RelationStatus
	Prediction     PredictionLevelClassification
	Firewalls      Firewalls
	Truth          string
	FinalStatement string
}

var (
	defaultOnce  sync.Once
	defaultAudit Audit
	defaultErr   error
)

func BuildDefault() (Audit, error) {
	defaultOnce.Do(func() { defaultAudit, defaultErr = build() })
	return defaultAudit, defaultErr
}

func build() (Audit, error) {
	p := pK7Snapshot
	s := sSplitSnapshot
	m1 := p * s
	m2 := p * s * s
	m3 := p * s * s * s
	fwall := m1 + kappaERedSnapshot*m2 - 2*p*m3
	if math.IsNaN(fwall) || math.IsInf(fwall, 0) {
		return Audit{}, fmt.Errorf("non-finite F_wall_3_red")
	}
	matches := closeRel(fwall, fWall3Snapshot, 1e-14)

	a := Audit{
		Gate782: Gate782Inheritance{
			Inherited:                true,
			KappaLambdaFormula:       "kappa_lambda_red=|lambda|+F_wall_3_red-kappa_e_red",
			SelectedSubBottleneck:    "F_wall_3_red boundary raw-moment response polynomial",
			FormulaLevelIndependence: "Gate782 gave kappa_lambda_red Level B formula independence, but F_wall_3_red remained the boundary sub-bottleneck.",
			Verdict:                  StatusGate782BoundaryFlavorComplementInherited,
		},
		Ledger: MomentLedger{P: p, S: s, M1: m1, M2: m2, M3: m3, KappaE: kappaERedSnapshot, FWall3: fwall, Matches: matches},
		Operator: OperatorBoardAudit{
			Audited:                     true,
			Operator:                    "R_wall(s)=s P_7 in End(H72)",
			ProjectorIdempotent:         true,
			PowerLaw:                    "R_wall(s)^n=s^n P_7 because P_7^2=P_7",
			Moments:                     []string{"M1=p s", "M2=p s^2", "M3=p s^3", "M_n=p s^n"},
			AllMomentsSameSupport:       true,
			IndependentOperatorGeometry: false,
			ScalarRawMomentCoordinate:   true,
			Verdict:                     StatusBoundaryResponseLivesInScalarRawMomentCoordinate,
		},
		Response: ResponseFunctionAudit{
			Audited:                  true,
			Function:                 "f_3(x)=x+kappa_e_red x^2-2p x^3",
			ExpectationFormula:       "Tr(rho_72 f_3(R_wall))=p s+kappa_e_red p s^2-2p^2s^3",
			ComputedExpectation:      fwall,
			MatchesLedger:            matches,
			WrittenAsExpectation:     true,
			NativeGeneratingFunction: false,
			Distinction:              "writing f_3 is a representation of the bridge polynomial, not a native derivation of the generating function.",
			Verdict:                  StatusFWall3RedExpectationOfCubicResponseFunction,
		},
		Coefficients: CoefficientSourceAudit{
			Audited:                      true,
			LeadingCoefficient:           "1: leading no-bias boundary response coefficient",
			QuadraticCoefficient:         "kappa_e_red: flavor-wall modulation coefficient",
			CubicCoefficient:             "-2p: boundary-pair / double-K7-event stress-pull candidate",
			TwoP:                         2 * p,
			BoundaryPairCandidate:        "2p=(dim B_boundary) p=2*(7/72)=7/36",
			BoundaryEndpoints:            []string{"|lambda(Lambda12)|", "R3-1"},
			NativeBoundaryPairTheorem:    false,
			TypedOperatorMapSourcesCubic: false,
			Verdict:                      Status2PBoundaryPairK7EventWeightSourceType,
		},
		CubicStop: CubicStopAudit{
			Audited:                         true,
			ProjectorAlgebraStopsPowers:     false,
			BoundaryPairExteriorCandidate:   true,
			RequiredExteriorMap:             "M1 -> leading event, M2 -> degree-1 boundary modulation, M3 -> degree-2 boundary-pair stress pull, M4 forbidden by Lambda^3 B_boundary=0",
			RawMomentToExteriorMapCertified: false,
			NativeCubicStopTheorem:          false,
			UntypedM4FitRejected:            true,
			TypedFourthOrderCoefficient:     false,
			Verdict:                         StatusCubicStopBoundaryPairExteriorDegreeCandidate,
		},
		Coordinate: RawMomentCoordinateAudit{
			Audited:                   true,
			RawMomentForm:             "M_n=p s^n",
			VarianceForm:              "p(1-p)s^2",
			CentralThirdMomentForm:    "p(1-p)(1-2p)s^3",
			ActiveCoordinate:          "raw moments, not variance/cumulant/central-moment coordinates",
			VarianceActive:            false,
			CentralMomentActive:       false,
			NativeRawMomentCoordinate: false,
			Verdict:                   StatusRawMomentCoordinatePreserved,
		},
		Runtime: RuntimeIndependenceAudit{
			Audited:                          true,
			Formula:                          "F_wall_3_red=p s+kappa_e_red p s^2-2p^2s^3",
			FormulaLevelRuntimeTargetAbsence: true,
			EvaluableWithoutDirectHiggsRuntimeVariables: true,
			NativeBoundaryResponseTheorem:               false,
			NativeCubicCoefficientTheorem:               false,
			NativeCubicStopTheorem:                      false,
			KappaERedFlavorSealed:                       true,
			Verdict:                                     StatusFWall3RedEvaluableWithoutDirectHiggsRuntimeVariables,
		},
		Relation: RelationStatus{
			Recorded:              true,
			KappaLambdaRelation:   "kappa_lambda_red=|lambda|+F_wall_3_red-kappa_e_red",
			FWallLevel:            "Level B formula independence; raw-moment response polynomial remains bridge-layer.",
			KappaLambdaLevel:      "Level B formula independence inherited from Gate782.",
			CHistoryLevel:         "Level B semi-independent bridge component.",
			CHiggsLevel:           "not Level C.",
			BoundarySubBottleneck: "F_wall_3_red is the boundary sub-bottleneck inside kappa_lambda_red.",
			CHistoryIndependent:   false,
			Verdict:               StatusFWall3RedNowBoundarySubBottleneck,
		},
		Prediction: PredictionLevelClassification{
			Recorded:         true,
			LevelA:           "algebraic identity / consistency closure",
			LevelB:           "semi-independent bridge estimate using external boundary/flavor data but no direct Higgs/runtime target variables",
			LevelC:           "independent tree-level prediction from native ASHA theorems",
			LevelD:           "physical pole-mass prediction after correction package",
			FWall3Level:      "Level B formula independence",
			KappaLambdaLevel: "Level B",
			CHistoryLevel:    "Level B",
			CHiggsLevel:      "still not Level C",
		},
		Firewalls: Firewalls{
			Enforced: true,
			Verdict:  StatusFirewallPreservedGate783,
		},
	}
	a.Truth = "Gate 783 source-types F_wall_3_red as a cubic raw-moment boundary response expectation, but it does not certify a native boundary response generating function or cubic stop theorem."
	a.FinalStatement = "Gate 783 does not make F_wall_3_red native. It improves the status by showing that F_wall_3_red can be written as a cubic raw-response expectation and that the cubic coefficient 2p has a typed boundary-pair times K7-event source candidate. The next bottleneck is the missing native map that would turn the raw moment polynomial into a true boundary response generating function, especially a map explaining why the expansion stops at the cubic term rather than continuing to untyped higher moments."
	return a, nil
}

func Statuses() []string {
	return []string{
		StatusGate782BoundaryFlavorComplementInherited,
		StatusProjectorPowerDegeneracyAudited,
		StatusRawMomentsReduceToScalarResponseCoordinates,
		StatusResponseFunctionRepresentationDefined,
		StatusCubicCoefficientRewrittenAs2P,
		StatusCubicStopCandidatesAudited,
		StatusUntypedM4FitRejected,
		StatusRawMomentCoordinatePreserved,
		StatusFWallFormulaLevelRuntimeTargetAbsenceAudited,
		StatusRelationToKappaLambdaRedAndCHistoryRecorded,
		StatusPredictionLevelClassificationRecorded,
		StatusPhysicalFirewallsEnforced,
		StatusFWall3RedTypedBoundaryRawMomentResponse,
		StatusFWall3RedExpectationOfCubicResponseFunction,
		Status2PBoundaryPairK7EventWeightSourceType,
		StatusCubicStopBoundaryPairExteriorDegreeCandidate,
		StatusFWall3RedEvaluableWithoutDirectHiggsRuntimeVariables,
		StatusFWall3RedNowBoundarySubBottleneck,
		StatusResponseFunctionNotYetNativeGeneratingFunction,
		StatusNoNativeBoundaryResponseGeneratingFunctionTheorem,
		StatusNoNativeRawMomentCoordinateTheorem,
		StatusNoNativeBoundaryPairStressPullTheorem,
		StatusNoNativeRawMomentToBoundaryExteriorDegreeMap,
		StatusNoNativeCubicStopTheorem,
		StatusNoTypedFourthOrderCoefficientSource,
		StatusFWall3RedNotYetNativeBoundaryResponseTheorem,
		StatusCHistoryNotYetFullIndependentPredictionComponent,
		StatusTreeProxyNotPoleMass,
		StatusNoYukawaOperatorOrEigenvalueTheorem,
		StatusFirewallPreservedGate783,
	}
}

func closeRel(got, want, tol float64) bool {
	if math.IsNaN(got) || math.IsInf(got, 0) || math.IsNaN(want) || math.IsInf(want, 0) {
		return false
	}
	d := math.Abs(got - want)
	if d <= tol {
		return true
	}
	den := math.Max(1, math.Abs(want))
	return d/den <= tol
}

func containsAll(haystack []string, needles []string) bool {
	joined := strings.Join(haystack, "\n")
	for _, n := range needles {
		if !strings.Contains(joined, n) {
			return false
		}
	}
	return true
}

func FormatLedger(l MomentLedger) string {
	return fmt.Sprintf("p=%.17g s=%.17g M1=%.17g M2=%.17g M3=%.17g F_wall_3_red=%.17g matches=%v", l.P, l.S, l.M1, l.M2, l.M3, l.FWall3, l.Matches)
}

func FormatOperator(o OperatorBoardAudit) string {
	return fmt.Sprintf("%s; %s; same_support=%v independent_operator_geometry=%v", o.Operator, o.PowerLaw, o.AllMomentsSameSupport, o.IndependentOperatorGeometry)
}

func FormatResponse(r ResponseFunctionAudit) string {
	return fmt.Sprintf("%s; %s; native_generating_function=%v; %.17g", r.Function, r.ExpectationFormula, r.NativeGeneratingFunction, r.ComputedExpectation)
}

func FormatCoefficients(c CoefficientSourceAudit) string {
	return fmt.Sprintf("%s; %s; %s; 2p=%.17g; native_pair_theorem=%v typed_operator=%v", c.LeadingCoefficient, c.QuadraticCoefficient, c.CubicCoefficient, c.TwoP, c.NativeBoundaryPairTheorem, c.TypedOperatorMapSourcesCubic)
}

func FormatCubicStop(c CubicStopAudit) string {
	return fmt.Sprintf("projector_stop=%v exterior_candidate=%v map_certified=%v native_stop=%v M4_rejected=%v", c.ProjectorAlgebraStopsPowers, c.BoundaryPairExteriorCandidate, c.RawMomentToExteriorMapCertified, c.NativeCubicStopTheorem, c.UntypedM4FitRejected)
}

func FormatRuntime(r RuntimeIndependenceAudit) string {
	return fmt.Sprintf("formula=%s runtime_absence=%v evaluable=%v native_response=%v native_cubic=%v kappa_e_sealed=%v", r.Formula, r.FormulaLevelRuntimeTargetAbsence, r.EvaluableWithoutDirectHiggsRuntimeVariables, r.NativeBoundaryResponseTheorem, r.NativeCubicCoefficientTheorem, r.KappaERedFlavorSealed)
}

func FormatRelation(r RelationStatus) string {
	return fmt.Sprintf("F_wall=%s; kappa_lambda=%s; C_History=%s; C_Higgs=%s", r.FWallLevel, r.KappaLambdaLevel, r.CHistoryLevel, r.CHiggsLevel)
}
