package higgs

import (
	"fmt"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func VacuumMixingTheorem() theorem.Theorem {
	const id = "GAUGE-HIGGS-VACUUM-MIXING"
	const name = "finite Higgs/vacuum-mixing sector from off-diagonal projected connection"
	return theorem.Theorem{
		ID:     id,
		Name:   name,
		Layer:  theorem.LayerGauge,
		Status: theorem.VerifiedNumeric,
		Verify: func() theorem.Result {
			const eps = 1e-8
			a, err := BuildDefault()
			if err != nil {
				return theorem.Result{
					ID: id, Name: name, Layer: theorem.LayerGauge, Status: theorem.FailedRoute,
					Checks: []theorem.Check{{Name: "construct Higgs/vacuum-mixing analysis", Passed: false, Detail: err.Error()}},
				}
			}
			offDiagonalOK := a.MaxOffDiagonalBlockResidual < eps
			skewOK := a.MaxSkewResidual < eps
			positiveOK := a.MaxPositiveResidual < eps
			nontrivialOK := a.TotalMixingNormSquared > eps && a.HiggsSpanRank > 0
			vacuumActiveOK := a.VacuumMixingRank > 0
			traceBalancedOK := abs(a.VacuumMixingTrace-a.ComplementMixingTrace) < 1e-8

			status := theorem.VerifiedNumeric
			if !offDiagonalOK || !skewOK || !positiveOK || !nontrivialOK {
				status = theorem.OpenTest
			}

			checks := []theorem.Check{
				{
					Name:   "canonical field definition",
					Passed: len(a.HiggsFields) == len(a.Connection.Compression.BooleanGenerators),
					Detail: fmt.Sprintf("built Φ_i=P_C A_i P_K+P_K A_i P_C for %d compressed connection generators", len(a.HiggsFields)),
				},
				{
					Name:   "pure off-diagonal block form",
					Passed: offDiagonalOK,
					Detail: fmt.Sprintf("max ||P_CΦP_C||+||P_KΦP_K|| = %.3e", a.MaxOffDiagonalBlockResidual),
				},
				{
					Name:   "skew connection component",
					Passed: skewOK,
					Detail: fmt.Sprintf("max ||Φ+Φᵀ||_F = %.3e", a.MaxSkewResidual),
				},
				{
					Name:   "nontrivial vacuum-mixing sector",
					Passed: nontrivialOK,
					Detail: fmt.Sprintf("span rank=%d, total Σ||Φ_i||² = %.10f", a.HiggsSpanRank, a.TotalMixingNormSquared),
				},
				{
					Name:   "positive mixing operators",
					Passed: positiveOK,
					Detail: fmt.Sprintf("largest negative-eigenvalue violation across ΦᵀΦ blocks = %.3e", a.MaxPositiveResidual),
				},
				{
					Name:   "contact vacuum directions coupled",
					Passed: vacuumActiveOK,
					Detail: fmt.Sprintf("rank M_K=%d inside dim(K)=%d, unmixed contact directions=%d; top spectrum %s", a.VacuumMixingRank, a.ContactDimension, a.VacuumUnmixedDimension, formatFloats(TopSpectrum(a.VacuumMixingSpectrum, 8))),
				},
				{
					Name:   "complement response rank",
					Passed: a.ComplementMixingRank > 0,
					Detail: fmt.Sprintf("rank M_C=%d inside the 49D complement; top spectrum %s", a.ComplementMixingRank, formatFloats(TopSpectrum(a.ComplementMixingSpectrum, 8))),
				},
				{
					Name:   "trace balance between K and K⊥ mixing",
					Passed: traceBalancedOK,
					Detail: fmt.Sprintf("Tr(M_K)=%.10f, Tr(M_C)=%.10f", a.VacuumMixingTrace, a.ComplementMixingTrace),
				},
			}
			notes := []string{
				"This gate does not derive the physical Higgs boson mass; it identifies the finite object that the bridge layer must use.",
				"The previous closure defect is now reinterpreted as second-fundamental curvature generated by Φ, the off-diagonal connection component between K and K⊥.",
				"The contact-vacuum mixing rank is a derived finite invariant. In this run it is partial, not full; those untouched contact directions must be interpreted before any mass claim.",
				"A future dynamics gate should build a Higgs potential or Yukawa operator from these positive mixing spectra, not from projector traces.",
			}
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerGauge, Status: status, Checks: checks, Notes: notes}
		},
	}
}

func formatFloats(values []float64) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = fmt.Sprintf("%.10g", value)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func abs(x float64) float64 {
	if x < 0 {
		return -x
	}
	return x
}
