// Package diracorderone implements Gate 164: finite Dirac candidate
// construction / order-one axiom obstruction audit.
//
// Gate 163 proved that exact spectral pre-data exist, but that no finite
// spectral action is lawful until a spectral triple is constructed. Gate 164
// asks the next narrower question: can any currently available finite operator
// be promoted to a nontrivial Dirac operator satisfying the order-one axiom?
//
// The answer is again conservative. Contact-only choices built from the exact
// contact overlap Omega are order-one-safe only in the vacuous sense: for the
// commutative spectral algebra generated by Omega, all commutators vanish and
// therefore the first-order condition has no content and no gauge fluctuation.
// Every nontrivial mixed-sector candidate requires a missing canonical algebra
// representation, real structure J, grading gamma, or sector map. Hence no
// physical beta row, action coefficient, mass, scale, or coupling is opened.
package diracorderone

import (
	"fmt"
	"sort"
	"strings"
	"sync"

	"github.com/bagherbal/asha-engine/pkg/bridge/spectralaction"
)

type RepresentationCandidate struct {
	Name                     string
	Carrier                  string
	Source                   string
	Available                bool
	Canonical                bool
	FaithfulOnTotalHilbert   bool
	Commutative              bool
	GeneratesNonzeroOneForms bool
	GaugeFluctuationTrivial  bool
	RequiresBranchChoice     bool
	UsesObservedInput        bool
	Verdict                  string
}

type RealStructureCandidate struct {
	Name                  string
	Carrier               string
	Available             bool
	CanonicalOnCarrier    bool
	CanonicalOnTotalSpace bool
	KOCompatibilityKnown  bool
	ChargeConjugationMap  bool
	RequiresQuarticSplit  bool
	UsesBranchChoice      bool
	UsesObservedInput     bool
	Verdict               string
}

type GradingCandidate struct {
	Name                  string
	Carrier               string
	Available             bool
	GaloisInvariant       bool
	Nontrivial            bool
	CanonicalOnCarrier    bool
	CanonicalOnTotalSpace bool
	OddDiracCompatible    bool
	RequiresQuarticSplit  bool
	UsesBranchChoice      bool
	UsesObservedInput     bool
	Verdict               string
}

type DiracConstruction struct {
	Name                       string
	Formula                    string
	Carrier                    string
	ExactOverQ                 bool
	SelfAdjoint                bool
	FiniteSpectrum             bool
	GaloisInvariant            bool
	BranchFree                 bool
	UsesObservedInput          bool
	UsesBranchChoice           bool
	RepresentationCanonical    bool
	RealStructureCanonical     bool
	GradingCanonical           bool
	TotalHilbertCompatible     bool
	OrderOneTestable           bool
	OrderOneVerified           bool
	OrderOneVacuous            bool
	NontrivialCommutators      bool
	GaugeFluctuationNontrivial bool
	GaugeFluctuationTrivial    bool
	RequiresAlgebraRep         bool
	RequiresRealStructure      bool
	RequiresGrading            bool
	RequiresSectorMap          bool
	RequiresBranchBreaking     bool
	PromotableToFiniteDirac    bool
	GaugeKineticMapRows        int
	BoundaryConstraintsDerived int
	ThresholdBetaRows          int
	PhysicalConstantsDerived   bool
	Verdict                    string
}

type RepresentationAudit struct {
	CandidatesAudited            int
	AvailableCandidates          int
	CanonicalCandidates          int
	FaithfulTotalRepresentations int
	CommutativeCandidates        int
	NonzeroOneFormCandidates     int
	GaugeTrivialCandidates       int
	BranchChoicesUsed            int
	ObservedInputsUsed           bool
	Verdict                      string
}

type RealStructureAudit struct {
	CandidatesAudited           int
	AvailableCandidates         int
	CanonicalCarrierCandidates  int
	CanonicalTotalCandidates    int
	KOCompatibleCandidates      int
	ChargeConjugationCandidates int
	QuarticSplitRequired        int
	BranchChoicesUsed           int
	ObservedInputsUsed          bool
	Verdict                     string
}

type GradingAudit struct {
	CandidatesAudited          int
	AvailableCandidates        int
	GaloisInvariantCandidates  int
	NontrivialCandidates       int
	CanonicalCarrierCandidates int
	CanonicalTotalCandidates   int
	OddDiracCompatible         int
	QuarticSplitRequired       int
	BranchChoicesUsed          int
	ObservedInputsUsed         bool
	Verdict                    string
}

type OrderOneAudit struct {
	DiracCandidatesAudited         int
	ExactCandidates                int
	SelfAdjointCandidates          int
	FiniteSpectrumCandidates       int
	GaloisInvariantCandidates      int
	BranchFreeCandidates           int
	ObservedInputsUsed             bool
	BranchChoicesUsed              int
	RepresentationCanonical        int
	RealStructureCanonical         int
	GradingCanonical               int
	TotalHilbertCompatible         int
	OrderOneTestable               int
	OrderOneVerified               int
	OrderOneVacuous                int
	NontrivialCommutatorCandidates int
	NontrivialOrderOneVerified     int
	GaugeFluctuationNontrivial     int
	GaugeFluctuationTrivial        int
	RequiresAlgebraRep             int
	RequiresRealStructure          int
	RequiresGrading                int
	RequiresSectorMap              int
	RequiresBranchBreaking         int
	PromotableFiniteDirac          int
	GaugeKineticMapRows            int
	BoundaryConstraintsDerived     int
	ThresholdBetaRows              int
	PhysicalConstantsDerived       bool
	Verdict                        string
}

type FirewallAudit struct {
	Gate163Inherited             bool
	FiniteSpectralPreData        bool
	ContactOnlyOrderOneVacuous   int
	NontrivialOrderOneVerified   int
	PromotableFiniteDirac        int
	SpectralTripleComplete       bool
	FiniteDiracSelected          bool
	RealStructureSelected        bool
	GradingSelected              bool
	OrderOneCalculusVerified     bool
	GaugeFluctuationMapDerived   bool
	GaugeKineticMapRows          int
	IndividualQuarticRows        int
	CanonicalQuarticBranches     int
	GaugeRepresentationRows      int
	LocalFieldRows               int
	MassActivationRows           int
	DecouplingRows               int
	DynkinIndexRows              int
	ThresholdBetaRows            int
	ProvenZeroRows               int
	BoundaryConstraintsDerived   int
	PhysicalConstantsDerived     bool
	BetaPermissionFirewallClosed bool
	Verdict                      string
}

type Summary struct {
	ContactRows                     int
	ZetaValuesComputed              int
	RepresentationCandidatesAudited int
	CanonicalRepresentations        int
	FaithfulTotalRepresentations    int
	RealStructuresAudited           int
	CanonicalTotalRealStructures    int
	GradingsAudited                 int
	CanonicalTotalGradings          int
	DiracCandidatesAudited          int
	OrderOneVerified                int
	OrderOneVacuous                 int
	NontrivialOrderOneVerified      int
	PromotableFiniteDirac           int
	GaugeKineticMapRows             int
	BoundaryConstraintsDerived      int
	ThresholdBetaRows               int
	ResidualNullityBefore           int
	ResidualNullityAfter            int
}

type Analysis struct {
	Previous spectralaction.Analysis

	Representations []RepresentationCandidate
	RealStructures  []RealStructureCandidate
	Gradings        []GradingCandidate
	DiracCandidates []DiracConstruction

	RepresentationAudit RepresentationAudit
	RealStructureAudit  RealStructureAudit
	GradingAudit        GradingAudit
	OrderOneAudit       OrderOneAudit
	Firewall            FirewallAudit
	Summary             Summary

	ContactRows                  int
	ContactZetaValues            int
	ExactRationalOverlapMatrix   bool
	ExactCharacteristicCertified bool
	ExactRootIsolationCertified  bool
	FiniteSpectralPreData        bool
	SpectralTripleComplete       bool
	FiniteDiracSelected          bool
	RealStructureSelected        bool
	GradingSelected              bool
	OrderOneCalculusVerified     bool
	OrientabilityVerified        bool
	PoincareDualityVerified      bool
	KOCompatibilityVerified      bool
	CanonicalCutoffSelected      bool
	GaugeFluctuationMapDerived   bool
	SpectralActionPrincipleReady bool
	GaugeKineticMapRows          int
	IndividualQuarticRows        int
	CanonicalQuarticBranches     int
	GaugeRepresentationRows      int
	SpinStatisticsRows           int
	LocalFieldRows               int
	MassActivationRows           int
	DecouplingRows               int
	DynkinIndexRows              int
	ThresholdBetaRows            int
	ProvenZeroRows               int
	BoundaryConstraintsDerived   int
	ContactBetaRowsAllowed       int
	ContactZeroRowsProved        int
	BetaPermissionFirewallClosed bool
	ThresholdCorrectedBeta       bool
	FullBetaMatchingTensor       bool
	ResidualNullityBefore        int
	ResidualNullityAfter         int
	HiddenObservedInputUsed      bool
	PhysicalWeakAngleDerived     bool
	FineStructureDerived         bool
	PhysicalMassesDerived        bool
	PhysicalScaleDerived         bool

	TruthStatement      string
	RejectedClaims      []string
	RemainingUnknowns   []string
	RecommendedNextGate string
}

var defaultOnce sync.Once
var defaultValue Analysis
var defaultErr error

func BuildDefault() (Analysis, error) {
	defaultOnce.Do(func() {
		prev, err := spectralaction.BuildDefault()
		if err != nil {
			defaultErr = err
			return
		}
		defaultValue, defaultErr = Build(prev)
	})
	return defaultValue, defaultErr
}

func Build(prev spectralaction.Analysis) (Analysis, error) {
	if !prev.FiniteSpectralPreData || prev.ContactRows != 7 || prev.ContactZetaValues != 5 || !prev.BetaPermissionFirewallClosed {
		return Analysis{}, fmt.Errorf("Gate 164 requires Gate 163 finite spectral pre-data and closed firewall")
	}
	if prev.SpectralTripleComplete || prev.FiniteDiracSelected || prev.RealStructureSelected || prev.GradingSelected || prev.OrderOneCalculusVerified || prev.GaugeFluctuationMapDerived || prev.GaugeKineticMapRows != 0 {
		return Analysis{}, fmt.Errorf("Gate 164 expects Gate 163 to leave the spectral-triple chain unselected")
	}
	if prev.HiddenObservedInputUsed || prev.PhysicalWeakAngleDerived || prev.FineStructureDerived || prev.PhysicalMassesDerived || prev.PhysicalScaleDerived {
		return Analysis{}, fmt.Errorf("Gate 164 refuses hidden observed physical input")
	}

	reps := representationCandidates()
	reals := realStructureCandidates()
	gradings := gradingCandidates()
	diracs := finiteDiracConstructions()

	repAudit := auditRepresentations(reps)
	realAudit := auditRealStructures(reals)
	gradingAudit := auditGradings(gradings)
	orderOneAudit := auditOrderOne(diracs)

	firewall := FirewallAudit{
		Gate163Inherited:             true,
		FiniteSpectralPreData:        prev.FiniteSpectralPreData,
		ContactOnlyOrderOneVacuous:   orderOneAudit.OrderOneVacuous,
		NontrivialOrderOneVerified:   orderOneAudit.NontrivialOrderOneVerified,
		PromotableFiniteDirac:        orderOneAudit.PromotableFiniteDirac,
		SpectralTripleComplete:       false,
		FiniteDiracSelected:          false,
		RealStructureSelected:        false,
		GradingSelected:              false,
		OrderOneCalculusVerified:     false,
		GaugeFluctuationMapDerived:   false,
		GaugeKineticMapRows:          0,
		IndividualQuarticRows:        0,
		CanonicalQuarticBranches:     0,
		GaugeRepresentationRows:      0,
		LocalFieldRows:               0,
		MassActivationRows:           0,
		DecouplingRows:               0,
		DynkinIndexRows:              0,
		ThresholdBetaRows:            0,
		ProvenZeroRows:               0,
		BoundaryConstraintsDerived:   0,
		PhysicalConstantsDerived:     false,
		BetaPermissionFirewallClosed: true,
		Verdict:                      "contact-only Dirac diagnostics satisfy order-one only vacuously; nontrivial Dirac candidates lack the canonical representation/J/gamma chain required for a finite spectral triple",
	}

	summary := Summary{
		ContactRows:                     prev.ContactRows,
		ZetaValuesComputed:              prev.ContactZetaValues,
		RepresentationCandidatesAudited: len(reps),
		CanonicalRepresentations:        repAudit.CanonicalCandidates,
		FaithfulTotalRepresentations:    repAudit.FaithfulTotalRepresentations,
		RealStructuresAudited:           len(reals),
		CanonicalTotalRealStructures:    realAudit.CanonicalTotalCandidates,
		GradingsAudited:                 len(gradings),
		CanonicalTotalGradings:          gradingAudit.CanonicalTotalCandidates,
		DiracCandidatesAudited:          len(diracs),
		OrderOneVerified:                orderOneAudit.OrderOneVerified,
		OrderOneVacuous:                 orderOneAudit.OrderOneVacuous,
		NontrivialOrderOneVerified:      orderOneAudit.NontrivialOrderOneVerified,
		PromotableFiniteDirac:           orderOneAudit.PromotableFiniteDirac,
		GaugeKineticMapRows:             orderOneAudit.GaugeKineticMapRows,
		BoundaryConstraintsDerived:      orderOneAudit.BoundaryConstraintsDerived,
		ThresholdBetaRows:               orderOneAudit.ThresholdBetaRows,
		ResidualNullityBefore:           prev.ResidualNullityAfter,
		ResidualNullityAfter:            prev.ResidualNullityAfter,
	}

	truth := "Gate 164 audits finite Dirac construction against the order-one axiom. Operators built only from the contact overlap Omega are exact, self-adjoint, Galois-invariant, and branch-free, and they satisfy the order-one condition only because the commutators in the contact spectral algebra vanish. That makes their gauge fluctuations trivial. The nontrivial mixed-sector Dirac candidates would be physically relevant, but each requires a missing canonical representation on the total finite Hilbert space together with a real structure, grading, and sector map. Therefore no finite Dirac operator is selected and the spectral-action/beta bridge remains sealed."

	return Analysis{
		Previous:                     prev,
		Representations:              reps,
		RealStructures:               reals,
		Gradings:                     gradings,
		DiracCandidates:              diracs,
		RepresentationAudit:          repAudit,
		RealStructureAudit:           realAudit,
		GradingAudit:                 gradingAudit,
		OrderOneAudit:                orderOneAudit,
		Firewall:                     firewall,
		Summary:                      summary,
		ContactRows:                  prev.ContactRows,
		ContactZetaValues:            prev.ContactZetaValues,
		ExactRationalOverlapMatrix:   prev.ExactRationalOverlapMatrix,
		ExactCharacteristicCertified: prev.ExactCharacteristicCertified,
		ExactRootIsolationCertified:  prev.ExactRootIsolationCertified,
		FiniteSpectralPreData:        prev.FiniteSpectralPreData,
		SpectralTripleComplete:       false,
		FiniteDiracSelected:          false,
		RealStructureSelected:        false,
		GradingSelected:              false,
		OrderOneCalculusVerified:     false,
		OrientabilityVerified:        false,
		PoincareDualityVerified:      false,
		KOCompatibilityVerified:      false,
		CanonicalCutoffSelected:      false,
		GaugeFluctuationMapDerived:   false,
		SpectralActionPrincipleReady: false,
		GaugeKineticMapRows:          0,
		IndividualQuarticRows:        0,
		CanonicalQuarticBranches:     0,
		GaugeRepresentationRows:      0,
		SpinStatisticsRows:           0,
		LocalFieldRows:               0,
		MassActivationRows:           0,
		DecouplingRows:               0,
		DynkinIndexRows:              0,
		ThresholdBetaRows:            0,
		ProvenZeroRows:               0,
		BoundaryConstraintsDerived:   0,
		ContactBetaRowsAllowed:       0,
		ContactZeroRowsProved:        0,
		BetaPermissionFirewallClosed: true,
		ThresholdCorrectedBeta:       false,
		FullBetaMatchingTensor:       false,
		ResidualNullityBefore:        prev.ResidualNullityAfter,
		ResidualNullityAfter:         prev.ResidualNullityAfter,
		HiddenObservedInputUsed:      false,
		PhysicalWeakAngleDerived:     false,
		FineStructureDerived:         false,
		PhysicalMassesDerived:        false,
		PhysicalScaleDerived:         false,
		TruthStatement:               truth,
		RejectedClaims: []string{
			"Omega_contact is automatically a physical finite Dirac operator",
			"a vacuous order-one check produces gauge fluctuations or gauge kinetic rows",
			"the quartic block can be graded by hand to build a nontrivial J/gamma pair",
			"mixed scalar-contact or Fock-scalar Dirac blocks are canonical without a sector map",
			"finite Dirac diagnostics derive spectral-action coefficients, threshold beta rows, or physical constants",
		},
		RemainingUnknowns: []string{
			"faithful canonical representation of the finite algebra on the total spectral Hilbert carrier",
			"real structure J with KO compatibility across contact, scalar, and Fock sectors",
			"global grading gamma that is Galois-safe and compatible with a nontrivial odd Dirac operator",
			"nontrivial finite Dirac block with verified first-order condition",
			"gauge fluctuation map from [D,A] one-forms to gauge kinetic rows",
		},
		RecommendedNextGate: "Gate 165 — finite algebra representation on total spectral Hilbert space / faithful action obstruction audit",
	}, nil
}

func representationCandidates() []RepresentationCandidate {
	return []RepresentationCandidate{
		{
			Name:                     "contact spectral algebra C[Omega]",
			Carrier:                  "seven-row contact spectral carrier",
			Source:                   "Gates 149-162",
			Available:                true,
			Canonical:                true,
			FaithfulOnTotalHilbert:   false,
			Commutative:              true,
			GeneratesNonzeroOneForms: false,
			GaugeFluctuationTrivial:  true,
			Verdict:                  "canonical contact-only representation; order-one is vacuous and gauge fluctuations vanish",
		},
		{
			Name:                     "Boolean/G2 projector algebra on exterior chamber",
			Carrier:                  "Lambda^4 R^8 projector carrier",
			Source:                   "Gates 1-5,149",
			Available:                true,
			Canonical:                true,
			FaithfulOnTotalHilbert:   false,
			Commutative:              false,
			GeneratesNonzeroOneForms: false,
			GaugeFluctuationTrivial:  true,
			Verdict:                  "exact finite projector data exist, but no total spectral-Hilbert representation or nonzero one-form calculus is derived",
		},
		{
			Name:                     "Cl(1,7) bookkeeping action",
			Carrier:                  "Clifford bookkeeping carrier",
			Source:                   "Gate 2",
			Available:                true,
			Canonical:                false,
			FaithfulOnTotalHilbert:   false,
			Commutative:              false,
			GeneratesNonzeroOneForms: false,
			GaugeFluctuationTrivial:  true,
			Verdict:                  "Clifford bookkeeping exists, but a faithful spectral-triple representation on the total carrier is not selected",
		},
		{
			Name:                     "Fock/scalar matter representation fragments",
			Carrier:                  "H_Fock tensor H_Phi",
			Source:                   "Gates 12-25",
			Available:                true,
			Canonical:                false,
			FaithfulOnTotalHilbert:   false,
			Commutative:              false,
			GeneratesNonzeroOneForms: false,
			GaugeFluctuationTrivial:  true,
			Verdict:                  "matter and scalar fragments exist, but they do not give a total contact/Fock/scalar spectral representation with J and gamma",
		},
		{
			Name:                     "formal total direct-sum algebra",
			Carrier:                  "H_contact ⊕ H_Fock⊗H_Phi",
			Source:                   "formal Gate 164 test object",
			Available:                false,
			Canonical:                false,
			FaithfulOnTotalHilbert:   false,
			Commutative:              false,
			GeneratesNonzeroOneForms: false,
			GaugeFluctuationTrivial:  true,
			Verdict:                  "the desired total algebra is exactly what remains to be constructed; using it here would be circular",
		},
	}
}

func realStructureCandidates() []RealStructureCandidate {
	return []RealStructureCandidate{
		{
			Name:                  "real conjugation on rational contact carrier",
			Carrier:               "contact spectral carrier",
			Available:             true,
			CanonicalOnCarrier:    true,
			CanonicalOnTotalSpace: false,
			KOCompatibilityKnown:  false,
			ChargeConjugationMap:  false,
			Verdict:               "real contact matrices admit a carrier-level conjugation, but it is not the physical real structure J of a total spectral triple",
		},
		{
			Name:                  "Fock particle/antiparticle conjugation diagnostic",
			Carrier:               "Fock bookkeeping carrier",
			Available:             true,
			CanonicalOnCarrier:    false,
			CanonicalOnTotalSpace: false,
			KOCompatibilityKnown:  false,
			ChargeConjugationMap:  true,
			Verdict:               "charge-conjugation diagnostics exist, but previous gates did not derive a total J compatible with contact rows",
		},
		{
			Name:                  "quartic ghost-pairing real structure",
			Carrier:               "quartic contact block",
			Available:             false,
			CanonicalOnCarrier:    false,
			CanonicalOnTotalSpace: false,
			RequiresQuarticSplit:  true,
			UsesBranchChoice:      true,
			Verdict:               "would require a nontrivial quartic split, forbidden by the Galois grading firewall",
		},
		{
			Name:                  "global finite spectral-triple J",
			Carrier:               "total spectral Hilbert carrier",
			Available:             false,
			CanonicalOnCarrier:    false,
			CanonicalOnTotalSpace: false,
			KOCompatibilityKnown:  false,
			ChargeConjugationMap:  false,
			Verdict:               "global J is a missing construction, not an available input",
		},
	}
}

func gradingCandidates() []GradingCandidate {
	return []GradingCandidate{
		{
			Name:                  "uniform contact grading",
			Carrier:               "contact spectral carrier",
			Available:             true,
			GaloisInvariant:       true,
			Nontrivial:            false,
			CanonicalOnCarrier:    true,
			CanonicalOnTotalSpace: false,
			OddDiracCompatible:    false,
			Verdict:               "Galois-safe but trivial; it cannot make a nonzero odd Dirac operator or ghost cancellation",
		},
		{
			Name:                  "quartic two/two ghost grading",
			Carrier:               "quartic contact block",
			Available:             false,
			GaloisInvariant:       false,
			Nontrivial:            true,
			CanonicalOnCarrier:    false,
			CanonicalOnTotalSpace: false,
			OddDiracCompatible:    false,
			RequiresQuarticSplit:  true,
			UsesBranchChoice:      true,
			Verdict:               "nontrivial but branch-dependent; Gate 159 forbids it as canonical data",
		},
		{
			Name:                  "scalar active-sector grading",
			Carrier:               "four-real scalar active carrier",
			Available:             true,
			GaloisInvariant:       true,
			Nontrivial:            true,
			CanonicalOnCarrier:    true,
			CanonicalOnTotalSpace: false,
			OddDiracCompatible:    false,
			Verdict:               "valid scalar-sector diagnostic, but no total contact/Fock/scalar gamma is derived",
		},
		{
			Name:                  "matter chirality/T3R grading",
			Carrier:               "Fock/matter carrier",
			Available:             true,
			GaloisInvariant:       true,
			Nontrivial:            true,
			CanonicalOnCarrier:    false,
			CanonicalOnTotalSpace: false,
			OddDiracCompatible:    false,
			Verdict:               "matter-side chirality search remains variational and does not grade the total spectral carrier",
		},
		{
			Name:                  "global finite spectral-triple gamma",
			Carrier:               "total spectral Hilbert carrier",
			Available:             false,
			GaloisInvariant:       false,
			Nontrivial:            false,
			CanonicalOnCarrier:    false,
			CanonicalOnTotalSpace: false,
			OddDiracCompatible:    false,
			Verdict:               "global grading is missing; assuming it would bypass the quartic grading theorem",
		},
	}
}

func finiteDiracConstructions() []DiracConstruction {
	contactVerdict := "exact contact-only diagnostic; first-order condition is satisfied only because [D,a]=0 in the spectral algebra, so there are no nontrivial one-forms or gauge fluctuations"
	return []DiracConstruction{
		contactDirac("contact overlap", "D = Omega_contact", contactVerdict),
		contactDirac("centered contact overlap", "D = Omega_contact - Tr(Omega)/7 I", contactVerdict),
		contactDirac("inverse contact overlap", "D = Omega_contact^{-1}", contactVerdict),
		contactDirac("quartic collective scalar block", "D = p_q(Omega_contact)", "exact Galois-invariant quartic-block diagnostic; it treats the quartic orbit collectively and remains gauge-trivial"),
		{
			Name:                    "scalar-contact off-diagonal block",
			Formula:                 "D = [[0, M_KC], [M_KC^*, 0]]",
			Carrier:                 "contact ⊕ scalar active carrier",
			ExactOverQ:              false,
			SelfAdjoint:             true,
			FiniteSpectrum:          true,
			GaloisInvariant:         false,
			BranchFree:              true,
			RepresentationCanonical: false,
			RealStructureCanonical:  false,
			GradingCanonical:        false,
			TotalHilbertCompatible:  false,
			OrderOneTestable:        false,
			NontrivialCommutators:   true,
			RequiresAlgebraRep:      true,
			RequiresRealStructure:   true,
			RequiresGrading:         true,
			RequiresSectorMap:       true,
			GaugeFluctuationTrivial: true,
			Verdict:                 "would be the first nontrivial Dirac block, but the scalar/contact map and total representation are not canonical",
		},
		{
			Name:                    "Fock-scalar Yukawa block",
			Formula:                 "D_Y = Y + Y^* on H_Fock⊗H_Phi",
			Carrier:                 "Fock ⊗ scalar carrier",
			ExactOverQ:              false,
			SelfAdjoint:             true,
			FiniteSpectrum:          true,
			GaloisInvariant:         true,
			BranchFree:              true,
			RepresentationCanonical: false,
			RealStructureCanonical:  false,
			GradingCanonical:        false,
			TotalHilbertCompatible:  false,
			OrderOneTestable:        false,
			NontrivialCommutators:   true,
			RequiresAlgebraRep:      true,
			RequiresRealStructure:   true,
			RequiresGrading:         true,
			RequiresSectorMap:       true,
			GaugeFluctuationTrivial: true,
			Verdict:                 "neutral Yukawa channels exist as selection rules, but no nonzero mass/source tensor is canonically selected",
		},
		{
			Name:                    "BRST differential symmetrization",
			Formula:                 "D_Q = Q + Q^*",
			Carrier:                 "contact constraint carrier",
			ExactOverQ:              true,
			SelfAdjoint:             true,
			FiniteSpectrum:          true,
			GaloisInvariant:         true,
			BranchFree:              true,
			RepresentationCanonical: false,
			RealStructureCanonical:  false,
			GradingCanonical:        false,
			TotalHilbertCompatible:  false,
			OrderOneTestable:        false,
			OrderOneVacuous:         true,
			GaugeFluctuationTrivial: true,
			RequiresAlgebraRep:      true,
			RequiresRealStructure:   true,
			RequiresGrading:         true,
			Verdict:                 "the only canonical BRST differential remains Q=0, so its symmetrization is inert rather than a physical Dirac operator",
		},
	}
}

func contactDirac(name, formula, verdict string) DiracConstruction {
	return DiracConstruction{
		Name:                       name,
		Formula:                    formula,
		Carrier:                    "seven-row contact spectral carrier",
		ExactOverQ:                 true,
		SelfAdjoint:                true,
		FiniteSpectrum:             true,
		GaloisInvariant:            true,
		BranchFree:                 true,
		RepresentationCanonical:    true,
		RealStructureCanonical:     false,
		GradingCanonical:           false,
		TotalHilbertCompatible:     false,
		OrderOneTestable:           true,
		OrderOneVerified:           true,
		OrderOneVacuous:            true,
		NontrivialCommutators:      false,
		GaugeFluctuationNontrivial: false,
		GaugeFluctuationTrivial:    true,
		RequiresRealStructure:      true,
		RequiresGrading:            true,
		PromotableToFiniteDirac:    false,
		Verdict:                    verdict,
	}
}

func auditRepresentations(items []RepresentationCandidate) RepresentationAudit {
	a := RepresentationAudit{CandidatesAudited: len(items), Verdict: "only the contact spectral representation is canonical, and it is gauge-trivial; no faithful total representation is available"}
	for _, item := range items {
		if item.Available {
			a.AvailableCandidates++
		}
		if item.Canonical {
			a.CanonicalCandidates++
		}
		if item.FaithfulOnTotalHilbert {
			a.FaithfulTotalRepresentations++
		}
		if item.Commutative {
			a.CommutativeCandidates++
		}
		if item.GeneratesNonzeroOneForms {
			a.NonzeroOneFormCandidates++
		}
		if item.GaugeFluctuationTrivial {
			a.GaugeTrivialCandidates++
		}
		if item.RequiresBranchChoice {
			a.BranchChoicesUsed++
		}
		if item.UsesObservedInput {
			a.ObservedInputsUsed = true
		}
	}
	return a
}

func auditRealStructures(items []RealStructureCandidate) RealStructureAudit {
	a := RealStructureAudit{CandidatesAudited: len(items), Verdict: "carrier-level conjugations exist, but no global KO-compatible real structure J is canonical"}
	for _, item := range items {
		if item.Available {
			a.AvailableCandidates++
		}
		if item.CanonicalOnCarrier {
			a.CanonicalCarrierCandidates++
		}
		if item.CanonicalOnTotalSpace {
			a.CanonicalTotalCandidates++
		}
		if item.KOCompatibilityKnown {
			a.KOCompatibleCandidates++
		}
		if item.ChargeConjugationMap {
			a.ChargeConjugationCandidates++
		}
		if item.RequiresQuarticSplit {
			a.QuarticSplitRequired++
		}
		if item.UsesBranchChoice {
			a.BranchChoicesUsed++
		}
		if item.UsesObservedInput {
			a.ObservedInputsUsed = true
		}
	}
	return a
}

func auditGradings(items []GradingCandidate) GradingAudit {
	a := GradingAudit{CandidatesAudited: len(items), Verdict: "partial gradings exist, but no global nontrivial Galois-safe gamma is canonical"}
	for _, item := range items {
		if item.Available {
			a.AvailableCandidates++
		}
		if item.GaloisInvariant {
			a.GaloisInvariantCandidates++
		}
		if item.Nontrivial {
			a.NontrivialCandidates++
		}
		if item.CanonicalOnCarrier {
			a.CanonicalCarrierCandidates++
		}
		if item.CanonicalOnTotalSpace {
			a.CanonicalTotalCandidates++
		}
		if item.OddDiracCompatible {
			a.OddDiracCompatible++
		}
		if item.RequiresQuarticSplit {
			a.QuarticSplitRequired++
		}
		if item.UsesBranchChoice {
			a.BranchChoicesUsed++
		}
		if item.UsesObservedInput {
			a.ObservedInputsUsed = true
		}
	}
	return a
}

func auditOrderOne(items []DiracConstruction) OrderOneAudit {
	a := OrderOneAudit{DiracCandidatesAudited: len(items), Verdict: "order-one succeeds only for gauge-trivial contact spectral functions; nontrivial Dirac blocks remain untestable and unpromotable"}
	for _, item := range items {
		if item.ExactOverQ {
			a.ExactCandidates++
		}
		if item.SelfAdjoint {
			a.SelfAdjointCandidates++
		}
		if item.FiniteSpectrum {
			a.FiniteSpectrumCandidates++
		}
		if item.GaloisInvariant {
			a.GaloisInvariantCandidates++
		}
		if item.BranchFree {
			a.BranchFreeCandidates++
		}
		if item.UsesObservedInput {
			a.ObservedInputsUsed = true
		}
		if item.UsesBranchChoice {
			a.BranchChoicesUsed++
		}
		if item.RepresentationCanonical {
			a.RepresentationCanonical++
		}
		if item.RealStructureCanonical {
			a.RealStructureCanonical++
		}
		if item.GradingCanonical {
			a.GradingCanonical++
		}
		if item.TotalHilbertCompatible {
			a.TotalHilbertCompatible++
		}
		if item.OrderOneTestable {
			a.OrderOneTestable++
		}
		if item.OrderOneVerified {
			a.OrderOneVerified++
		}
		if item.OrderOneVacuous {
			a.OrderOneVacuous++
		}
		if item.NontrivialCommutators {
			a.NontrivialCommutatorCandidates++
		}
		if item.NontrivialCommutators && item.OrderOneVerified {
			a.NontrivialOrderOneVerified++
		}
		if item.GaugeFluctuationNontrivial {
			a.GaugeFluctuationNontrivial++
		}
		if item.GaugeFluctuationTrivial {
			a.GaugeFluctuationTrivial++
		}
		if item.RequiresAlgebraRep {
			a.RequiresAlgebraRep++
		}
		if item.RequiresRealStructure {
			a.RequiresRealStructure++
		}
		if item.RequiresGrading {
			a.RequiresGrading++
		}
		if item.RequiresSectorMap {
			a.RequiresSectorMap++
		}
		if item.RequiresBranchBreaking {
			a.RequiresBranchBreaking++
		}
		if item.PromotableToFiniteDirac {
			a.PromotableFiniteDirac++
		}
		a.GaugeKineticMapRows += item.GaugeKineticMapRows
		a.BoundaryConstraintsDerived += item.BoundaryConstraintsDerived
		a.ThresholdBetaRows += item.ThresholdBetaRows
		if item.PhysicalConstantsDerived {
			a.PhysicalConstantsDerived = true
		}
	}
	return a
}

func FormatRepresentation(c RepresentationCandidate) string {
	return fmt.Sprintf("%s carrier=%s available=%t canonical=%t faithfulTotal=%t commutative=%t oneForms=%t gaugeTrivial=%t branch=%t observed=%t source=%s (%s)", c.Name, c.Carrier, c.Available, c.Canonical, c.FaithfulOnTotalHilbert, c.Commutative, c.GeneratesNonzeroOneForms, c.GaugeFluctuationTrivial, c.RequiresBranchChoice, c.UsesObservedInput, c.Source, c.Verdict)
}

func FormatRealStructure(c RealStructureCandidate) string {
	return fmt.Sprintf("%s carrier=%s available=%t carrierCanonical=%t totalCanonical=%t KO=%t C=%t quarticSplit=%t branch=%t observed=%t (%s)", c.Name, c.Carrier, c.Available, c.CanonicalOnCarrier, c.CanonicalOnTotalSpace, c.KOCompatibilityKnown, c.ChargeConjugationMap, c.RequiresQuarticSplit, c.UsesBranchChoice, c.UsesObservedInput, c.Verdict)
}

func FormatGrading(c GradingCandidate) string {
	return fmt.Sprintf("%s carrier=%s available=%t galois=%t nontrivial=%t carrierCanonical=%t totalCanonical=%t oddD=%t quarticSplit=%t branch=%t observed=%t (%s)", c.Name, c.Carrier, c.Available, c.GaloisInvariant, c.Nontrivial, c.CanonicalOnCarrier, c.CanonicalOnTotalSpace, c.OddDiracCompatible, c.RequiresQuarticSplit, c.UsesBranchChoice, c.UsesObservedInput, c.Verdict)
}

func FormatDirac(c DiracConstruction) string {
	return fmt.Sprintf("%s: %s carrier=%s exactQ=%t selfAdjoint=%t finite=%t galois=%t branchFree=%t observed=%t branch=%t rep=%t J=%t gamma=%t total=%t testable=%t order1=%t vacuous=%t nontrivComm=%t gaugeNontriv=%t gaugeTrivial=%t needs(rep=%t,J=%t,gamma=%t,map=%t,branch=%t) promotable=%t gaugeRows=%d constraints=%d beta=%d physical=%t (%s)", c.Name, c.Formula, c.Carrier, c.ExactOverQ, c.SelfAdjoint, c.FiniteSpectrum, c.GaloisInvariant, c.BranchFree, c.UsesObservedInput, c.UsesBranchChoice, c.RepresentationCanonical, c.RealStructureCanonical, c.GradingCanonical, c.TotalHilbertCompatible, c.OrderOneTestable, c.OrderOneVerified, c.OrderOneVacuous, c.NontrivialCommutators, c.GaugeFluctuationNontrivial, c.GaugeFluctuationTrivial, c.RequiresAlgebraRep, c.RequiresRealStructure, c.RequiresGrading, c.RequiresSectorMap, c.RequiresBranchBreaking, c.PromotableToFiniteDirac, c.GaugeKineticMapRows, c.BoundaryConstraintsDerived, c.ThresholdBetaRows, c.PhysicalConstantsDerived, c.Verdict)
}

func FormatRepresentationAudit(a RepresentationAudit) string {
	return fmt.Sprintf("candidates=%d available=%d canonical=%d faithfulTotal=%d commutative=%d nonzeroOneForms=%d gaugeTrivial=%d branchChoices=%d observed=%t (%s)", a.CandidatesAudited, a.AvailableCandidates, a.CanonicalCandidates, a.FaithfulTotalRepresentations, a.CommutativeCandidates, a.NonzeroOneFormCandidates, a.GaugeTrivialCandidates, a.BranchChoicesUsed, a.ObservedInputsUsed, a.Verdict)
}

func FormatRealStructureAudit(a RealStructureAudit) string {
	return fmt.Sprintf("candidates=%d available=%d carrierCanonical=%d totalCanonical=%d KO=%d C=%d quarticSplit=%d branchChoices=%d observed=%t (%s)", a.CandidatesAudited, a.AvailableCandidates, a.CanonicalCarrierCandidates, a.CanonicalTotalCandidates, a.KOCompatibleCandidates, a.ChargeConjugationCandidates, a.QuarticSplitRequired, a.BranchChoicesUsed, a.ObservedInputsUsed, a.Verdict)
}

func FormatGradingAudit(a GradingAudit) string {
	return fmt.Sprintf("candidates=%d available=%d galois=%d nontrivial=%d carrierCanonical=%d totalCanonical=%d oddD=%d quarticSplit=%d branchChoices=%d observed=%t (%s)", a.CandidatesAudited, a.AvailableCandidates, a.GaloisInvariantCandidates, a.NontrivialCandidates, a.CanonicalCarrierCandidates, a.CanonicalTotalCandidates, a.OddDiracCompatible, a.QuarticSplitRequired, a.BranchChoicesUsed, a.ObservedInputsUsed, a.Verdict)
}

func FormatOrderOneAudit(a OrderOneAudit) string {
	return fmt.Sprintf("D=%d exact=%d selfAdjoint=%d finite=%d galois=%d branchFree=%d observed=%t branchChoices=%d rep=%d J=%d gamma=%d total=%d testable=%d order1=%d vacuous=%d nontriv=%d nontrivOrder1=%d gaugeNontriv=%d gaugeTrivial=%d needs(rep=%d,J=%d,gamma=%d,map=%d,branch=%d) promotable=%d gaugeRows=%d constraints=%d beta=%d physical=%t (%s)", a.DiracCandidatesAudited, a.ExactCandidates, a.SelfAdjointCandidates, a.FiniteSpectrumCandidates, a.GaloisInvariantCandidates, a.BranchFreeCandidates, a.ObservedInputsUsed, a.BranchChoicesUsed, a.RepresentationCanonical, a.RealStructureCanonical, a.GradingCanonical, a.TotalHilbertCompatible, a.OrderOneTestable, a.OrderOneVerified, a.OrderOneVacuous, a.NontrivialCommutatorCandidates, a.NontrivialOrderOneVerified, a.GaugeFluctuationNontrivial, a.GaugeFluctuationTrivial, a.RequiresAlgebraRep, a.RequiresRealStructure, a.RequiresGrading, a.RequiresSectorMap, a.RequiresBranchBreaking, a.PromotableFiniteDirac, a.GaugeKineticMapRows, a.BoundaryConstraintsDerived, a.ThresholdBetaRows, a.PhysicalConstantsDerived, a.Verdict)
}

func FormatFirewall(f FirewallAudit) string {
	return fmt.Sprintf("gate163=%t preData=%t contactVacuous=%d nontrivOrder1=%d promotableD=%d triple=%t D=%t J=%t gamma=%t order1=%t gauge=%t gaugeRows=%d individualQuartic=%d branches=%d gaugeRep=%d local=%d mass=%d decoupling=%d dynkin=%d beta=%d zero=%d constraints=%d physical=%t closed=%t (%s)", f.Gate163Inherited, f.FiniteSpectralPreData, f.ContactOnlyOrderOneVacuous, f.NontrivialOrderOneVerified, f.PromotableFiniteDirac, f.SpectralTripleComplete, f.FiniteDiracSelected, f.RealStructureSelected, f.GradingSelected, f.OrderOneCalculusVerified, f.GaugeFluctuationMapDerived, f.GaugeKineticMapRows, f.IndividualQuarticRows, f.CanonicalQuarticBranches, f.GaugeRepresentationRows, f.LocalFieldRows, f.MassActivationRows, f.DecouplingRows, f.DynkinIndexRows, f.ThresholdBetaRows, f.ProvenZeroRows, f.BoundaryConstraintsDerived, f.PhysicalConstantsDerived, f.BetaPermissionFirewallClosed, f.Verdict)
}

func FormatSummary(s Summary) string {
	return fmt.Sprintf("contactRows=%d zeta=%d reps=%d canonicalReps=%d faithfulTotal=%d J=%d totalJ=%d gamma=%d totalGamma=%d D=%d order1=%d vacuous=%d nontrivOrder1=%d promotableD=%d gaugeRows=%d constraints=%d beta=%d nullity=%d→%d", s.ContactRows, s.ZetaValuesComputed, s.RepresentationCandidatesAudited, s.CanonicalRepresentations, s.FaithfulTotalRepresentations, s.RealStructuresAudited, s.CanonicalTotalRealStructures, s.GradingsAudited, s.CanonicalTotalGradings, s.DiracCandidatesAudited, s.OrderOneVerified, s.OrderOneVacuous, s.NontrivialOrderOneVerified, s.PromotableFiniteDirac, s.GaugeKineticMapRows, s.BoundaryConstraintsDerived, s.ThresholdBetaRows, s.ResidualNullityBefore, s.ResidualNullityAfter)
}

func FormatDiracList(items []DiracConstruction) string {
	parts := make([]string, 0, len(items))
	for _, item := range items {
		parts = append(parts, fmt.Sprintf("%s(order1=%t,vacuous=%t,promotable=%t)", item.Name, item.OrderOneVerified, item.OrderOneVacuous, item.PromotableToFiniteDirac))
	}
	sort.Strings(parts)
	return strings.Join(parts, "; ")
}
