package diracorderone

import (
	"fmt"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func FiniteDiracCandidateOrderOneAxiomObstructionAuditTheorem() theorem.Theorem {
	const id = "BRIDGE-FINITE-DIRAC-ORDER-ONE-OBSTRUCTION-AUDIT"
	const name = "Finite Dirac candidate construction / order-one axiom obstruction audit"
	return theorem.Theorem{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build finite Dirac order-one audit", Passed: false, Detail: err.Error()}}}
		}
		return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: []theorem.Check{
			{Name: "Gate 163 spectral-action firewall is inherited", Passed: a.Previous.FiniteSpectralPreData && !a.Previous.SpectralTripleComplete && !a.Previous.FiniteDiracSelected && !a.Previous.RealStructureSelected && !a.Previous.GradingSelected && !a.Previous.OrderOneCalculusVerified && !a.Previous.GaugeFluctuationMapDerived && a.Previous.GaugeKineticMapRows == 0 && a.Previous.ThresholdBetaRows == 0 && a.Previous.ResidualNullityAfter == 3 && !a.Previous.HiddenObservedInputUsed, Detail: fmt.Sprintf("preData=%t triple=%t D=%t J=%t gamma=%t order1=%t gauge=%t gaugeRows=%d beta=%d nullity=%d hiddenObserved=%t", a.Previous.FiniteSpectralPreData, a.Previous.SpectralTripleComplete, a.Previous.FiniteDiracSelected, a.Previous.RealStructureSelected, a.Previous.GradingSelected, a.Previous.OrderOneCalculusVerified, a.Previous.GaugeFluctuationMapDerived, a.Previous.GaugeKineticMapRows, a.Previous.ThresholdBetaRows, a.Previous.ResidualNullityAfter, a.Previous.HiddenObservedInputUsed)},
			{Name: "representation audit finds no faithful total spectral representation", Passed: a.RepresentationAudit.CandidatesAudited == 5 && a.RepresentationAudit.AvailableCandidates == 4 && a.RepresentationAudit.CanonicalCandidates == 2 && a.RepresentationAudit.FaithfulTotalRepresentations == 0 && a.RepresentationAudit.NonzeroOneFormCandidates == 0 && a.RepresentationAudit.GaugeTrivialCandidates == 5 && a.RepresentationAudit.BranchChoicesUsed == 0 && !a.RepresentationAudit.ObservedInputsUsed, Detail: FormatRepresentationAudit(a.RepresentationAudit)},
			{Name: "real-structure audit finds no global KO-compatible J", Passed: a.RealStructureAudit.CandidatesAudited == 4 && a.RealStructureAudit.AvailableCandidates == 2 && a.RealStructureAudit.CanonicalCarrierCandidates == 1 && a.RealStructureAudit.CanonicalTotalCandidates == 0 && a.RealStructureAudit.KOCompatibleCandidates == 0 && a.RealStructureAudit.QuarticSplitRequired == 1 && a.RealStructureAudit.BranchChoicesUsed == 1 && !a.RealStructureAudit.ObservedInputsUsed, Detail: FormatRealStructureAudit(a.RealStructureAudit)},
			{Name: "grading audit finds no global nontrivial Galois-safe gamma", Passed: a.GradingAudit.CandidatesAudited == 5 && a.GradingAudit.AvailableCandidates == 3 && a.GradingAudit.GaloisInvariantCandidates == 3 && a.GradingAudit.NontrivialCandidates == 3 && a.GradingAudit.CanonicalCarrierCandidates == 2 && a.GradingAudit.CanonicalTotalCandidates == 0 && a.GradingAudit.OddDiracCompatible == 0 && a.GradingAudit.QuarticSplitRequired == 1 && a.GradingAudit.BranchChoicesUsed == 1 && !a.GradingAudit.ObservedInputsUsed, Detail: FormatGradingAudit(a.GradingAudit)},
			{Name: "contact-only Dirac candidates satisfy order-one only vacuously", Passed: a.OrderOneAudit.DiracCandidatesAudited == 7 && a.OrderOneAudit.OrderOneTestable == 4 && a.OrderOneAudit.OrderOneVerified == 4 && a.OrderOneAudit.OrderOneVacuous == 5 && a.OrderOneAudit.NontrivialCommutatorCandidates == 2 && a.OrderOneAudit.NontrivialOrderOneVerified == 0 && a.OrderOneAudit.GaugeFluctuationNontrivial == 0 && a.OrderOneAudit.GaugeFluctuationTrivial == 7, Detail: FormatOrderOneAudit(a.OrderOneAudit) + " :: " + FormatDiracList(a.DiracCandidates)},
			{Name: "no finite Dirac operator is promotable", Passed: a.OrderOneAudit.PromotableFiniteDirac == 0 && a.OrderOneAudit.GaugeKineticMapRows == 0 && a.OrderOneAudit.BoundaryConstraintsDerived == 0 && a.OrderOneAudit.ThresholdBetaRows == 0 && !a.OrderOneAudit.PhysicalConstantsDerived && !a.OrderOneAudit.ObservedInputsUsed, Detail: FormatOrderOneAudit(a.OrderOneAudit)},
			{Name: "order-one firewall preserves beta and constants", Passed: a.Firewall.Gate163Inherited && a.Firewall.FiniteSpectralPreData && a.Firewall.ContactOnlyOrderOneVacuous == 5 && a.Firewall.NontrivialOrderOneVerified == 0 && a.Firewall.PromotableFiniteDirac == 0 && !a.Firewall.SpectralTripleComplete && !a.Firewall.FiniteDiracSelected && !a.Firewall.RealStructureSelected && !a.Firewall.GradingSelected && !a.Firewall.OrderOneCalculusVerified && !a.Firewall.GaugeFluctuationMapDerived && a.Firewall.GaugeKineticMapRows == 0 && a.Firewall.IndividualQuarticRows == 0 && a.Firewall.CanonicalQuarticBranches == 0 && a.Firewall.GaugeRepresentationRows == 0 && a.Firewall.LocalFieldRows == 0 && a.Firewall.MassActivationRows == 0 && a.Firewall.DecouplingRows == 0 && a.Firewall.DynkinIndexRows == 0 && a.Firewall.ThresholdBetaRows == 0 && a.Firewall.ProvenZeroRows == 0 && a.Firewall.BoundaryConstraintsDerived == 0 && !a.Firewall.PhysicalConstantsDerived && a.Firewall.BetaPermissionFirewallClosed, Detail: FormatFirewall(a.Firewall)},
			{Name: "physical bridge remains sealed with nullity unchanged", Passed: a.ContactRows == 7 && a.ContactZetaValues == 5 && a.FiniteSpectralPreData && !a.SpectralTripleComplete && !a.SpectralActionPrincipleReady && !a.FiniteDiracSelected && !a.RealStructureSelected && !a.GradingSelected && !a.OrderOneCalculusVerified && !a.OrientabilityVerified && !a.PoincareDualityVerified && !a.KOCompatibilityVerified && !a.CanonicalCutoffSelected && !a.GaugeFluctuationMapDerived && a.GaugeKineticMapRows == 0 && a.IndividualQuarticRows == 0 && a.CanonicalQuarticBranches == 0 && a.GaugeRepresentationRows == 0 && a.SpinStatisticsRows == 0 && a.LocalFieldRows == 0 && a.MassActivationRows == 0 && a.DecouplingRows == 0 && a.DynkinIndexRows == 0 && a.ThresholdBetaRows == 0 && a.ProvenZeroRows == 0 && a.BoundaryConstraintsDerived == 0 && a.ContactBetaRowsAllowed == 0 && a.ContactZeroRowsProved == 0 && a.BetaPermissionFirewallClosed && a.ResidualNullityBefore == 3 && a.ResidualNullityAfter == 3 && !a.ThresholdCorrectedBeta && !a.FullBetaMatchingTensor && !a.HiddenObservedInputUsed && !a.PhysicalWeakAngleDerived && !a.FineStructureDerived && !a.PhysicalMassesDerived && !a.PhysicalScaleDerived, Detail: FormatSummary(a.Summary) + " :: " + a.TruthStatement},
		}}
	}}
}
