package generation2twistorinvariantsu2socketandmovingu1phaseaudit

import (
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2TwistorInvariantSU2SocketAndMovingU1PhaseAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 714 — Twistor-Invariant SU(2) Socket and Moving U(1) Phase Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 714 — Twistor-Invariant SU(2) Socket and Moving U(1) Phase Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate713 twistor socket bundle", Passed: a.Inherited.TwistorSocketBundleInherited && a.Inherited.K7PlusDimension == k7PlusDimension && a.Inherited.K7MinusDimension == k7MinusDimension && a.Inherited.TwistorSphereDimension == twistorSphereDim && a.Inherited.FamilyValuedSocketBundle && !a.Inherited.SingleSocketPromoted && !a.Inherited.NativeTwistorPointSelector && !a.Inherited.PhysicalElectroweakBundle && !a.Inherited.HyperchargeAssignment && !a.Inherited.YukawaOperatorCertified && !a.Inherited.HiggsMassCertified && a.Inherited.Verdict == StatusGate713TwistorSocketBundleInherited, Detail: FormatInherited(a.Inherited)},
			{Name: "define common commutant", Passed: strings.Contains(a.CommonCommutant.Definition, "Comm") && a.CommonCommutant.Dimension == commutantDimension && a.CommonCommutant.IncludedInAllSockets && strings.Contains(a.CommonCommutant.InclusionArgument, "[X,J_H(n)]") && a.CommonCommutant.SelectorIndependent && !a.CommonCommutant.PhysicalSU2LCertified && strings.Contains(a.CommonCommutant.Verdict, StatusCommonCommutantDefined) && strings.Contains(a.CommonCommutant.Verdict, StatusCommonCommutantIncludedInAllU2Sockets) && strings.Contains(a.CommonCommutant.Verdict, StatusCommonCommutantTwistorInvariantSU2Candidate), Detail: FormatCommon(a.CommonCommutant)},
			{Name: "audit twistor intersection", Passed: strings.Contains(a.Intersection.Definition, "intersection") && a.Intersection.EqualsCommonCommutant && a.Intersection.Dimension == commutantDimension && a.Intersection.ProofUsesBasisDirections && !a.Intersection.ContainsMovingPhaseLine && strings.Contains(a.Intersection.Verdict, StatusTwistorIntersectionEqualsCommonCommutant) && strings.Contains(a.Intersection.Verdict, StatusNoSelectorIndependentU1PhaseLine), Detail: FormatIntersection(a.Intersection)},
			{Name: "audit moving U1 phase line", Passed: strings.Contains(a.PhaseLine.Definition, "span{J_H") && a.PhaseLine.Dimension == phaseLineDimension && a.PhaseLine.MovesWithSelectorN && !a.PhaseLine.CommonToAllSockets && !a.PhaseLine.SelectorIndependentLine && !a.PhaseLine.NativePointSelected && !a.PhaseLine.HyperchargeCertified && strings.Contains(a.PhaseLine.Verdict, StatusMovingPhaseLineAudited) && strings.Contains(a.PhaseLine.Verdict, StatusU1PhaseLineSelectorDependent) && strings.Contains(a.PhaseLine.Verdict, StatusNoSelectorIndependentU1PhaseLine), Detail: FormatPhase(a.PhaseLine)},
			{Name: "audit commutant Lie algebra", Passed: strings.Contains(a.LieAlgebra.AlgebraName, "Comm") && a.LieAlgebra.Dimension == commutantDimension && a.LieAlgebra.ClosesAsSU2Like && strings.Contains(a.LieAlgebra.Commutator, "epsilon") && a.LieAlgebra.NormalizationRequired && !a.LieAlgebra.PhysicalSU2LCertified && strings.Contains(a.LieAlgebra.Verdict, StatusLieAlgebraStructureOfCommutantAudited) && strings.Contains(a.LieAlgebra.Verdict, StatusCommonCommutantTwistorInvariantSU2Candidate), Detail: FormatLie(a.LieAlgebra)},
			{Name: "separate selector-dependent and independent socket parts", Passed: a.Separation.IndependentCount == 3 && a.Separation.DependentCount == 3 && strings.Contains(a.Separation.AirlockSplit, "SU2") && strings.Contains(a.Separation.AirlockSplit, "U1") && a.Separation.SeparationValid && strings.Contains(strings.Join(a.Separation.SelectorIndependent, ";"), "commutant") && strings.Contains(strings.Join(a.Separation.SelectorDependent, ";"), "phase line") && strings.Contains(a.Separation.Verdict, StatusSelectorDependentAndIndependentPartsSeparated) && strings.Contains(a.Separation.Verdict, StatusElectroweakAirlockSplits), Detail: FormatSeparation(a.Separation)},
			{Name: "enforce physical electroweak firewall", Passed: !a.PhysicalFirewall.InternalCommutantPhysicalSU2L && !a.PhysicalFirewall.MovingPhasePhysicalU1Y && !a.PhysicalFirewall.HyperchargeNormalization && !a.PhysicalFirewall.TypedHiggsDoubletMap && !a.PhysicalFirewall.YukawaOperator && !a.PhysicalFirewall.YukawaEigenvalues && !a.PhysicalFirewall.HiggsMass && !a.PhysicalFirewall.ScalarRuntime && len(a.PhysicalFirewall.MissingMaps) == 4 && strings.Contains(a.PhysicalFirewall.Verdict, StatusPhysicalElectroweakFirewallEnforced) && strings.Contains(a.PhysicalFirewall.Verdict, StatusInternalCommutantNotPhysicalSU2L) && strings.Contains(a.PhysicalFirewall.Verdict, StatusNoHyperchargeAssignmentOrNormalization) && strings.Contains(a.PhysicalFirewall.Verdict, StatusNoYukawaOperatorOrEigenvalueTheorem), Detail: FormatPhysical(a.PhysicalFirewall)},
			{Name: "record strategic electroweak split", Passed: strings.Contains(a.Strategy.SU2Problem, "SU(2)_L") && strings.Contains(a.Strategy.U1Problem, "phase line") && strings.Contains(a.Strategy.HiggsProblem, "Higgs doublet") && strings.Contains(a.Strategy.SelectorProblem, "n_*") && strings.Contains(a.Strategy.Verdict, StatusElectroweakAirlockSplits), Detail: FormatStrategy(a.Strategy)},
			{Name: "classify source types", Passed: strings.Contains(a.SourceTypes.CommonCommutantRole, "selector-independent") && strings.Contains(a.SourceTypes.PhaseLineRole, "selector-dependent") && strings.Contains(a.SourceTypes.TwistorRole, "intersection") && strings.Contains(a.SourceTypes.ElectroweakRole, "missing") && strings.Contains(a.SourceTypes.HyperchargeRole, "missing") && strings.Contains(a.SourceTypes.FirewallRole, "no Higgs") && strings.Contains(a.SourceTypes.Verdict, StatusGate714TwistorInvariantSU2SocketBoundary), Detail: FormatSourceTypes(a.SourceTypes)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 714 — Twistor-Invariant SU(2) Socket and Moving U(1) Phase Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
