package generation2firsttracefunctionalselectionandspectralorderaudit

import (
	"math"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2FirstTraceFunctionalSelectionAndSpectralOrderAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 689 — First-Trace Functional Selection and Spectral-Order Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 689 — First-Trace Functional Selection and Spectral-Order Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate688 response-operator spectrum", Passed: a.Inherited.ResponseOperatorSpectrumInherited && a.Inherited.Operator == "R_split = S_split P_K7" && strings.Contains(a.Inherited.TracePowerFormula, "Tr(R_split^n)=7 S_split^n") && math.Abs(a.Inherited.SSplit-auditedSSplit) < residualTolerance && math.Abs(a.Inherited.DBase-auditedDBase) < residualTolerance && a.Inherited.H72Dimension == h72Dimension && a.Inherited.K7Dimension == k7Dimension && a.Inherited.K7PlusDimension == k7PlusDimension && a.Inherited.K7MinusDimension == k7MinusDimension && !a.Inherited.PriorSpectrumTraceSelectsK7 && a.Inherited.PriorSupportSelectsK7 && !a.Inherited.PriorNativeFirstTracePrinciple && a.Inherited.Verdict == StatusGate688ResponseOperatorSpectrumInherited, Detail: FormatInheritance(a.Inherited)},
			{Name: "define spectral functional candidates", Passed: a.Functionals.CandidateCount == 6 && len(a.Functionals.Candidates) == 6 && math.Abs(a.Functionals.FirstOrdinaryTrace-(float64(k7Dimension)/float64(h72Dimension))*auditedSSplit) < residualTolerance && math.Abs(a.Functionals.QuadraticTrace-(float64(k7Dimension)/float64(h72Dimension))*auditedSSplit*auditedSSplit) < residualTolerance && math.Abs(a.Functionals.FrobeniusNorm-a.Functionals.QuadraticTrace) < residualTolerance && math.Abs(a.Functionals.HodgeSignedTrace-(float64(1)/float64(h72Dimension))*auditedSSplit) < residualTolerance && math.Abs(a.Functionals.FullIdentityTrace-auditedSSplit) < residualTolerance && a.Functionals.FirstTraceMatchesBest && a.Functionals.OnlyFirstTraceActive && strings.Contains(a.Functionals.Verdict, StatusSpectralFunctionalCandidatesDefined), Detail: FormatFunctionals(a.Functionals)},
			{Name: "compute first trace response", Passed: math.Abs(a.Functionals.FirstOrdinaryTrace-0.0001256543573849177) < residualTolerance && math.Abs(a.Residuals.FirstTraceResidual-firstTraceResidual) < residualTolerance && strings.Contains(a.Functionals.Verdict, StatusFirstTraceResponseComputed), Detail: FormatFunctionals(a.Functionals)},
			{Name: "compute higher trace and Frobenius responses", Passed: math.Abs(a.Functionals.QuadraticTrace-1.624013231638281e-7) < 1e-21 && math.Abs(a.Functionals.FrobeniusNorm-a.Functionals.QuadraticTrace) < residualTolerance && a.Residuals.QuadraticTooSmall && a.Residuals.FrobeniusTooSmall && strings.Contains(a.Functionals.Verdict, StatusHigherTraceResponsesComputed) && strings.Contains(a.Residuals.Verdict, StatusQuadraticTraceOrFrobeniusNotActive), Detail: FormatResiduals(a.Residuals)},
			{Name: "compute Hodge-signed and full identity traces", Passed: math.Abs(a.Functionals.HodgeSignedTrace-1.795062248355967e-5) < residualTolerance && math.Abs(a.Functionals.FullIdentityTrace-auditedSSplit) < residualTolerance && a.Residuals.HodgeSignedTooSmall && a.Residuals.FullIdentityTooLarge && strings.Contains(a.TraceType.Verdict, StatusHodgeSignedTraceComputed) && strings.Contains(a.Residuals.Verdict, StatusFullIdentityTraceNotActive), Detail: FormatTraceType(a.TraceType)},
			{Name: "audit residual comparison", Passed: a.Residuals.BestCandidate == "F_1 = Tr(R_split)/72" && math.Abs(a.Residuals.BestResidual-math.Abs(firstTraceResidual)) < residualTolerance && math.Abs(a.Residuals.QuadraticResidual-(auditedDBase-a.Functionals.QuadraticTrace)) < residualTolerance && math.Abs(a.Residuals.FrobeniusResidual-a.Residuals.QuadraticResidual) < residualTolerance && len(a.Residuals.ResidualRanking) == 4 && strings.Contains(a.Residuals.Verdict, StatusResidualComparisonAudited), Detail: FormatResiduals(a.Residuals)},
			{Name: "audit linear spectral order match", Passed: a.Order.DBaseLinearInWallCoords && a.Order.SSplitLinearInWallCoords && a.Order.FirstTraceOrder == 1 && a.Order.QuadraticTraceOrder == 2 && a.Order.CubicTraceOrder == 3 && a.Order.RequiredFunctionalOrder == 1 && a.Order.HigherPowersAreInactive && strings.Contains(a.Order.Verdict, StatusLinearOrderMatchAudited) && strings.Contains(a.Order.Verdict, StatusDBaseIsLinearWallResponseCoordinate), Detail: FormatOrder(a.Order)},
			{Name: "audit trace type: ordinary total support not signed polarity", Passed: a.TraceType.K7PlusDimension == 4 && a.TraceType.K7MinusDimension == 3 && a.TraceType.OrdinaryMultiplicity == 7 && a.TraceType.HodgeSignedMultiplicity == 1 && math.Abs(a.TraceType.OrdinaryTraceCoefficient-float64(7)/float64(72)) < residualTolerance && math.Abs(a.TraceType.HodgeSignedCoefficient-float64(1)/float64(72)) < residualTolerance && a.TraceType.ActiveUsesTotalSupport && !a.TraceType.ActiveUsesSignedPolarity && strings.Contains(a.TraceType.Verdict, StatusHodgeSignedTraceNotActive), Detail: FormatTraceType(a.TraceType)},
			{Name: "record comparative selection without native first-trace theorem", Passed: a.Selection.SelectedFunctional == "F_1=Tr(R_split)/72=(7/72)S_split" && a.Selection.SelectionIsComparative && !a.Selection.NativeFirstTraceProved && !a.Selection.NativeSevenOver72Proved && len(a.Selection.RejectedFunctionals) == 4 && strings.Contains(a.Selection.Verdict, StatusActiveBridgeSelectsFirstOrdinaryTrace) && strings.Contains(a.Selection.Verdict, StatusNoNativeFirstTraceResponseTheorem), Detail: FormatSelection(a.Selection)},
			{Name: "record missing HistoryResponseFirstTraceTheorem", Passed: len(a.Missing.Missing) == 2 && strings.Contains(a.Missing.PreciseGap, "HistoryResponseFirstTraceTheorem") && strings.Contains(a.Missing.Verdict, StatusNoNativeFirstTraceResponseTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeSevenOver72Theorem), Detail: FormatMissing(a.Missing)},
			{Name: "preserve first-trace selection firewall", Passed: !a.Discipline.ClaimsNativeFirstTraceTheorem && !a.Discipline.ClaimsNativeSevenOver72 && !a.Discipline.ClaimsBoundaryStress && !a.Discipline.ClaimsScalarRGMatching && !a.Discipline.ClaimsHiggsMass && !a.Discipline.ClaimsGaugeUnification && !a.Discipline.ClaimsFlavorDerivation && !a.Discipline.ClaimsCKMPMNS && !a.Discipline.ClaimsProjectorActivation && !a.Discipline.ClaimsK7IdentityFromTrace && a.Discipline.Verdict == StatusGate689FirstTraceSelectionBoundary, Detail: FormatDiscipline(a.Discipline)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 689 — First-Trace Functional Selection and Spectral-Order Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
