package generation2centralscalarbaselineandupliftonlyresponseisolationaudit

import (
	"math"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2CentralScalarBaselineAndUpliftOnlyResponseIsolationAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 706 — Central Scalar Baseline and Uplift-Only Response Isolation Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 706 — Central Scalar Baseline and Uplift-Only Response Isolation Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate705 scalar-baseline/K7-uplift audit", Passed: a.Inherited.ScalarBaselineK7UpliftInherited && a.Inherited.TwoPayoffRewritten && a.Inherited.KSumScalarBaselineUplift && a.Inherited.K7SplitUpliftNotPrimitiveGauge && a.Inherited.ScalarWallAirlockBaseline && math.Abs(a.Inherited.TotalExpectation-0.0498265964350682) < 5e-16 && math.Abs(a.Inherited.Residual-8.5258344e-10) < 1e-16 && a.Inherited.NoNativeScalarBaseline && a.Inherited.NoNativeK7Uplift && a.Inherited.NoNativeUpliftTheorem && a.Inherited.NoNativeHistoryResponse && a.Inherited.NoNativeSevenOver72 && a.Inherited.Verdict == StatusGate705ScalarBaselineK7UpliftInherited, Detail: FormatInheritance(a.Inherited)},
			{Name: "define central baseline operator", Passed: strings.Contains(a.CentralBaseline.Operator, "|lambda|I_H72") && math.Abs(a.CentralBaseline.ScalarBaseline-math.Abs(lambdaLambda12)) < tolerance && a.CentralBaseline.CommutesWithPK7 && a.CentralBaseline.CommutesWithPB && a.CentralBaseline.CommutesWithPG && a.CentralBaseline.CommutesWithPPerp && a.CentralBaseline.ProjectorBlind && a.CentralBaseline.IdentityShift && strings.Contains(a.CentralBaseline.Verdict, StatusCentralBaselineOperatorDefined) && strings.Contains(a.CentralBaseline.Verdict, StatusScalarBaselineCentralIdentityShift), Detail: FormatCentralBaseline(a.CentralBaseline)},
			{Name: "baseline expectation observer-independent", Passed: strings.Contains(a.BaselineExpect.Formula, "Tr(rho)") && math.Abs(a.BaselineExpect.Rho72Expectation-math.Abs(lambdaLambda12)) < tolerance && math.Abs(a.BaselineExpect.FiniteStateExpectation-math.Abs(lambdaLambda12)) < tolerance && math.Abs(a.BaselineExpect.KernelStateExpectation-math.Abs(lambdaLambda12)) < tolerance && math.Abs(a.BaselineExpect.LocalK7StateExpectation-math.Abs(lambdaLambda12)) < tolerance && a.BaselineExpect.ObserverIndependent && a.BaselineExpect.Verdict == StatusBaselineExpectationObserverIndependent, Detail: FormatBaselineExpectation(a.BaselineExpect)},
			{Name: "isolate uplift-only response", Passed: strings.Contains(a.Uplift.PositiveObservable, "W_boundary") && strings.Contains(a.Uplift.SubtractedObservable, "W_boundary-|lambda|I_H72") && strings.Contains(a.Uplift.UpliftOperator, "S_split P_K7") && math.Abs(a.Uplift.BoundarySplit-(lambdaLambda12+r3Minus1)) < tolerance && math.Abs(a.Uplift.DBase-(kappaLambda+kappaE+lambdaLambda12)) < tolerance && math.Abs(a.Uplift.KSumMinusScalarBaseline-a.Uplift.DBase) < tolerance && math.Abs(a.Uplift.UpliftExpectationRho72-pK7*(lambdaLambda12+r3Minus1)) < tolerance && math.Abs(a.Uplift.Residual-8.5258344e-10) < 1e-16 && a.Uplift.IsolatesGate700Law && strings.Contains(a.Uplift.Verdict, StatusUpliftOperatorIsolated) && strings.Contains(a.Uplift.Verdict, StatusDBaseBaselineSubtractedHistoryDefect), Detail: FormatUplift(a.Uplift)},
			{Name: "observer dependence localized to uplift", Passed: a.Observer.BaselineIndependent && strings.Contains(a.Observer.UpliftFormula, "Tr(rho P_K7)") && math.Abs(a.Observer.Rho72UpliftExpectation-pK7*a.Uplift.BoundarySplit) < tolerance && math.Abs(a.Observer.FiniteUpliftExpectation-pK7Finite*a.Uplift.BoundarySplit) < tolerance && math.Abs(a.Observer.KernelUpliftExpectation-pK7Kernel*a.Uplift.BoundarySplit) < tolerance && math.Abs(a.Observer.LocalK7UpliftExpectation-a.Uplift.BoundarySplit) < tolerance && a.Observer.OnlyUpliftRequiresRho72 && a.Observer.Verdict == StatusObserverDependenceLocalizedToUplift, Detail: FormatObserver(a.Observer)},
			{Name: "support dependence localized to uplift", Passed: !a.Support.BaselineSelectsPK7 && !a.Support.BaselineSelectsRho72 && a.Support.UpliftProjectorSensitive && a.Support.UpliftSupportSelected && strings.Contains(a.Support.SelectorStatement, "P_B P=P") && strings.Contains(a.Support.SelectorStatement, "P_G P=P") && a.Support.K7IdentityRequiresSupport && strings.Contains(a.Support.Verdict, StatusSupportDependenceLocalizedToUplift) && strings.Contains(a.Support.Verdict, StatusBaselineDoesNotSelectK7OrRho72), Detail: FormatSupport(a.Support)},
			{Name: "audit relation to previous gates", Passed: strings.Contains(a.Relation.Gate705PositiveDistanceLaw, "K_sum") && strings.Contains(a.Relation.Gate706SubtractedLaw, "D_base") && math.Abs(a.Relation.KSum-(kappaLambda+kappaE)) < tolerance && math.Abs(a.Relation.DBase-(kappaLambda+kappaE+lambdaLambda12)) < tolerance && math.Abs(a.Relation.ScalarBaseline-math.Abs(lambdaLambda12)) < tolerance && math.Abs(a.Relation.ExpectedWound-0.0498265964350682) < 5e-16 && math.Abs(a.Relation.ExpectedUplift-pK7*(lambdaLambda12+r3Minus1)) < tolerance && a.Relation.NoNewNumericalRelation && a.Relation.Verdict == StatusRelationToPreviousGatesAudited, Detail: FormatRelation(a.Relation)},
			{Name: "classify source types", Passed: strings.Contains(a.SourceTypes.ScalarBaselineRole, "universal") && strings.Contains(a.SourceTypes.UpliftRole, "K7-localized") && strings.Contains(a.SourceTypes.ObserverRole, "uplift event probability") && strings.Contains(a.SourceTypes.KSumRole, "total expected wound") && strings.Contains(a.SourceTypes.DBaseRole, "baseline subtraction"), Detail: FormatSourceTypes(a.SourceTypes)},
			{Name: "preserve missing theorem boundary", Passed: len(a.Missing.Missing) == 6 && strings.Contains(a.Missing.Verdict, StatusBaselineDoesNotSelectK7OrRho72) && strings.Contains(a.Missing.Verdict, StatusNoNativeScalarWoundFullChamberBaseline) && strings.Contains(a.Missing.Verdict, StatusNoNativeK7ReceivesSplitUplift) && strings.Contains(a.Missing.Verdict, StatusNoNativeBoundaryWoundUpliftTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeHistoryResponseTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeSevenOver72Theorem), Detail: FormatMissing(a.Missing)},
			{Name: "preserve Gate706 central-baseline/uplift isolation firewall", Passed: !a.Firewall.ClaimsBaselineSelectsK7OrRho72 && !a.Firewall.ClaimsScalarWoundFullChamberBaselineNative && !a.Firewall.ClaimsK7ReceivesSplitUpliftNative && !a.Firewall.ClaimsNativeBoundaryWoundUpliftTheorem && !a.Firewall.ClaimsNativeHistoryResponseTheorem && !a.Firewall.ClaimsNativeSevenOver72Theorem && !a.Firewall.ClaimsBoundaryStressDerived && !a.Firewall.ClaimsScalarRGMatching && !a.Firewall.ClaimsHiggsMass && !a.Firewall.ClaimsGaugeUnification && !a.Firewall.ClaimsFlavorDerivation && !a.Firewall.ClaimsCKMPMNS && a.Firewall.Verdict == StatusGate706CentralBaselineUpliftBoundary, Detail: FormatFirewall(a.Firewall)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 706 — Central Scalar Baseline and Uplift-Only Response Isolation Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
