// Package boundary computes the finite Lie algebra forced by imposing the
// contact boundary after Boolean compression. Gate 8 answered the harsh
// yes/no question: the four naively compressed g₂ᴿ generators do not close.
// This package asks the deeper question: what is the smallest skew,
// boundary-fixed Lie algebra generated by those compressed operators?
package boundary

import (
	"sync"

	"fmt"
	"math"

	"github.com/bagherbal/asha-engine/pkg/gauge/lift"
	"github.com/bagherbal/asha-engine/pkg/linear"
)

type Closure struct {
	Compression lift.Compression

	SeedDimension    int
	ClosureDimension int
	DerivedDimension int
	CenterDimension  int

	Basis        []linear.Matrix
	DerivedBasis []linear.Matrix

	MaxSkewResidual            float64
	MaxBoundaryLeakage         float64
	MaxClosureResidual         float64
	MaxClosureRelativeResidual float64

	Iterations    int
	CutoffReached bool
	MaxDimension  int
}

var (
	boundaryDefaultOnce  sync.Once
	boundaryDefaultValue Closure
	boundaryDefaultErr   error
)

func BuildDefault() (Closure, error) {
	boundaryDefaultOnce.Do(func() {
		boundaryDefaultValue, boundaryDefaultErr = buildBoundaryDefaultUncached()
	})
	return boundaryDefaultValue, boundaryDefaultErr
}

func buildBoundaryDefaultUncached() (Closure, error) {
	c, err := lift.BuildDefault()
	if err != nil {
		return Closure{}, err
	}
	return Build(c, 1e-9, 8)
}

func Build(c lift.Compression, eps float64, maxDim int) (Closure, error) {
	if eps <= 0 {
		eps = 1e-9
	}
	if maxDim <= 0 {
		maxDim = 512
	}
	basis := make([]linear.Matrix, 0)
	for _, seed := range c.RestrictedGenerators {
		var added bool
		var err error
		basis, added, err = addIndependent(basis, seed, eps)
		if err != nil {
			return Closure{}, err
		}
		_ = added
	}
	seedDim := len(basis)
	if seedDim == 0 {
		return Closure{}, fmt.Errorf("boundary closure has zero-dimensional seed")
	}

	iterations := 0
	cutoff := false
	for {
		iterations++
		changed := false
		current := len(basis)
		for i := 0; i < current; i++ {
			for j := i + 1; j < current; j++ {
				bracket, err := commutator(basis[i], basis[j])
				if err != nil {
					return Closure{}, err
				}
				var added bool
				basis, added, err = addIndependent(basis, bracket, eps)
				if err != nil {
					return Closure{}, err
				}
				if added {
					changed = true
					if len(basis) >= maxDim {
						cutoff = true
						break
					}
				}
			}
			if cutoff {
				break
			}
		}
		if cutoff || !changed {
			break
		}
		// A safety guard: a stable finite closure should settle quickly. If it
		// does not, the dimension-growth result is already the important truth.
		if iterations > maxDim {
			cutoff = true
			break
		}
	}

	derivedBasis, err := buildDerivedBasis(basis, eps)
	if err != nil {
		return Closure{}, err
	}
	centerDim, err := centerDimension(basis, eps)
	if err != nil {
		return Closure{}, err
	}
	absResidual, relResidual, err := closureResidual(basis)
	if err != nil {
		return Closure{}, err
	}
	maxSkew, maxLeak, err := boundaryResiduals(basis, c.BooleanContactProjector, c.BooleanComplementProjector)
	if err != nil {
		return Closure{}, err
	}

	return Closure{
		Compression:                c,
		SeedDimension:              seedDim,
		ClosureDimension:           len(basis),
		DerivedDimension:           len(derivedBasis),
		CenterDimension:            centerDim,
		Basis:                      basis,
		DerivedBasis:               derivedBasis,
		MaxSkewResidual:            maxSkew,
		MaxBoundaryLeakage:         maxLeak,
		MaxClosureResidual:         absResidual,
		MaxClosureRelativeResidual: relResidual,
		Iterations:                 iterations,
		CutoffReached:              cutoff,
		MaxDimension:               maxDim,
	}, nil
}

func addIndependent(basis []linear.Matrix, candidate linear.Matrix, eps float64) ([]linear.Matrix, bool, error) {
	if len(basis) > 0 {
		if candidate.Rows() != basis[0].Rows() || candidate.Cols() != basis[0].Cols() {
			return nil, false, fmt.Errorf("candidate shape mismatch")
		}
	}
	residual := candidate.Clone()
	for _, b := range basis {
		coeff, err := inner(residual, b)
		if err != nil {
			return nil, false, err
		}
		residual, err = residual.Sub(b.Scale(coeff))
		if err != nil {
			return nil, false, err
		}
	}
	norm := residual.FrobeniusNorm()
	if norm <= eps {
		return basis, false, nil
	}
	basis = append(basis, residual.Scale(1/norm))
	return basis, true, nil
}

func buildDerivedBasis(basis []linear.Matrix, eps float64) ([]linear.Matrix, error) {
	out := make([]linear.Matrix, 0)
	for i := 0; i < len(basis); i++ {
		for j := i + 1; j < len(basis); j++ {
			bracket, err := commutator(basis[i], basis[j])
			if err != nil {
				return nil, err
			}
			var added bool
			out, added, err = addIndependent(out, bracket, eps)
			if err != nil {
				return nil, err
			}
			_ = added
		}
	}
	return out, nil
}

func centerDimension(basis []linear.Matrix, eps float64) (int, error) {
	d := len(basis)
	if d == 0 {
		return 0, nil
	}
	gram := linear.NewMatrix(d, d)
	for a := 0; a < d; a++ {
		for b := a; b < d; b++ {
			sum := 0.0
			for j := 0; j < d; j++ {
				ca, err := commutator(basis[a], basis[j])
				if err != nil {
					return 0, err
				}
				cb, err := commutator(basis[b], basis[j])
				if err != nil {
					return 0, err
				}
				ip, err := inner(ca, cb)
				if err != nil {
					return 0, err
				}
				sum += ip
			}
			gram.Set(a, b, sum)
			gram.Set(b, a, sum)
		}
	}
	eig, err := linear.SymmetricEigenJacobi(gram, 1e-12, 0)
	if err != nil {
		return 0, err
	}
	zeros := 0
	for _, value := range eig.Values {
		if math.Abs(value) < eps {
			zeros++
		}
	}
	return zeros, nil
}

func closureResidual(basis []linear.Matrix) (float64, float64, error) {
	maxAbs := 0.0
	maxRel := 0.0
	for i := 0; i < len(basis); i++ {
		for j := i + 1; j < len(basis); j++ {
			bracket, err := commutator(basis[i], basis[j])
			if err != nil {
				return 0, 0, err
			}
			residual := bracket.Clone()
			for _, b := range basis {
				coeff, err := inner(residual, b)
				if err != nil {
					return 0, 0, err
				}
				residual, err = residual.Sub(b.Scale(coeff))
				if err != nil {
					return 0, 0, err
				}
			}
			abs := residual.FrobeniusNorm()
			norm := bracket.FrobeniusNorm()
			rel := 0.0
			if norm > 0 {
				rel = abs / norm
			}
			if abs > maxAbs {
				maxAbs = abs
			}
			if rel > maxRel {
				maxRel = rel
			}
		}
	}
	return maxAbs, maxRel, nil
}

func boundaryResiduals(basis []linear.Matrix, pk linear.Matrix, pc linear.Matrix) (float64, float64, error) {
	maxSkew := 0.0
	maxLeak := 0.0
	for _, op := range basis {
		skew, err := op.Add(op.Transpose())
		if err != nil {
			return 0, 0, err
		}
		if n := skew.FrobeniusNorm(); n > maxSkew {
			maxSkew = n
		}
		left, err := pk.Mul(op)
		if err != nil {
			return 0, 0, err
		}
		left, err = left.Mul(pc)
		if err != nil {
			return 0, 0, err
		}
		right, err := pc.Mul(op)
		if err != nil {
			return 0, 0, err
		}
		right, err = right.Mul(pk)
		if err != nil {
			return 0, 0, err
		}
		if n := left.FrobeniusNorm(); n > maxLeak {
			maxLeak = n
		}
		if n := right.FrobeniusNorm(); n > maxLeak {
			maxLeak = n
		}
	}
	return maxSkew, maxLeak, nil
}

func commutator(a, b linear.Matrix) (linear.Matrix, error) {
	ab, err := a.Mul(b)
	if err != nil {
		return linear.Matrix{}, err
	}
	ba, err := b.Mul(a)
	if err != nil {
		return linear.Matrix{}, err
	}
	return ab.Sub(ba)
}

func inner(a, b linear.Matrix) (float64, error) {
	if a.Rows() != b.Rows() || a.Cols() != b.Cols() {
		return 0, fmt.Errorf("inner product shape mismatch")
	}
	sum := 0.0
	for r := 0; r < a.Rows(); r++ {
		for c := 0; c < a.Cols(); c++ {
			sum += a.At(r, c) * b.At(r, c)
		}
	}
	return sum, nil
}
