package boundary

import (
	"fmt"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func BoundaryFixedClosureTheorem() theorem.Theorem {
	const id = "GAUGE-BOUNDARY-FIXED-CLOSURE"
	const name = "minimal boundary-fixed Lie algebra generated by Boolean-compressed g₂ᴿ"
	return theorem.Theorem{
		ID:     id,
		Name:   name,
		Layer:  theorem.LayerGauge,
		Status: theorem.OpenTest,
		Verify: func() theorem.Result {
			const eps = 1e-8
			closure, err := BuildDefault()
			if err != nil {
				return theorem.Result{
					ID: id, Name: name, Layer: theorem.LayerGauge, Status: theorem.FailedRoute,
					Checks: []theorem.Check{{Name: "construct boundary-fixed closure", Passed: false, Detail: err.Error()}},
				}
			}
			stable := !closure.CutoffReached && closure.MaxClosureRelativeResidual < eps && closure.MaxBoundaryLeakage < eps && closure.MaxSkewResidual < eps
			su2u1 := closure.ClosureDimension == 4 && closure.DerivedDimension == 3 && closure.CenterDimension == 1
			status := theorem.OpenTest
			if stable && su2u1 {
				status = theorem.VerifiedNumeric
			}
			notes := []string{
				"This gate does not force the tangent su(2)⊕u(1) answer. It computes the finite Lie algebra generated after the contact boundary is imposed.",
				"If the closure dimension grows beyond 4, the finite Boolean geometry is asking for an enlarged algebra or a different projection principle.",
			}
			if stable && !su2u1 {
				notes = append(notes, "Result: a stable boundary-fixed Lie algebra exists, but it is not the original four-dimensional su(2)⊕u(1) candidate.")
			}
			if closure.CutoffReached {
				notes = append(notes, "Result: closure kept growing until the configured cutoff; this is evidence against a small finite electroweak algebra under the current projection.")
			}
			checks := []theorem.Check{
				{
					Name:   "seed algebra from Gate 8",
					Passed: closure.SeedDimension > 0,
					Detail: fmt.Sprintf("seed span dimension=%d from boundary-fixed compressed generators", closure.SeedDimension),
				},
				{
					Name:   "boundary-fixed construction",
					Passed: closure.MaxBoundaryLeakage < eps,
					Detail: fmt.Sprintf("max ||P_KJP_C|| or ||P_CJP_K|| across closure basis = %.3e", closure.MaxBoundaryLeakage),
				},
				{
					Name:   "skew finite generators",
					Passed: closure.MaxSkewResidual < eps,
					Detail: fmt.Sprintf("max ||J+Jᵀ||_F across closure basis = %.3e", closure.MaxSkewResidual),
				},
				{
					Name:   "Lie closure reached",
					Passed: !closure.CutoffReached && closure.MaxClosureRelativeResidual < eps,
					Detail: fmt.Sprintf("closure dim=%d, iterations=%d, cutoff=%t, max relative residual=%.3e", closure.ClosureDimension, closure.Iterations, closure.CutoffReached, closure.MaxClosureRelativeResidual),
				},
				{
					Name:   "algebra signature",
					Passed: closure.ClosureDimension > 0,
					Detail: fmt.Sprintf("dimension=%d, derived dimension=%d, center dimension=%d", closure.ClosureDimension, closure.DerivedDimension, closure.CenterDimension),
				},
				{
					Name:   "finite electroweak-sized theorem",
					Passed: stable && su2u1,
					Detail: "requires stable closure with dimension=4, derived=3, center=1",
				},
			}
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerGauge, Status: status, Checks: checks, Notes: notes}
		},
	}
}
