package gaugecouplingboundaryseal

import "github.com/bagherbal/asha-engine/pkg/theorem"

func GaugeCouplingBoundarySealSymbolicRGEvaluationFirewallTheorem() theorem.Theorem {
	const id = "BRIDGE-GAUGE-COUPLING-BOUNDARY-SEAL-SYMBOLIC-RG-EVALUATION-FIREWALL-AUDIT"
	const name = "gauge-coupling boundary seal / symbolic RG evaluation firewall audit"
	return theorem.Theorem{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: []theorem.Check{{Name: "build gauge-coupling boundary seal audit", Passed: false, Detail: err.Error()}}}
		}
		return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: []theorem.Check{
			{Name: "Gate 198 symbolic threshold scaffold is inherited", Passed: a.BoundaryAudit.Gate198ThresholdTreeInherited && a.PreviousGate198.Summary.PiecewiseRGScaffoldBuilt && a.PreviousGate198.Firewall.ConditionalBetaRowsActivated && !a.PreviousGate198.Firewall.PhysicalRGFlowEvaluated, Detail: a.PreviousGate198.TruthStatement},
			{Name: "boundary scale seal is explicit and quarantined", Passed: a.ScaleSeal.ExplicitBoundaryData && a.ScaleSeal.Quarantined && a.ScaleSeal.RequiredForTopDownEvaluation && !a.ScaleSeal.DerivedFromFiniteAlgebra && !a.ScaleSeal.DerivedFromTopologicalSeal && !a.ScaleSeal.ObservedValueInserted && a.ScaleSeal.DownstreamMustDeclareSeal, Detail: FormatScaleSeal(a.ScaleSeal)},
			{Name: "absolute coupling seal is explicit and not set to the topological unit branch", Passed: a.CouplingSeal.ExplicitBoundaryData && a.CouplingSeal.Quarantined && a.CouplingSeal.Dimensionless && a.CouplingSeal.RequiredForTopDownEvaluation && !a.CouplingSeal.DerivedFromFiniteAlgebra && !a.CouplingSeal.DerivedFromEightPiSquared && !a.CouplingSeal.UnitTopologicalBranchAssumed && !a.CouplingSeal.ObservedValueInserted && a.CouplingSeal.DownstreamMustDeclareSeal, Detail: FormatCouplingSeal(a.CouplingSeal)},
			{Name: "top-down and bottom-up directions are separated", Passed: a.BoundaryAudit.TopDownUVParametersAccepted && a.BoundaryAudit.BottomUpIRInputsAllowedForAudit && !a.BoundaryAudit.BottomUpIRInputsDerived && a.BoundaryAudit.IRCouplingsQuarantinedIfUsed && a.BoundaryAudit.TopologicalUOneBranchAvailableOnlyAsComparison && !a.BoundaryAudit.BoundaryDataDerivedFromFinite && !a.BoundaryAudit.ObservedInputsUsedInDefaultBuild, Detail: FormatBoundaryAudit(a.BoundaryAudit)},
			{Name: "closed-form symbolic RG trajectory is assembled but not evaluated", Passed: a.Trajectory.BaselineBetaVector.Equal(BetaVector{U1Y: R(41, 10), SU2L: R(-19, 6), SU3C: R(-7, 1)}) && a.Trajectory.FermionContributionVector.Equal(BetaVector{U1Y: R(4, 1), SU2L: R(4, 1), SU3C: R(4, 1)}) && a.Trajectory.ThresholdRows == 12 && a.Trajectory.PiecewiseClosedFormBuilt && a.Trajectory.TreeLevelContinuityInherited && a.Trajectory.FiniteMatchingCorrectionsSealed && !a.Trajectory.ThresholdOrderingKnown && !a.Trajectory.EvaluatedNumerically && !a.Trajectory.PhysicalPredictionMade && !a.Trajectory.UsesObservedCouplings, Detail: FormatTrajectory(a.Trajectory)},
			{Name: "bottom-up convergence is only a quarantined viability audit", Passed: a.BottomUp.AllowedAsPhenomenologicalAudit && a.BottomUp.RequiresIRCouplingSeal && a.BottomUp.InvertibilityEquationsBuilt && a.BottomUp.PairwiseDifferenceEquationsBuilt && a.BottomUp.CanSolveFormalPairwiseLogIntervals && a.BottomUp.CanTestUEqualsOneIfInputsProvided && !a.BottomUp.TopologicalUOneDerived && !a.BottomUp.IRInputsDerived && !a.BottomUp.ThresholdOrderingKnown && !a.BottomUp.NumericalConvergenceDetermined && !a.BottomUp.ReducesStrictNullity, Detail: FormatBottomUp(a.BottomUp)},
			{Name: "low-energy evaluation domain remains bounded by W/Z and threshold-ordering firewalls", Passed: a.Domain.FormalFermionThresholdsAvailable && !a.Domain.FermionThresholdOrderingKnown && !a.Domain.GaugeBosonThresholdsAvailable && a.Domain.WZThresholdsBlocked && !a.Domain.RunToMZAllowed && !a.Domain.DeepInfraredFlowDefined, Detail: FormatDomain(a.Domain)},
			{Name: "absolute coupling, continuum normalization, observed-input, and physical prediction firewalls remain sealed", Passed: a.Firewall.Gate198Inherited && !a.Firewall.BoundaryScaleDerivedStrict && !a.Firewall.AbsoluteCouplingDerivedStrict && !a.Firewall.GaugeCouplingsDerived && !a.Firewall.TopologicalEightPiSquaredImported && !a.Firewall.FiniteToContinuumScaleDerived && !a.Firewall.ObservedInputsImported && !a.Firewall.PhysicalRGPredictionMade && !a.Firewall.NumericalTrajectoryEvaluated && !a.Firewall.WZThresholdsDerived && !a.Firewall.ThresholdOrderingDerived && !a.Firewall.FiniteMatchingCorrectionsDerived && !a.Firewall.BottomUpAuditCanDeriveFiniteTheorem && a.Firewall.StrictNullityBefore == 3 && a.Firewall.StrictNullityAfter == 3 && a.Firewall.ConditionalBoundarySealNullityBefore == 1 && a.Firewall.ConditionalBoundarySealNullityAfter == 0 && a.Firewall.ConditionalSymbolicEvaluationNullityBefore == 1 && a.Firewall.ConditionalSymbolicEvaluationNullityAfter == 0 && a.Firewall.PhysicalPredictionNullityBefore == a.Firewall.PhysicalPredictionNullityAfter, Detail: FormatFirewall(a.Firewall)},
			{Name: "summary records symbolic evaluation without physical overclaim", Passed: a.Summary.TestsAudited == 7 && a.Summary.UVBoundarySealsRecorded && a.Summary.SymbolicTopDownTrajectoryBuilt && a.Summary.BottomUpViabilityAuditSeparated && a.Summary.LowEnergyDomainFirewallPreserved && a.Summary.AbsoluteCouplingFirewallPreserved && a.Summary.NoObservedInputsInDefaultBuild, Detail: FormatSummary(a.Summary)},
		}, Notes: []string{
			a.TruthStatement,
			"Gate 199 answer: the engine accepts both directions, but separates them. Top-down M*,u* boundary seals generate symbolic IR trajectories. Bottom-up IR inputs are admitted only as a quarantined convergence/viability audit and never as a derivation of the finite UV boundary.",
			"Matching answer inherited from Gate 198: tree-level continuity is enforced at threshold surfaces; finite threshold matching corrections remain scheme-dependent and sealed.",
		}}
	}}
}
