package generation2boundaryquotientpayofffunctionalselectionaudit

import (
	"math"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2BoundaryQuotientPayoffFunctionalSelectionAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 697 — Boundary Quotient Payoff Functional Selection Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 697 — Boundary Quotient Payoff Functional Selection Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate696 support-local Bernoulli observable", Passed: a.Inherited.SupportLocalBernoulliObservableInherited && a.Inherited.Rho72Definition == "rho_72 = I_H72/72" && a.Inherited.SupportLocalObservable == "R_a=aP_K7" && a.Inherited.BoundaryPayoffAssignment == "a=S_split" && a.Inherited.ReconstructedOperator == "R_split=S_split P_K7" && math.Abs(a.Inherited.EventPayoff-a.Inherited.SSplit) < tolerance && a.Inherited.ComplementPayoff == 0 && a.Inherited.NoExpectationAloneSelection && a.Inherited.NoNativeSupportLocality && a.Inherited.NoNativeSSplitPayoff && a.Inherited.NoNativeSevenOver72 && a.Inherited.Verdict == StatusGate696SupportLocalBernoulliObservableInherited, Detail: FormatInheritance(a.Inherited)},
			{Name: "define payoff source problem", Passed: a.PayoffProblem.InheritedObservable == "R_a=aP_K7" && strings.Contains(a.PayoffProblem.KnownSupportResult, "b=0") && a.PayoffProblem.RemainingQuestion == "a ?= S_split" && a.PayoffProblem.SupportLocalityFixesB && a.PayoffProblem.EventPayoffStillUnfixed && strings.Contains(a.PayoffProblem.CandidatePayoff, "lambda") && a.PayoffProblem.Verdict == StatusPayoffSourceProblemDefined, Detail: FormatPayoffProblem(a.PayoffProblem)},
			{Name: "define boundary quotient and sigma coordinate", Passed: strings.Contains(a.Quotient.BoundarySpace, "span") && math.Abs(a.Quotient.BoundaryVector[0]-lambdaLambda12) < tolerance && math.Abs(a.Quotient.BoundaryVector[1]-r3Minus1) < tolerance && a.Quotient.AntiAlignmentGenerator == [2]float64{-1, 1} && math.Abs(a.Quotient.SigmaOnAntiAlignment) < tolerance && a.Quotient.KernelMatchesWall && a.Quotient.DescendsToQuotient && strings.Contains(a.Quotient.QuotientSpace, "B_boundary/L_anti") && math.Abs(a.Quotient.SSplit-a.Inherited.SSplit) < 5e-16 && a.Quotient.SSplitMatchesSigma && strings.Contains(a.Quotient.Verdict, StatusSigmaBoundaryDescendsToQuotientCoordinate), Detail: FormatQuotient(a.Quotient)},
			{Name: "interpret S_split as boundary quotient payoff", Passed: a.Interpretation.EventPayoff == "a=S_split=sigma_boundary(b)" && a.Interpretation.Observable == "R_split=sigma_boundary(b)P_K7" && strings.Contains(a.Interpretation.EquivalentOperator, "lambda") && math.Abs(a.Interpretation.Payoff-a.Inherited.SSplit) < tolerance && a.Interpretation.K7ReceivesBoundaryDefect && a.Interpretation.DoesNotProveCoupling && strings.Contains(a.Interpretation.Verdict, StatusSSplitCanonicalAntiAlignmentQuotientPayoff), Detail: FormatInterpretation(a.Interpretation)},
			{Name: "audit alternative boundary payoff functionals", Passed: len(a.Alternatives.Alternatives) == 5 && a.Alternatives.LambdaOnlyRejected && a.Alternatives.GaugeOnlyRejected && a.Alternatives.AntiAlignedRejected && a.Alternatives.MidpointStressRejected && a.Alternatives.SplitPayoffAccepted && a.Alternatives.AllAudited && a.Alternatives.Verdict == StatusAlternativeBoundaryPayoffsAudited, Detail: FormatAlternatives(a.Alternatives)},
			{Name: "preserve wall-coordinate scale normalization firewall", Passed: a.ScaleFirewall.QuotientCoordinateUniqueUpToScale && a.ScaleFirewall.ScaledFunctional == "c*sigma_boundary" && strings.Contains(a.ScaleFirewall.ActiveNormalizationSource, "unit coefficients") && a.ScaleFirewall.UnitCoefficientLambda == 1 && a.ScaleFirewall.UnitCoefficientGauge == 1 && !a.ScaleFirewall.ClaimsNativePayoffNormalization && a.ScaleFirewall.Verdict == StatusPayoffFunctionalUniqueOnlyUpToNormalization, Detail: FormatScaleFirewall(a.ScaleFirewall)},
			{Name: "reconstruct event expectation", Passed: a.Expectation.Rho72 == "rho_72=I_H72/72" && a.Expectation.ResponseOperator == "R_split=sigma_boundary(b)P_K7" && math.Abs(a.Expectation.K7Weight-7.0/72.0) < tolerance && strings.Contains(a.Expectation.ExpectationFormula, "(7/72)S_split") && math.Abs(a.Expectation.Expectation-a.Inherited.Expectation) < tolerance && math.Abs(a.Expectation.DBase-a.Inherited.DBase) < tolerance && math.Abs(a.Expectation.ResidualE1-a.Inherited.ResidualE1) < 1e-18 && a.Expectation.MatchesInherited && a.Expectation.Verdict == StatusEventExpectationReconstructed, Detail: FormatExpectation(a.Expectation)},
			{Name: "classify source types", Passed: strings.Contains(a.SourceTypes.BoundarySpaceRole, "boundary") && strings.Contains(a.SourceTypes.SigmaBoundaryRole, "quotient") && strings.Contains(a.SourceTypes.SSplitRole, "payoff") && strings.Contains(a.SourceTypes.PK7Role, "Boolean-octonionic") && strings.Contains(a.SourceTypes.Rho72Role, "maximum-entropy") && strings.Contains(a.SourceTypes.RSplitRole, "K7 event") && a.SourceTypes.Verdict == StatusActiveResponseK7EventBoundaryQuotientPayoff, Detail: FormatSourceTypes(a.SourceTypes)},
			{Name: "record missing payoff-coupling theorem", Passed: len(a.Missing.Candidates) == 5 && strings.Contains(a.Missing.PreciseGap, "why the Boolean-octonionic K7 event") && strings.Contains(a.Missing.Verdict, StatusNoNativeReasonK7ReceivesBoundaryQuotientPayoff) && strings.Contains(a.Missing.Verdict, StatusNoNativePayoffCouplingTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeHistoryResponseTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeSevenOver72Theorem), Detail: FormatMissing(a.Missing)},
			{Name: "preserve Gate697 boundary quotient payoff firewall", Passed: !a.Firewall.ClaimsK7ReceivesBoundaryPayoffNatively && !a.Firewall.ClaimsNativePayoffCouplingTheorem && !a.Firewall.ClaimsNativeHistoryResponseTheorem && !a.Firewall.ClaimsNativeSevenOver72Theorem && !a.Firewall.ClaimsBoundaryStressDerived && !a.Firewall.ClaimsScalarRGMatching && !a.Firewall.ClaimsHiggsMass && !a.Firewall.ClaimsGaugeUnification && !a.Firewall.ClaimsFlavorDerivation && !a.Firewall.ClaimsCKMPMNS && a.Firewall.Verdict == StatusGate697BoundaryQuotientPayoffBoundary, Detail: FormatFirewall(a.Firewall)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 697 — Boundary Quotient Payoff Functional Selection Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
