package generation2quotientlinenormalizationandresponsecoefficientcovarianceaudit

import (
	"math"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2QuotientLineNormalizationAndResponseCoefficientCovarianceAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 701 — Quotient-Line Normalization and Response Coefficient Covariance Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 701 — Quotient-Line Normalization and Response Coefficient Covariance Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}, Notes: []string{StatusGate701QuotientNormalizationBoundary}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate700 conditional response law", Passed: a.Inherited.InheritedConditionalLaw && math.Abs(a.Inherited.SigmaBoundary-canonicalSBoundary()) < tolerance && math.Abs(a.Inherited.SigmaHistory-canonicalSHistory()) < tolerance && math.Abs(a.Inherited.Expectation-canonicalExpectation()) < tolerance && math.Abs(a.Inherited.ResidualE1-canonicalResidual()) < strictTol && a.Inherited.PremisesNonredundant && a.Inherited.NoNativePrinciple && a.Inherited.NoNativeSevenOver72 && a.Inherited.Verdict == StatusGate700ConditionalHistoryResponseLawInherited, Detail: FormatInheritance(a.Inherited)},
			{Name: "define quotient-line rescaling and compute covariance", Passed: a.Rescaling.BoundaryScale == 2 && a.Rescaling.HistoryScale == 3 && math.Abs(a.Rescaling.OriginalCoefficient-eventProbK7) < tolerance && math.Abs(a.Rescaling.TransformedCoefficient-(3.0/2.0)*eventProbK7) < tolerance && strings.Contains(a.Rescaling.Formula, "beta/alpha") && a.Rescaling.CoefficientCovariant && !a.Rescaling.CoefficientInvariant && strings.Contains(a.Rescaling.Verdict, StatusQuotientLineRescalingDefined) && strings.Contains(a.Rescaling.Verdict, StatusResponseCoefficientTransformationComputed) && strings.Contains(a.Rescaling.Verdict, StatusResponseCoeffNotInvariantUnderArbitraryQuotientRescaling), Detail: FormatRescaling(a.Rescaling)},
			{Name: "separate invariant K7 event probability", Passed: a.Probability.ProbabilityName == "p_K7" && math.Abs(a.Probability.Probability-eventProbK7) < tolerance && strings.Contains(a.Probability.TraceFormula, "rho_72") && strings.Contains(a.Probability.TraceFormula, "P_K7") && a.Probability.IndependentOfAlpha && a.Probability.IndependentOfBeta && a.Probability.InvariantObjectSeparated && a.Probability.ResponseCoefficientNeedsCoordinates && strings.Contains(a.Probability.Verdict, StatusEventProbabilityInvariantSeparated) && strings.Contains(a.Probability.Verdict, StatusSevenOver72InvariantAsK7EventProbability), Detail: FormatProbability(a.Probability)},
			{Name: "audit canonical wall-coordinate normalization", Passed: strings.Contains(a.WallNormalize.BoundaryCoordinate, "lambda+(R_3-1)") && strings.Contains(a.WallNormalize.HistoryCoordinate, "kappa_lambda+kappa_e+lambda") && a.WallNormalize.BoundaryUsesUnitWallCoefficients && a.WallNormalize.HistoryUsesUnitWallCoefficients && a.WallNormalize.SameWallDistanceFamily && a.WallNormalize.CanonicalAlpha == 1 && a.WallNormalize.CanonicalBeta == 1 && a.WallNormalize.CoefficientEqualsProbability && a.WallNormalize.EqualScaleRequiredForDirectEquality && strings.Contains(a.WallNormalize.Verdict, StatusWallCoordinateNormalizationAudited) && strings.Contains(a.WallNormalize.Verdict, StatusResponseCoefficientEqualsEventProbabilityOnlyCanonicalWalls) && strings.Contains(a.WallNormalize.Verdict, StatusGate700LawCoordinateSealedNotCoordinateFree), Detail: FormatWallNormalization(a.WallNormalize)},
			{Name: "compute alternative normalization examples", Passed: len(a.Alternatives.Examples) == 3 && a.Alternatives.AllComputed && a.Alternatives.NonInvariantSeen && a.Alternatives.CanonicalSeen && math.Abs(a.Alternatives.Examples[0].TransformedCoefficient-7.0/144.0) < tolerance && math.Abs(a.Alternatives.Examples[1].TransformedCoefficient-7.0/36.0) < tolerance && math.Abs(a.Alternatives.Examples[2].TransformedCoefficient-7.0/72.0) < tolerance && a.Alternatives.Verdict == StatusAlternativeNormalizationExamplesComputed, Detail: FormatAlternatives(a.Alternatives)},
			{Name: "preserve source-type separation", Passed: strings.Contains(a.Source.InvariantObject, "p_K7") && strings.Contains(a.Source.CoordinateSealedObject, "wall-distance") && a.Source.DoesNotWeakenGate700 && a.Source.ClarifiesSourceType && strings.Contains(a.Source.Verdict, StatusEventProbabilityInvariantSeparated) && strings.Contains(a.Source.Verdict, StatusGate700LawCoordinateSealedNotCoordinateFree), Detail: FormatSource(a.Source)},
			{Name: "sharpen missing theorem pair", Passed: len(a.Missing.Theorems) == 6 && strings.Contains(a.Missing.PrecisePair, "p_K7=7/72") && strings.Contains(a.Missing.PrecisePair, "aligned unit wall-distance") && strings.Contains(a.Missing.Verdict, StatusNoNativeWallCoordinateNormalizationAlignmentTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeBoundaryHistoryResponsePrinciple) && strings.Contains(a.Missing.Verdict, StatusNoNativeSevenOver72Theorem), Detail: FormatMissing(a.Missing)},
			{Name: "preserve Gate701 quotient-normalization firewall", Passed: !a.Firewall.ClaimsResponseCoefficientCoordinateFree && !a.Firewall.ClaimsNativeWallNormalization && !a.Firewall.ClaimsNativeBoundaryHistoryPrinciple && !a.Firewall.ClaimsNativeSevenOver72Theorem && !a.Firewall.ClaimsBoundaryStressDerived && !a.Firewall.ClaimsScalarRGMatching && !a.Firewall.ClaimsHiggsMass && !a.Firewall.ClaimsGaugeUnification && !a.Firewall.ClaimsFlavorDerivation && !a.Firewall.ClaimsCKMPMNS && a.Firewall.Verdict == StatusGate701QuotientNormalizationBoundary, Detail: FormatFirewall(a.Firewall)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 701 — Quotient-Line Normalization and Response Coefficient Covariance Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
