package generation2k7minuscomplexstructureselectorandso3gaugefirewallaudit

import (
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2K7MinusComplexStructureSelectorAndSO3GaugeFirewallAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 712 — K7- Complex-Structure Selector and SO(3) Gauge Firewall Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 712 — K7- Complex-Structure Selector and SO(3) Gauge Firewall Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate711 U2 socket", Passed: a.Inherited.U2SocketInherited && a.Inherited.K7PlusDimension == k7PlusDimension && a.Inherited.K7MinusDimension == k7MinusDimension && a.Inherited.CanSelectJH && a.Inherited.U2SocketAfterChoice && a.Inherited.InternalSU2SocketCandidate && a.Inherited.InternalU1SocketCandidate && !a.Inherited.CanonicalJHSelected && !a.Inherited.PhysicalElectroweakU2 && !a.Inherited.PhysicalHiggsDoubletMap && !a.Inherited.HyperchargeAssignment && !a.Inherited.YukawaOperatorCertified && !a.Inherited.HiggsMassCertified && a.Inherited.Verdict == StatusGate711U2SocketInherited, Detail: FormatInherited(a.Inherited)},
			{Name: "audit K7- to complex-structure family map", Passed: strings.Contains(a.FamilyMap.Domain, "S^2") && strings.Contains(a.FamilyMap.Codomain, "J_H") && strings.Contains(a.FamilyMap.Map, "n_a J_a") && a.FamilyMap.UnitSphereDimension == sphereDimension && a.FamilyMap.K7MinusDimension == k7MinusDimension && strings.Contains(a.FamilyMap.JHSquared, "-I") && a.FamilyMap.UnitDirectionWouldSelect && !a.FamilyMap.NativeSelectorFound && a.FamilyMap.FamilyValuedU2Socket && !a.FamilyMap.CanonicalComplexStructure && strings.Contains(a.FamilyMap.Verdict, StatusK7MinusToComplexStructureFamilyMapAudited) && strings.Contains(a.FamilyMap.Verdict, StatusU2SocketFamilyValuedOverS2), Detail: FormatFamilyMap(a.FamilyMap)},
			{Name: "audit SO3 covariance of K7- frame", Passed: strings.Contains(a.SO3Covariance.FrameTransform, "SO(3)") && strings.Contains(a.SO3Covariance.TwoFormTransform, "omega") && a.SO3Covariance.PreservesOmega && a.SO3Covariance.PreservesEta123 && a.SO3Covariance.GaugeCovariantFrame && !a.SO3Covariance.CanonicalOrderedFrame && !a.SO3Covariance.SelectsSingleAxis && !a.SO3Covariance.PhysicalGenerationAxis && strings.Contains(a.SO3Covariance.Verdict, StatusSO3CovarianceOfK7MinusFrameAudited) && strings.Contains(a.SO3Covariance.Verdict, StatusFanoVolumeOrFrameDoesNotSelectSingleAxis), Detail: FormatSO3(a.SO3Covariance)},
			{Name: "audit selector candidates", Passed: len(a.Selectors.Candidates) == 7 && !a.Selectors.NativeSelectorFound && a.Selectors.BoundaryScalarsRejected && a.Selectors.HistoryScalarsRejected && a.Selectors.ExternalSealOnly && strings.Contains(a.Selectors.Verdict, StatusSelectorCandidatesAudited) && strings.Contains(a.Selectors.Verdict, StatusNoNativeK7MinusUnitVectorSelector) && strings.Contains(a.Selectors.Verdict, StatusBoundaryScalarAndHistoryScalarsDoNotSelectDirection), Detail: FormatSelectors(a.Selectors)},
			{Name: "preserve gauge versus physical selector firewall", Passed: a.GaugeFirewall.FamilyValuedPreHiggsCarriers && !a.GaugeFirewall.UniqueHiggsComplexStructure && !a.GaugeFirewall.PhysicalHiggsDoubletMap && !a.GaugeFirewall.PhysicalGenerationSpaceMap && !a.GaugeFirewall.YukawaOperatorMap && !a.GaugeFirewall.FlavorHierarchyTheorem && !a.GaugeFirewall.CKMPMNSThereom && strings.Contains(a.GaugeFirewall.Verdict, StatusNoCanonicalHiggsComplexStructureSelected) && strings.Contains(a.GaugeFirewall.Verdict, StatusNoTypedK7PlusToPhysicalHiggsDoubletMap) && strings.Contains(a.GaugeFirewall.Verdict, StatusNoTypedK7MinusToPhysicalGenerationSpaceMap), Detail: FormatGaugeFirewall(a.GaugeFirewall)},
			{Name: "classify missing vacuum selector", Passed: strings.Contains(a.VacuumSelector.MissingObject, "n_*") && strings.Contains(a.VacuumSelector.SelectorType, "vacuum") && !a.VacuumSelector.NativeTheoremCertified && a.VacuumSelector.EnvironmentalSealAllowed && a.VacuumSelector.SealMustBeQuarantined && strings.Contains(a.VacuumSelector.Verdict, StatusNoNativeK7MinusUnitVectorSelector), Detail: FormatVacuumSelector(a.VacuumSelector)},
			{Name: "record flavor relation without promoting it", Passed: strings.Contains(a.FlavorRelation.SO3BreakPattern, "SO(3) to SO(2)") && a.FlavorRelation.ResemblesFlavorAxis && !a.FlavorRelation.GenerationCarrierMap && !a.FlavorRelation.FlavorOrientationMap && !a.FlavorRelation.YukawaEigenvalueMap && !a.FlavorRelation.CKMPMNSMap && strings.Contains(a.FlavorRelation.Verdict, StatusNoTypedK7MinusToPhysicalGenerationSpaceMap), Detail: FormatFlavorRelation(a.FlavorRelation)},
			{Name: "record missing physical maps", Passed: strings.Contains(a.Missing.ThetaG, "generation") && strings.Contains(a.Missing.ThetaJH, "Higgs complex structure") && strings.Contains(a.Missing.ThetaY, "Yukawa") && len(a.Missing.Missing) == 5 && strings.Contains(a.Missing.Verdict, StatusNoCanonicalHiggsComplexStructureSelected) && strings.Contains(a.Missing.Verdict, StatusNoYukawaOperatorOrEigenvalueTheorem), Detail: FormatMissing(a.Missing)},
			{Name: "classify source types", Passed: strings.Contains(a.SourceTypes.K7MinusRole, "unit directions") && strings.Contains(a.SourceTypes.FanoFrameRole, "SO(3)-covariant") && strings.Contains(a.SourceTypes.BoundaryRole, "scalar") && strings.Contains(a.SourceTypes.HistoryRole, "scalar") && strings.Contains(a.SourceTypes.SelectorRole, "missing") && strings.Contains(a.SourceTypes.FirewallRole, "family-valued") && strings.Contains(a.SourceTypes.Verdict, StatusGate712K7MinusSelectorBoundary), Detail: FormatSourceTypes(a.SourceTypes)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 712 — K7- Complex-Structure Selector and SO(3) Gauge Firewall Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
