package totalrepresentation

import (
	"fmt"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func FiniteAlgebraTotalHilbertRepresentationFaithfulActionObstructionAuditTheorem() theorem.Theorem {
	const id = "BRIDGE-TOTAL-HILBERT-REPRESENTATION-FAITHFUL-ACTION-OBSTRUCTION"
	const name = "Finite algebra representation on total spectral Hilbert space / faithful action obstruction audit"
	return theorem.Theorem{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.Variational, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build total representation theorem", Passed: false, Detail: err.Error()}}}
		}
		return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.Variational, Checks: []theorem.Check{
			{Name: "Gate 164 finite-Dirac firewall is inherited", Passed: a.Previous.FiniteSpectralPreData && !a.Previous.SpectralTripleComplete && !a.Previous.FiniteDiracSelected && !a.Previous.RealStructureSelected && !a.Previous.GradingSelected && !a.Previous.OrderOneCalculusVerified && !a.Previous.GaugeFluctuationMapDerived && a.Previous.GaugeKineticMapRows == 0 && a.Previous.ThresholdBetaRows == 0 && a.Previous.ResidualNullityAfter == 3 && !a.Previous.HiddenObservedInputUsed, Detail: fmt.Sprintf("preData=%t triple=%t D=%t J=%t gamma=%t order1=%t gauge=%t gaugeRows=%d beta=%d nullity=%d hiddenObserved=%t", a.Previous.FiniteSpectralPreData, a.Previous.SpectralTripleComplete, a.Previous.FiniteDiracSelected, a.Previous.RealStructureSelected, a.Previous.GradingSelected, a.Previous.OrderOneCalculusVerified, a.Previous.GaugeFluctuationMapDerived, a.Previous.GaugeKineticMapRows, a.Previous.ThresholdBetaRows, a.Previous.ResidualNullityAfter, a.Previous.HiddenObservedInputUsed)},
			{Name: "carrier audit finds no canonical total Hilbert space", Passed: a.CarrierAudit.CandidatesAudited == 6 && a.CarrierAudit.AvailableCandidates == 5 && a.CarrierAudit.CanonicalCandidates == 4 && a.CarrierAudit.TotalHilbertCandidates == 2 && a.CarrierAudit.CanonicalTotalHilberts == 0 && !a.CarrierAudit.ObservedInputsUsed, Detail: FormatCarrierAudit(a.CarrierAudit)},
			{Name: "own-carrier representations exist but no faithful total representation exists", Passed: a.AlgebraActionAudit.CandidatesAudited == 8 && a.AlgebraActionAudit.AvailableCandidates == 7 && a.AlgebraActionAudit.CanonicalOwnCarrierActions == 6 && a.AlgebraActionAudit.FaithfulOwnCarrierActions == 4 && a.AlgebraActionAudit.FaithfulTotalRepresentations == 0 && a.AlgebraActionAudit.NontrivialCrossSectorActions == 0 && a.AlgebraActionAudit.NonzeroOneFormActions == 0 && a.AlgebraActionAudit.RequireImportedSMAlgebra == 1 && !a.AlgebraActionAudit.ObservedInputsUsed, Detail: FormatActionAudit(a.AlgebraActionAudit) + " :: " + FormatActions(a.AlgebraActions)},
			{Name: "sector glue maps are diagnostic but not canonical intertwiners", Passed: a.GlueAudit.CandidatesAudited == 5 && a.GlueAudit.AvailableCandidates == 4 && a.GlueAudit.CanonicalCandidates == 0 && a.GlueAudit.IntertwiningCandidates == 0 && a.GlueAudit.IsometricCandidates == 0 && a.GlueAudit.GaloisSafeCandidates == 4 && !a.GlueAudit.ObservedInputsUsed, Detail: FormatGlueAudit(a.GlueAudit)},
			{Name: "no assembly is promotable to a finite spectral triple", Passed: a.AssemblyAudit.CandidatesAudited == 6 && a.AssemblyAudit.AvailableCandidates == 4 && a.AssemblyAudit.CanonicalCandidates == 3 && a.AssemblyAudit.TotalCarrierComplete == 2 && a.AssemblyAudit.FaithfulTotalRepresentations == 0 && a.AssemblyAudit.NontrivialSectorMixing == 0 && a.AssemblyAudit.NonzeroOneForms == 0 && a.AssemblyAudit.PromotableSpectralTriples == 0 && a.AssemblyAudit.GaugeKineticMapRows == 0 && a.AssemblyAudit.ThresholdBetaRows == 0 && !a.AssemblyAudit.PhysicalConstantsDerived && !a.AssemblyAudit.ObservedInputsUsed, Detail: FormatAssemblyAudit(a.AssemblyAudit) + " :: " + FormatAssemblies(a.Assemblies)},
			{Name: "representation firewall preserves beta and constants", Passed: a.Firewall.Gate164Inherited && a.Firewall.FiniteSpectralPreData && a.Firewall.CanonicalCarrierActions == 6 && a.Firewall.FaithfulTotalRepresentations == 0 && a.Firewall.CanonicalGlueMaps == 0 && a.Firewall.PromotableSpectralTriples == 0 && !a.Firewall.SpectralTripleComplete && !a.Firewall.FiniteDiracSelected && !a.Firewall.RealStructureSelected && !a.Firewall.GradingSelected && !a.Firewall.OrderOneCalculusVerified && !a.Firewall.GaugeFluctuationMapDerived && a.Firewall.GaugeKineticMapRows == 0 && a.Firewall.IndividualQuarticRows == 0 && a.Firewall.CanonicalQuarticBranches == 0 && a.Firewall.GaugeRepresentationRows == 0 && a.Firewall.LocalFieldRows == 0 && a.Firewall.MassActivationRows == 0 && a.Firewall.DecouplingRows == 0 && a.Firewall.DynkinIndexRows == 0 && a.Firewall.ThresholdBetaRows == 0 && a.Firewall.ProvenZeroRows == 0 && a.Firewall.BoundaryConstraintsDerived == 0 && !a.Firewall.PhysicalConstantsDerived && a.Firewall.BetaPermissionFirewallClosed, Detail: FormatFirewall(a.Firewall)},
			{Name: "physical bridge remains sealed with nullity unchanged", Passed: a.ContactRows == 7 && a.ContactZetaValues == 5 && a.FiniteSpectralPreData && a.CanonicalCarrierActions == 6 && a.FaithfulTotalRepresentations == 0 && a.CanonicalGlueMaps == 0 && !a.SpectralTripleComplete && !a.SpectralActionPrincipleReady && !a.FiniteDiracSelected && !a.RealStructureSelected && !a.GradingSelected && !a.OrderOneCalculusVerified && !a.OrientabilityVerified && !a.PoincareDualityVerified && !a.KOCompatibilityVerified && !a.CanonicalCutoffSelected && !a.GaugeFluctuationMapDerived && a.GaugeKineticMapRows == 0 && a.IndividualQuarticRows == 0 && a.CanonicalQuarticBranches == 0 && a.GaugeRepresentationRows == 0 && a.SpinStatisticsRows == 0 && a.LocalFieldRows == 0 && a.MassActivationRows == 0 && a.DecouplingRows == 0 && a.DynkinIndexRows == 0 && a.ThresholdBetaRows == 0 && a.ProvenZeroRows == 0 && a.BoundaryConstraintsDerived == 0 && a.ContactBetaRowsAllowed == 0 && a.ContactZeroRowsProved == 0 && a.BetaPermissionFirewallClosed && a.ResidualNullityBefore == 3 && a.ResidualNullityAfter == 3 && !a.ThresholdCorrectedBeta && !a.FullBetaMatchingTensor && !a.HiddenObservedInputUsed && !a.PhysicalWeakAngleDerived && !a.FineStructureDerived && !a.PhysicalMassesDerived && !a.PhysicalScaleDerived, Detail: FormatSummary(a.Summary) + " :: " + a.TruthStatement},
		}}
	}}
}
