// Package eftdecayportal implements Gate 222: EFT decay portal construction /
// RelicDecaySeal activation audit.
//
// Gate 221 proved that the sealed PeV carriers are cosmologically pathological
// unless a legal decay portal is supplied. Gate 222 does not pretend that such
// portals are generated by the finite Clifford/G2 core. It asks a narrower EFT
// question: which gauge-invariant phenomenological operators would be required
// to make the carriers decay before BBN, and can the full PeV spectrum receive
// a RelicDecaySeal without violating the existing leptoquark, carrier, matching,
// and threshold-spectrum firewalls?
//
// Important correction: the sealed colored carrier (8,2,Y=1/2) is not identical
// to the SM quark doublet Q=(3,2,Y=1/6). A simple mass-mixing portal with Q is
// therefore rejected. The electroweak triplet admits a standard renormalizable
// lepton-Higgs portal, but that only rescues the colorless triplet. The colored
// octet still lacks a certified pure-SM decay portal in the audited basis, so
// the full RelicDecaySeal is not granted by this gate.
package eftdecayportal

import (
	"fmt"
	"math"
	"strings"
	"sync"

	"github.com/bagherbal/asha-engine/pkg/bridge/heavycarrierdecayaudit"
)

const (
	StatusPartialPortalOnly        = "PARTIAL_EFT_PORTAL_SUPPORT_TRIPLET_ONLY"
	StatusFullRelicSealNotGranted  = "RELIC_DECAY_SEAL_NOT_GRANTED_FULL_SPECTRUM"
	StatusColoredPortalObstruction = "FAILED_ROUTE_COLORED_OCTET_DECAY_PORTAL"
	DecayPortalAuditID             = "GATE222-EFT-DECAY-PORTAL-RELIC-SEAL-ACTIVATION-AUDIT"

	hbarGeVS   = 6.582119569e-25
	bbnSeconds = 1.0
	eightPi    = 8.0 * math.Pi
)

type Gate221Snapshot struct {
	Gate221Inherited             bool
	FatalCosmologicalPathology   bool
	RelicDecaySealRequired       bool
	RelicDecaySealGranted        bool
	ThresholdSpectrumSealActive  bool
	MatchingCorrectionSealActive bool
	EmpiricalCarrierSealActive   bool
	LeptoquarkDynamicsSealActive bool
	MBGeV                        float64
	RequiredWidthGeV             float64
	TruthStatement               string
}

type SMField struct {
	Name           string
	Representation string
	Color          string
	Weak           string
	Hypercharge    string
	Fermion        bool
}

type EFTPortalCandidate struct {
	Name                             string
	TargetCarrier                    string
	SymbolicForm                     string
	Dimension                        int
	GaugeInvariant                   bool
	LorentzStructureAccepted         bool
	PureSMFinalStates                bool
	ViolatesLeptoquarkSeal           bool
	FiniteGenerated                  bool
	RequiresPhenomenologicalCoupling bool
	WidthFormula                     string
	BBNParameterName                 string
	BBNParameterBound                float64
	BoundDirection                   string
	SealEligible                     bool
	Verdict                          string
}

type GaugeInvariantOperatorAudit struct {
	SMFields                 []SMField
	Candidates               []EFTPortalCandidate
	CandidatesAudited        int
	GaugeInvariantCandidates int
	SealEligibleCandidates   int
	TripletPortalFound       bool
	OctetMassMixingRejected  bool
	OctetPureSMPortalFound   bool
	OctetPortalObstructed    bool
	FullSpectrumPortalFound  bool
	Verdict                  string
}

type BBNKinematicsAudit struct {
	MBGeV                           float64
	BBNThresholdSeconds             float64
	RequiredWidthGeV                float64
	TripletYukawaMin                float64
	UnitWilsonDim6LambdaMaxGeV      float64
	UnitWilsonDim5LambdaMaxGeV      float64
	TripletCanPassBBNUnderSeal      bool
	OctetCanPassBBNUnderSeal        bool
	FullSpectrumCanPassBBNUnderSeal bool
	Verdict                         string
}

type RelicDecaySealActivationAudit struct {
	SealName                 string
	SealRequested            bool
	SealGranted              bool
	PartialTripletSubseal    bool
	FullSpectrumDeniedReason string
	QuarantinedInputs        []string
	RequiredFutureData       []string
	OperationalStatus        string
	Verdict                  string
}

type FirewallAudit struct {
	Gate221Inherited             bool
	ThresholdSpectrumSealActive  bool
	MatchingCorrectionSealActive bool
	EmpiricalCarrierSealActive   bool
	LeptoquarkDynamicsSealActive bool
	NativeOperatorClaimed        bool
	OctetQMixingClaimed          bool
	ArbitraryCouplingFixed       bool
	RelicAbundanceComputed       bool
	ProtonSealViolated           bool
	BBNUsedAsFilterOnly          bool
	FiniteCorePolluted           bool
	RecommendedNextGate          string
	RemainingUnknowns            []string
	Verdict                      string
}

type CosmologyRescueSummary struct {
	TripletRescuedByEFTPortal bool
	ColoredOctetRescued       bool
	FullSpectrumRelicSafe     bool
	FatalPathologyCleared     bool
	Status                    string
	NextGate                  string
	Comment                   string
}

type Analysis struct {
	Gate221         Gate221Snapshot
	Gate221Analysis heavycarrierdecayaudit.Analysis
	Operators       GaugeInvariantOperatorAudit
	Kinematics      BBNKinematicsAudit
	RelicSeal       RelicDecaySealActivationAudit
	Summary         CosmologyRescueSummary
	Firewall        FirewallAudit
	TruthStatement  string
}

var (
	defaultOnce sync.Once
	defaultA    Analysis
	defaultErr  error
)

func BuildDefault() (Analysis, error) {
	defaultOnce.Do(func() {
		g221, err := heavycarrierdecayaudit.BuildDefault()
		if err != nil {
			defaultErr = fmt.Errorf("build Gate 221 input: %w", err)
			return
		}
		defaultA, defaultErr = Build(g221)
	})
	return defaultA, defaultErr
}

func Build(g221 heavycarrierdecayaudit.Analysis) (Analysis, error) {
	snap := snapshotFromGate221(g221)
	if !snap.Gate221Inherited || !snap.FatalCosmologicalPathology || !snap.RelicDecaySealRequired {
		return Analysis{}, fmt.Errorf("Gate 222 requires Gate 221 cosmological pathology and ungranted RelicDecaySeal")
	}
	operators := auditGaugeInvariantOperators(snap)
	kin := auditBBNKinematics(snap, operators)
	seal := auditRelicDecaySealActivation(operators, kin)
	summary := summarize(operators, kin, seal)
	firewall := auditFirewall(snap)
	truth := buildTruth(snap, operators, kin, seal, summary)
	return Analysis{Gate221: snap, Gate221Analysis: g221, Operators: operators, Kinematics: kin, RelicSeal: seal, Summary: summary, Firewall: firewall, TruthStatement: truth}, nil
}

func snapshotFromGate221(a heavycarrierdecayaudit.Analysis) Gate221Snapshot {
	return Gate221Snapshot{
		Gate221Inherited:             a.Summary.Status == heavycarrierdecayaudit.StatusFailedCosmologicalPathology,
		FatalCosmologicalPathology:   a.Summary.FatalPathology,
		RelicDecaySealRequired:       a.RelicSeal.SealRequired,
		RelicDecaySealGranted:        a.RelicSeal.SealGranted,
		ThresholdSpectrumSealActive:  a.Firewall.ThresholdSpectrumSealActive,
		MatchingCorrectionSealActive: a.Firewall.MatchingCorrectionSealActive,
		EmpiricalCarrierSealActive:   a.Firewall.EmpiricalCarrierSealActive,
		LeptoquarkDynamicsSealActive: a.Firewall.LeptoquarkDynamicsSealActive,
		MBGeV:                        a.Gate220.MBGeV,
		RequiredWidthGeV:             a.Lifetime.RequiredWidthGeV,
		TruthStatement:               a.TruthStatement,
	}
}

func smFields() []SMField {
	return []SMField{
		{Name: "Q", Representation: "(3,2,Y=1/6)", Color: "3", Weak: "2", Hypercharge: "1/6", Fermion: true},
		{Name: "u^c", Representation: "(3bar,1,Y=-2/3)", Color: "3bar", Weak: "1", Hypercharge: "-2/3", Fermion: true},
		{Name: "d^c", Representation: "(3bar,1,Y=1/3)", Color: "3bar", Weak: "1", Hypercharge: "1/3", Fermion: true},
		{Name: "L", Representation: "(1,2,Y=-1/2)", Color: "1", Weak: "2", Hypercharge: "-1/2", Fermion: true},
		{Name: "e^c", Representation: "(1,1,Y=1)", Color: "1", Weak: "1", Hypercharge: "1", Fermion: true},
		{Name: "H", Representation: "(1,2,Y=1/2)", Color: "1", Weak: "2", Hypercharge: "1/2", Fermion: false},
		{Name: "H†", Representation: "(1,2,Y=-1/2)", Color: "1", Weak: "2", Hypercharge: "-1/2", Fermion: false},
	}
}

func auditGaugeInvariantOperators(snap Gate221Snapshot) GaugeInvariantOperatorAudit {
	fields := smFields()
	yMin := tripletYukawaMin(snap.MBGeV, snap.RequiredWidthGeV)
	lambda6 := lambdaDim6Max(snap.MBGeV, snap.RequiredWidthGeV)
	candidates := []EFTPortalCandidate{
		{
			Name:                             "triplet lepton-Higgs Yukawa portal",
			TargetCarrier:                    "Dirac (1,3,Y=1)",
			SymbolicForm:                     "y_T Ψ_3^a (L σ^a H†) + h.c.",
			Dimension:                        4,
			GaugeInvariant:                   true,
			LorentzStructureAccepted:         true,
			PureSMFinalStates:                true,
			ViolatesLeptoquarkSeal:           false,
			FiniteGenerated:                  false,
			RequiresPhenomenologicalCoupling: true,
			WidthFormula:                     "Γ ≈ |y_T|² M_B/(8π)",
			BBNParameterName:                 "|y_T|",
			BBNParameterBound:                yMin,
			BoundDirection:                   ">",
			SealEligible:                     true,
			Verdict:                          "gauge invariant and BBN-safe for an extremely small sealed Yukawa; not finite-derived",
		},
		{
			Name:                             "octet simple Q mass-mixing portal",
			TargetCarrier:                    "Dirac (8,2,Y=1/2)",
			SymbolicForm:                     "m_mix Ψ_8 Q + h.c.",
			Dimension:                        3,
			GaugeInvariant:                   false,
			LorentzStructureAccepted:         true,
			PureSMFinalStates:                true,
			ViolatesLeptoquarkSeal:           false,
			FiniteGenerated:                  false,
			RequiresPhenomenologicalCoupling: true,
			WidthFormula:                     "not legal",
			BBNParameterName:                 "m_mix",
			BoundDirection:                   "not applicable",
			SealEligible:                     false,
			Verdict:                          "rejected: Ψ_8=(8,2,1/2) is not Q=(3,2,1/6); color and hypercharge do not match",
		},
		{
			Name:                             "octet color-current EFT portal through pure SM fields",
			TargetCarrier:                    "Dirac (8,2,Y=1/2)",
			SymbolicForm:                     "Ψ_8 × SM fermions/scalars with dimension ≤ 6",
			Dimension:                        6,
			GaugeInvariant:                   false,
			LorentzStructureAccepted:         false,
			PureSMFinalStates:                true,
			ViolatesLeptoquarkSeal:           false,
			FiniteGenerated:                  false,
			RequiresPhenomenologicalCoupling: true,
			WidthFormula:                     "if a legal dim-6 portal existed: Γ ~ M_B⁵/(192π³Λ⁴)",
			BBNParameterName:                 "Λ_EFT/c^(1/2)",
			BBNParameterBound:                lambda6,
			BoundDirection:                   "< (diagnostic only; operator not certified)",
			SealEligible:                     false,
			Verdict:                          "no audited pure-SM dimension≤6 operator simultaneously supplies color singlet, electroweak singlet, hypercharge zero, and Lorentz scalar structure",
		},
		{
			Name:                             "leptoquark-assisted colored decay portal",
			TargetCarrier:                    "Dirac (8,2,Y=1/2)",
			SymbolicForm:                     "Ψ_8 qℓq/Λ² through dormant u(4) leptoquark slots",
			Dimension:                        6,
			GaugeInvariant:                   true,
			LorentzStructureAccepted:         false,
			PureSMFinalStates:                true,
			ViolatesLeptoquarkSeal:           true,
			FiniteGenerated:                  false,
			RequiresPhenomenologicalCoupling: true,
			WidthFormula:                     "blocked by seal",
			BBNParameterName:                 "Λ_EFT",
			BoundDirection:                   "not applicable",
			SealEligible:                     false,
			Verdict:                          "blocked by LeptoquarkDynamicsSeal; dormant u(4) slots cannot be used as propagators or Wilson coefficients",
		},
	}
	gaugeInv := 0
	eligible := 0
	triplet := false
	octetMixRejected := false
	octetPureSM := false
	octetBlocked := true
	for _, c := range candidates {
		if c.GaugeInvariant && !c.ViolatesLeptoquarkSeal {
			gaugeInv++
		}
		if c.SealEligible {
			eligible++
			if c.TargetCarrier == "Dirac (1,3,Y=1)" {
				triplet = true
			}
		}
		if c.Name == "octet simple Q mass-mixing portal" && !c.GaugeInvariant {
			octetMixRejected = true
		}
		if c.TargetCarrier == "Dirac (8,2,Y=1/2)" && c.GaugeInvariant && c.LorentzStructureAccepted && !c.ViolatesLeptoquarkSeal && c.PureSMFinalStates {
			octetPureSM = true
			octetBlocked = false
		}
	}
	return GaugeInvariantOperatorAudit{SMFields: fields, Candidates: candidates, CandidatesAudited: len(candidates), GaugeInvariantCandidates: gaugeInv, SealEligibleCandidates: eligible, TripletPortalFound: triplet, OctetMassMixingRejected: octetMixRejected, OctetPureSMPortalFound: octetPureSM, OctetPortalObstructed: octetBlocked, FullSpectrumPortalFound: triplet && octetPureSM, Verdict: "Gate 222 finds a sealed triplet lepton-Higgs Yukawa portal, but rejects the false octet-Q mass-mixing claim and finds no certified pure-SM octet decay portal through dimension 6"}
}

func auditBBNKinematics(snap Gate221Snapshot, op GaugeInvariantOperatorAudit) BBNKinematicsAudit {
	yMin := tripletYukawaMin(snap.MBGeV, snap.RequiredWidthGeV)
	lambda6 := lambdaDim6Max(snap.MBGeV, snap.RequiredWidthGeV)
	lambda5 := lambdaDim5Max(snap.MBGeV, snap.RequiredWidthGeV)
	triplet := op.TripletPortalFound && yMin > 0
	octet := op.OctetPureSMPortalFound
	return BBNKinematicsAudit{MBGeV: snap.MBGeV, BBNThresholdSeconds: bbnSeconds, RequiredWidthGeV: snap.RequiredWidthGeV, TripletYukawaMin: yMin, UnitWilsonDim6LambdaMaxGeV: lambda6, UnitWilsonDim5LambdaMaxGeV: lambda5, TripletCanPassBBNUnderSeal: triplet, OctetCanPassBBNUnderSeal: octet, FullSpectrumCanPassBBNUnderSeal: triplet && octet, Verdict: fmt.Sprintf("triplet BBN safety would require |y_T| > %.6g; a hypothetical unit-Wilson dimension-6 width would require Λ < %.6g GeV, but no such octet operator is certified", yMin, lambda6)}
}

func auditRelicDecaySealActivation(op GaugeInvariantOperatorAudit, kin BBNKinematicsAudit) RelicDecaySealActivationAudit {
	granted := op.FullSpectrumPortalFound && kin.FullSpectrumCanPassBBNUnderSeal
	partial := op.TripletPortalFound && kin.TripletCanPassBBNUnderSeal
	status := StatusFullRelicSealNotGranted
	verdict := "full RelicDecaySeal is denied because the colored octet remains without a legal pure-SM decay portal"
	if granted {
		status = "RELIC_DECAY_SEAL_GRANTED"
		verdict = "full RelicDecaySeal granted for the sealed EFT portals"
	}
	return RelicDecaySealActivationAudit{
		SealName:                 "RelicDecaySeal",
		SealRequested:            true,
		SealGranted:              granted,
		PartialTripletSubseal:    partial,
		FullSpectrumDeniedReason: "Dirac (8,2,Y=1/2) is not SM-Q-like; simple mass mixing fails and no certified dimension≤6 pure-SM decay portal survives the audit",
		QuarantinedInputs:        []string{"triplet Yukawa y_T if a future partial seal is used", "any future octet Wilson coefficient", "any future octet suppression scale Λ_EFT", "heavy-light Lorentz contractions", "BBN lifetime bound"},
		RequiredFutureData:       []string{"gauge-invariant octet decay operator", "Lorentz scalar contraction", "pure-SM final state or explicitly sealed new mediator", "Wilson coefficient or Λ_EFT", "Γ_octet with τ < 1 second"},
		OperationalStatus:        status,
		Verdict:                  verdict,
	}
}

func summarize(op GaugeInvariantOperatorAudit, kin BBNKinematicsAudit, seal RelicDecaySealActivationAudit) CosmologyRescueSummary {
	return CosmologyRescueSummary{TripletRescuedByEFTPortal: op.TripletPortalFound && kin.TripletCanPassBBNUnderSeal, ColoredOctetRescued: op.OctetPureSMPortalFound && kin.OctetCanPassBBNUnderSeal, FullSpectrumRelicSafe: seal.SealGranted, FatalPathologyCleared: seal.SealGranted, Status: StatusPartialPortalOnly + "; " + StatusColoredPortalObstruction + "; " + StatusFullRelicSealNotGranted, NextGate: "Gate 223 — colored-octet decay portal alternatives / spectrum replacement audit", Comment: "The colorless triplet can be rescued by a sealed lepton-Higgs Yukawa, but the PeV spectrum as a whole remains cosmologically unsafe until the colored octet obtains a legal decay portal."}
}

func auditFirewall(snap Gate221Snapshot) FirewallAudit {
	return FirewallAudit{Gate221Inherited: snap.Gate221Inherited, ThresholdSpectrumSealActive: snap.ThresholdSpectrumSealActive, MatchingCorrectionSealActive: snap.MatchingCorrectionSealActive, EmpiricalCarrierSealActive: snap.EmpiricalCarrierSealActive, LeptoquarkDynamicsSealActive: snap.LeptoquarkDynamicsSealActive, NativeOperatorClaimed: false, OctetQMixingClaimed: false, ArbitraryCouplingFixed: false, RelicAbundanceComputed: false, ProtonSealViolated: false, BBNUsedAsFilterOnly: true, FiniteCorePolluted: false, RecommendedNextGate: "Gate 223 — colored-octet decay portal alternatives / spectrum replacement audit", RemainingUnknowns: []string{"colored-octet decay operator", "octet Wilson coefficient or new mediator", "Boltzmann/relic abundance after legal full decay sector", "mass splitting/cascade details", "finite origin of any decay portal"}, Verdict: "Gate 222 quarantines EFT portals as phenomenology, rejects the false octet-Q mixing claim, and does not pollute the finite core"}
}

func buildTruth(snap Gate221Snapshot, op GaugeInvariantOperatorAudit, kin BBNKinematicsAudit, seal RelicDecaySealActivationAudit, sum CosmologyRescueSummary) string {
	return fmt.Sprintf("Gate 222 audits EFT decay portals for the Gate-221 PeV carriers at M_B=%.9g GeV. It finds a gauge-invariant triplet portal Ψ_3 L H† with |y_T|>%.6g sufficient for τ<1s, but rejects simple octet-Q mass mixing because (8,2,1/2)≠(3,2,1/6) and finds no certified pure-SM octet decay portal through the audited basis. Full RelicDecaySeal is therefore not granted. Status=%s.", snap.MBGeV, kin.TripletYukawaMin, sum.Status)
}

func tripletYukawaMin(m, gammaReq float64) float64 {
	if m <= 0 || gammaReq <= 0 {
		return math.Inf(1)
	}
	return math.Sqrt(eightPi * gammaReq / m)
}

func lambdaDim6Max(m, gammaReq float64) float64 {
	if m <= 0 || gammaReq <= 0 {
		return 0
	}
	// Diagnostic standard four-fermion scaling Γ≈M^5/(192π^3Λ^4) for unit Wilson coefficient.
	return math.Pow(math.Pow(m, 5)/(192.0*math.Pow(math.Pi, 3)*gammaReq), 0.25)
}

func lambdaDim5Max(m, gammaReq float64) float64 {
	if m <= 0 || gammaReq <= 0 {
		return 0
	}
	// Diagnostic magnetic-type scaling Γ≈M^3/(8πΛ^2) for unit Wilson coefficient.
	return math.Sqrt(math.Pow(m, 3) / (eightPi * gammaReq))
}

func FormatGate221(g Gate221Snapshot) string {
	return fmt.Sprintf("gate221=%t fatal=%t sealRequired=%t sealGranted=%t seals=(spectrum %t,matching %t,carrier %t,lq %t) MB=%.9g Γ_BBN>%.9g truth=%q", g.Gate221Inherited, g.FatalCosmologicalPathology, g.RelicDecaySealRequired, g.RelicDecaySealGranted, g.ThresholdSpectrumSealActive, g.MatchingCorrectionSealActive, g.EmpiricalCarrierSealActive, g.LeptoquarkDynamicsSealActive, g.MBGeV, g.RequiredWidthGeV, g.TruthStatement)
}

func FormatSMFields(fields []SMField) string {
	parts := make([]string, 0, len(fields))
	for _, f := range fields {
		parts = append(parts, fmt.Sprintf("%s=%s", f.Name, f.Representation))
	}
	return strings.Join(parts, "; ")
}

func FormatCandidate(c EFTPortalCandidate) string {
	return fmt.Sprintf("%s target=%s dim=%d form=%q gauge=%t lorentz=%t pureSM=%t lqSealViolation=%t finite=%t phenCoupling=%t bound=%s %s %.9g sealEligible=%t :: %s", c.Name, c.TargetCarrier, c.Dimension, c.SymbolicForm, c.GaugeInvariant, c.LorentzStructureAccepted, c.PureSMFinalStates, c.ViolatesLeptoquarkSeal, c.FiniteGenerated, c.RequiresPhenomenologicalCoupling, c.BBNParameterName, c.BoundDirection, c.BBNParameterBound, c.SealEligible, c.Verdict)
}

func FormatOperatorAudit(a GaugeInvariantOperatorAudit) string {
	names := make([]string, 0, len(a.Candidates))
	for _, c := range a.Candidates {
		names = append(names, c.Name+":"+c.Verdict)
	}
	return fmt.Sprintf("SM=[%s] audited=%d gaugeInvariant=%d eligible=%d triplet=%t octetMixRejected=%t octetPureSM=%t octetBlocked=%t full=%t :: %s", FormatSMFields(a.SMFields), a.CandidatesAudited, a.GaugeInvariantCandidates, a.SealEligibleCandidates, a.TripletPortalFound, a.OctetMassMixingRejected, a.OctetPureSMPortalFound, a.OctetPortalObstructed, a.FullSpectrumPortalFound, strings.Join(names, " | "))
}

func FormatKinematics(k BBNKinematicsAudit) string {
	return fmt.Sprintf("MB=%.9g BBN<%.9g s Γreq>%.9g GeV yTmin=%.9g Λ6max(unit)=%.9g GeV Λ5max(unit)=%.9g GeV pass=(triplet %t,octet %t,full %t) :: %s", k.MBGeV, k.BBNThresholdSeconds, k.RequiredWidthGeV, k.TripletYukawaMin, k.UnitWilsonDim6LambdaMaxGeV, k.UnitWilsonDim5LambdaMaxGeV, k.TripletCanPassBBNUnderSeal, k.OctetCanPassBBNUnderSeal, k.FullSpectrumCanPassBBNUnderSeal, k.Verdict)
}

func FormatRelicSeal(s RelicDecaySealActivationAudit) string {
	return fmt.Sprintf("seal=%s requested=%t granted=%t partialTriplet=%t status=%s denied=%q quarantined=[%s] future=[%s] :: %s", s.SealName, s.SealRequested, s.SealGranted, s.PartialTripletSubseal, s.OperationalStatus, s.FullSpectrumDeniedReason, strings.Join(s.QuarantinedInputs, "; "), strings.Join(s.RequiredFutureData, "; "), s.Verdict)
}

func FormatSummary(s CosmologyRescueSummary) string {
	return fmt.Sprintf("rescued=(triplet %t,octet %t,full %t) cleared=%t status=%s next=%q :: %s", s.TripletRescuedByEFTPortal, s.ColoredOctetRescued, s.FullSpectrumRelicSafe, s.FatalPathologyCleared, s.Status, s.NextGate, s.Comment)
}

func FormatFirewall(f FirewallAudit) string {
	return fmt.Sprintf("gate221=%t seals=(spectrum %t,matching %t,carrier %t,lq %t) nativeClaim=%t octetQMixingClaim=%t couplingFixed=%t relic=%t protonSealViolated=%t BBNfilter=%t finitePolluted=%t next=%q", f.Gate221Inherited, f.ThresholdSpectrumSealActive, f.MatchingCorrectionSealActive, f.EmpiricalCarrierSealActive, f.LeptoquarkDynamicsSealActive, f.NativeOperatorClaimed, f.OctetQMixingClaimed, f.ArbitraryCouplingFixed, f.RelicAbundanceComputed, f.ProtonSealViolated, f.BBNUsedAsFilterOnly, f.FiniteCorePolluted, f.RecommendedNextGate)
}
