package spectralaction

import (
	"fmt"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func FiniteSpectralActionPrincipleSpectralTripleConstructionAuditTheorem() theorem.Theorem {
	const id = "BRIDGE-FINITE-SPECTRAL-ACTION-TRIPLE-FIREWALL"
	const name = "Finite spectral action principle / spectral triple construction audit"
	return theorem.Theorem{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build finite spectral action audit", Passed: false, Detail: err.Error()}}}
		}
		return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: []theorem.Check{
			{Name: "Gate 162 finite-zeta firewall is inherited", Passed: a.Previous.BetaPermissionFirewallClosed && a.Previous.ContactZetaValues == 5 && a.Previous.FiniteZetaPoleCount == 0 && !a.Previous.AnalyticContinuationNeeded && !a.Previous.SpectralTripleComplete && !a.Previous.CanonicalCutoffSelected && a.Previous.GaugeKineticMapRows == 0 && a.Previous.ContactBetaRowsAllowed == 0 && a.Previous.BoundaryConstraintsDerived == 0 && !a.Previous.HiddenObservedInputUsed, Detail: fmt.Sprintf("zeta=%d poles=%d analytic=%t triple=%t cutoff=%t gaugeRows=%d beta=%d constraints=%d hiddenObserved=%t", a.Previous.ContactZetaValues, a.Previous.FiniteZetaPoleCount, a.Previous.AnalyticContinuationNeeded, a.Previous.SpectralTripleComplete, a.Previous.CanonicalCutoffSelected, a.Previous.GaugeKineticMapRows, a.Previous.ContactBetaRowsAllowed, a.Previous.BoundaryConstraintsDerived, a.Previous.HiddenObservedInputUsed)},
			{Name: "exact spectral pre-data are available", Passed: a.FiniteSpectralPreData && a.ContactRows == 7 && a.ContactZetaValues == 5 && a.ExactRationalOverlapMatrix && a.ExactCharacteristicCertified && a.ExactRootIsolationCertified && a.PositiveNonzeroSpectrumRows == 7 && a.FiniteZetaPoleCount == 0 && !a.AnalyticContinuationNeeded && a.GaloisInvariantOrbits == 4 && a.RationalSingletonRows == 3 && a.QuarticOrbitRows == 4 && a.QuarticCollectiveBlocks == 1, Detail: FormatSummary(a.Summary)},
			{Name: "spectral-triple axiom audit is incomplete", Passed: a.AxiomAudit.IngredientsAudited == 11 && a.AxiomAudit.AvailableIngredients == 4 && a.AxiomAudit.CanonicalIngredients == 3 && a.AxiomAudit.RequiredIngredients == 11 && a.AxiomAudit.MissingRequiredCanonical == 8 && a.AxiomAudit.FiniteAlgebraAvailable && a.AxiomAudit.FiniteHilbertCandidate && a.AxiomAudit.ContactZetaLedgerAvailable && a.AxiomAudit.ContactOverlapAvailable && !a.AxiomAudit.AlgebraRepresentationReady && !a.AxiomAudit.FiniteDiracSelected && !a.AxiomAudit.RealStructureSelected && !a.AxiomAudit.GradingSelected && !a.AxiomAudit.OrderOneCalculusVerified && !a.AxiomAudit.OrientabilityVerified && !a.AxiomAudit.PoincareDualityVerified && !a.AxiomAudit.KOCompatibilityVerified && !a.AxiomAudit.CanonicalCutoffSelected && !a.AxiomAudit.GaugeFluctuationMapDerived && !a.AxiomAudit.SpectralTripleComplete, Detail: FormatAxiomAudit(a.AxiomAudit) + " :: " + FormatIngredientList(a.Ingredients)},
			{Name: "Dirac-like candidates are diagnostics, not selected spectral-triple D", Passed: a.DiracAudit.CandidatesAudited == 5 && a.DiracAudit.ExactCandidates == 5 && a.DiracAudit.SelfAdjointCandidates == 5 && a.DiracAudit.FiniteSpectrumCandidates == 5 && a.DiracAudit.GaloisInvariantCandidates == 5 && a.DiracAudit.BranchFreeCandidates == 5 && !a.DiracAudit.ObservedInputsUsed && a.DiracAudit.BranchChoicesUsed == 0 && a.DiracAudit.NeedRepresentation == 5 && a.DiracAudit.NeedRealStructure == 5 && a.DiracAudit.NeedGrading == 5 && a.DiracAudit.NeedOrderOneCalculus == 5 && a.DiracAudit.NeedGaugeFluctuationMap == 5 && a.DiracAudit.OrderOneVerified == 0 && a.DiracAudit.PromotableCandidates == 0 && a.DiracAudit.GaugeKineticMapsDerived == 0 && a.DiracAudit.CanonicalActionCoefficients == 0 && a.DiracAudit.BetaRowsAllowed == 0 && !a.DiracAudit.PhysicalConstantsDerived, Detail: FormatDiracAudit(a.DiracAudit) + " :: " + FormatDiracList(a.DiracCandidates)},
			{Name: "spectral-action ansatzes remain formal", Passed: a.ActionAudit.AnsatzesAudited == 5 && a.ActionAudit.UsingZetaLedger == 5 && a.ActionAudit.ExactAnsatzes == 5 && a.ActionAudit.GaloisInvariantAnsatzes == 5 && a.ActionAudit.BranchFreeAnsatzes == 5 && !a.ActionAudit.ObservedInputsUsed && a.ActionAudit.BranchChoicesUsed == 0 && a.ActionAudit.NeedCutoffFunction == 5 && a.ActionAudit.NeedTestFunction == 5 && a.ActionAudit.NeedDiracOperator == 5 && a.ActionAudit.NeedGaugeRepresentation == 5 && a.ActionAudit.CanonicalCoefficients == 0 && a.ActionAudit.GaugeKineticRows == 0 && a.ActionAudit.BoundaryConstraintsDerived == 0 && a.ActionAudit.ThresholdBetaRows == 0 && !a.ActionAudit.PhysicalConstantsDerived, Detail: FormatActionAudit(a.ActionAudit) + " :: " + FormatActionAnsatzList(a.ActionAnsatzes)},
			{Name: "spectral-action firewall preserves beta and physical constants", Passed: a.Firewall.Gate162Inherited && !a.Firewall.SpectralTripleComplete && !a.Firewall.FiniteDiracSelected && !a.Firewall.RealStructureSelected && !a.Firewall.GradingSelected && !a.Firewall.CanonicalCutoffSelected && !a.Firewall.GaugeFluctuationMapDerived && a.Firewall.GaugeKineticMapRows == 0 && a.Firewall.IndividualQuarticRows == 0 && a.Firewall.GaugeRepresentationRows == 0 && a.Firewall.LocalFieldRows == 0 && a.Firewall.MassActivationRows == 0 && a.Firewall.DecouplingRows == 0 && a.Firewall.DynkinIndexRows == 0 && a.Firewall.ThresholdBetaRows == 0 && a.Firewall.ProvenZeroRows == 0 && a.Firewall.BoundaryConstraintsDerived == 0 && !a.Firewall.PhysicalConstantsDerived && a.Firewall.BetaPermissionFirewallClosed, Detail: FormatFirewall(a.Firewall)},
			{Name: "physical bridge remains sealed with nullity unchanged", Passed: !a.SpectralTripleComplete && !a.SpectralActionPrincipleReady && !a.FiniteDiracSelected && !a.RealStructureSelected && !a.GradingSelected && !a.OrderOneCalculusVerified && !a.OrientabilityVerified && !a.PoincareDualityVerified && !a.KOCompatibilityVerified && !a.CanonicalCutoffSelected && !a.GaugeFluctuationMapDerived && a.GaugeKineticMapRows == 0 && a.IndividualQuarticRows == 0 && a.CanonicalQuarticBranches == 0 && a.GaugeRepresentationRows == 0 && a.SpinStatisticsRows == 0 && a.LocalFieldRows == 0 && a.MassActivationRows == 0 && a.DecouplingRows == 0 && a.DynkinIndexRows == 0 && a.ThresholdBetaRows == 0 && a.ProvenZeroRows == 0 && a.BoundaryConstraintsDerived == 0 && a.ContactBetaRowsAllowed == 0 && a.ContactZeroRowsProved == 0 && a.BetaPermissionFirewallClosed && !a.ThresholdCorrectedBeta && !a.FullBetaMatchingTensor && a.ResidualNullityBefore == 3 && a.ResidualNullityAfter == 3 && !a.HiddenObservedInputUsed && !a.PhysicalWeakAngleDerived && !a.FineStructureDerived && !a.PhysicalMassesDerived && !a.PhysicalScaleDerived, Detail: FormatSummary(a.Summary) + " :: " + a.TruthStatement},
		}}
	}}
}
