package generation2historydefectreadoutfunctionalselectionaudit

import (
	"math"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2HistoryDefectReadoutFunctionalSelectionAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 698 — History Defect Readout Functional Selection Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 698 — History Defect Readout Functional Selection Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate697 boundary quotient payoff", Passed: a.Inherited.BoundaryQuotientPayoffInherited && strings.Contains(a.Inherited.BoundaryPayoff, "sigma_boundary") && math.Abs(a.Inherited.BoundaryPayoffValue-(lambdaLambda12+r3Minus1)) < tolerance && a.Inherited.BoundaryPayoffDescends && a.Inherited.ResponseOperator == "R_split=sigma_boundary(b)P_K7" && a.Inherited.Rho72 == "rho_72=I_H72/72" && a.Inherited.NoNativePayoffCoupling && a.Inherited.NoNativeHistoryResponse && a.Inherited.NoNativeSevenOver72 && a.Inherited.Verdict == StatusGate697BoundaryQuotientPayoffInherited, Detail: FormatInheritance(a.Inherited)},
			{Name: "define history closure wall", Passed: a.ClosureWall.WallEquation == "kappa_lambda+kappa_e+lambda=0" && strings.Contains(a.ClosureWall.EquivalentPositiveClosure, "lambda<0") && math.Abs(a.ClosureWall.KappaLambda-kappaLambda) < tolerance && math.Abs(a.ClosureWall.KappaE-kappaE) < tolerance && math.Abs(a.ClosureWall.Lambda-lambdaLambda12) < tolerance && a.ClosureWall.LambdaNegative && math.Abs(a.ClosureWall.ClosureDefect-a.Readout.DBase) < tolerance && !a.ClosureWall.WallSatisfied && a.ClosureWall.Verdict == StatusHistoryClosureWallDefined, Detail: FormatClosureWall(a.ClosureWall)},
			{Name: "define sigma_history readout", Passed: strings.Contains(a.Readout.SigmaDefinition, "kappa_lambda+kappa_e+lambda") && a.Readout.InputSpace == "H_history=span(kappa_lambda,kappa_e,lambda)" && a.Readout.InputVector == [3]float64{kappaLambda, kappaE, lambdaLambda12} && a.Readout.DBaseExpression == "D_base=kappa_lambda+kappa_e+lambda(Lambda_12)" && math.Abs(a.Readout.DBase-(kappaLambda+kappaE+lambdaLambda12)) < tolerance && a.Readout.MatchesInheritedDBase && a.Readout.MeasuresClosureDefect && strings.Contains(a.Readout.Verdict, StatusSigmaHistoryReadoutDefined) && strings.Contains(a.Readout.Verdict, StatusDBaseIdentifiedAsHistoryDefectQuotient), Detail: FormatReadout(a.Readout)},
			{Name: "audit alternative history readouts", Passed: len(a.Alternatives.Alternatives) == 6 && a.Alternatives.KSumRejected && a.Alternatives.LambdaOnlyRejected && a.Alternatives.KappaLambdaOnlyRejected && a.Alternatives.KappaEOnlyRejected && a.Alternatives.AbsoluteFormEquivalent && a.Alternatives.SignedFormAccepted && a.Alternatives.AllAudited && a.Alternatives.Verdict == StatusAlternativeHistoryReadoutsAudited, Detail: FormatAlternatives(a.Alternatives)},
			{Name: "prefer signed scalar wall form", Passed: a.SignAudit.LambdaNegative && a.SignAudit.SignedForm == "kappa_lambda+kappa_e+lambda" && a.SignAudit.AbsoluteForm == "kappa_lambda+kappa_e-|lambda|" && math.Abs(a.SignAudit.DBaseSigned-a.SignAudit.DBaseAbsolute) < tolerance && a.SignAudit.FormsEquivalentNumerically && a.SignAudit.SignedFormPreferred && a.SignAudit.OrientationPreserved && a.SignAudit.Verdict == StatusSignedScalarWallFormPreferred, Detail: FormatSignAudit(a.SignAudit)},
			{Name: "reconstruct full bridge as quotient-to-expectation equation", Passed: strings.Contains(a.Bridge.LeftSide, "sigma_history") && strings.Contains(a.Bridge.RightSide, "sigma_boundary") && strings.Contains(a.Bridge.ExpandedEquation, "I_H72/72") && math.Abs(a.Bridge.SigmaHistory-a.Readout.DBase) < tolerance && math.Abs(a.Bridge.SigmaBoundaryExpectation-a.Inherited.Expectation) < tolerance && math.Abs(a.Bridge.ResidualE1-a.Inherited.ResidualE1) < 1e-17 && a.Bridge.MatchesInheritedResidual && a.Bridge.RelatesQuotientToPayoff && strings.Contains(a.Bridge.Verdict, StatusFullBridgeReconstructedAsQuotientExpectation), Detail: FormatBridge(a.Bridge)},
			{Name: "retain residual status without promotion", Passed: math.Abs(a.Residual.ResidualE1-a.Inherited.ResidualE1) < 1e-17 && a.Residual.QuadraticClueRetained && !a.Residual.QuadraticCluePromoted && !a.Residual.NativeResidualExplanation, Detail: FormatResidual(a.Residual)},
			{Name: "classify source types", Passed: strings.Contains(a.SourceTypes.KappaLambdaRole, "scalar") && strings.Contains(a.SourceTypes.KappaERole, "flavor") && strings.Contains(a.SourceTypes.LambdaRole, "signed") && strings.Contains(a.SourceTypes.DBaseRole, "closure-defect") && strings.Contains(a.SourceTypes.SSplitRole, "boundary") && strings.Contains(a.SourceTypes.Rho72Role, "maximum-entropy") && strings.Contains(a.SourceTypes.PK7Role, "Boolean-octonionic") && a.SourceTypes.Verdict == StatusDBaseCanonicalHistoryClosureDefectReadout, Detail: FormatSourceTypes(a.SourceTypes)},
			{Name: "record missing history-boundary response theorem", Passed: len(a.Missing.Candidates) == 6 && strings.Contains(a.Missing.PreciseGap, "sigma_history") && strings.Contains(a.Missing.PreciseGap, "sigma_boundary") && strings.Contains(a.Missing.Verdict, StatusNoNativeExpectedK7PayoffEqualsHistoryDefect) && strings.Contains(a.Missing.Verdict, StatusNoNativeHistoryBoundaryResponseTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeSevenOver72Theorem), Detail: FormatMissing(a.Missing)},
			{Name: "preserve Gate698 history defect readout firewall", Passed: !a.Firewall.ClaimsExpectedK7PayoffEqualsHistoryDefectNatively && !a.Firewall.ClaimsNativeHistoryBoundaryResponseTheorem && !a.Firewall.ClaimsNativeSevenOver72Theorem && !a.Firewall.ClaimsNativePayoffTheorem && !a.Firewall.ClaimsBoundaryStressDerived && !a.Firewall.ClaimsScalarRGMatching && !a.Firewall.ClaimsHiggsMass && !a.Firewall.ClaimsGaugeUnification && !a.Firewall.ClaimsFlavorDerivation && !a.Firewall.ClaimsCKMPMNS && a.Firewall.Verdict == StatusGate698HistoryDefectReadoutBoundary, Detail: FormatFirewall(a.Firewall)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 698 — History Defect Readout Functional Selection Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
