package generation2scalarsu2provenance

import "github.com/bagherbal/asha-engine/pkg/theorem"

func Generation2ScalarSU2ComplexStructureGaugeOrbitProvenanceAuditTheorem() theorem.Theorem {
	const id = AuditID
	const name = "Generation 2 scalar SU(2)L complex-structure and gauge-orbit provenance audit"
	return theorem.Theorem{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "construct Gate498 scalar SU2 provenance audit", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherits Gate497 bridge gauge quotient", Passed: a.Inheritance.Executed && a.Inheritance.Gate497AuditDefined && a.Inheritance.BridgeGaugeQuotientClosed && a.Inheritance.ResidualS1BridgeGaugeOrbitFound && a.Inheritance.PhotonIsotropyStabilizerConfirmed && a.Inheritance.BrokenGaugeOrbitRankThreeConfirmed && a.Inheritance.RadialModeSeparatedFromGaugeOrbit && a.Inheritance.UnitaryGaugeRepresentativeBridgeValid && a.Inheritance.NativeGaugeOrbitStillOpen && a.Inheritance.NativeDphiStillOpen && a.Inheritance.NoElectroweakFlavorDataImported, Detail: FormatInheritance(a.Inheritance)},
			{Name: "compatible complex-doublet socket exists", Passed: a.ComplexStructure.Executed && a.ComplexStructure.ActiveRealDimension == 4 && a.ComplexStructure.ComplexDoubletDimension == 2 && nearlyZero(a.ComplexStructure.JSkewResidual) && nearlyZero(a.ComplexStructure.JSquarePlusIResidual) && nearlyZero(a.ComplexStructure.ScalarResponseCommJNorm) && a.ComplexStructure.JCompatibleWithPairPlanes && a.ComplexStructure.AbstractComplexDoubletSocket && !a.ComplexStructure.ComplexStructureNativelyUnique, Detail: FormatComplexStructure(a.ComplexStructure)},
			{Name: "abstract SU2 doublet closes", Passed: a.SU2Action.Executed && a.SU2Action.AbstractDoubletRepresentation && nearlyZero(a.SU2Action.SkewResidual) && nearlyZero(a.SU2Action.SU2ClosureResidual) && a.SU2Action.PairDegenerate, Detail: FormatSU2Action(a.SU2Action)},
			{Name: "scalar response selects only pair U1 not full SU2", Passed: a.SU2Action.PairRotationU1Selected && !a.SU2Action.FullSU2SelectedByScalarResponse && !a.SU2Action.FullSU2ActionNativeSelected && a.SU2Action.CommT1Norm > eps && a.SU2Action.CommT2Norm > eps && a.SU2Action.CommT3Norm < eps, Detail: FormatSU2Action(a.SU2Action)},
			{Name: "bridge Goldstone orbit remains consistent but not native", Passed: a.GaugeOrbit.Executed && a.GaugeOrbit.BridgeGoldstoneOrbitConsistent && a.GaugeOrbit.BridgeOrbitRankThreeInherited && a.GaugeOrbit.PhotonStabilizerInherited && a.GaugeOrbit.RadialQuotientModeInherited && a.GaugeOrbit.AbstractSU2NeededForOrbit && !a.GaugeOrbit.NativeSU2Selected && !a.GaugeOrbit.NativeGaugeOrbitSelected && !a.GaugeOrbit.NativeDphiClosed && !a.GaugeOrbit.WZNativeMassPromotionAllowed, Detail: FormatGaugeOrbit(a.GaugeOrbit)},
			{Name: "native boundary remains closed", Passed: a.Boundary.Executed && a.Boundary.ComplexStructureSocketFound && !a.Boundary.ComplexStructureNativelyUnique && a.Boundary.AbstractSU2ClosureConfirmed && !a.Boundary.FullScalarSU2NativeSelected && !a.Boundary.NativeGaugeOrbitSelected && !a.Boundary.NativeDphiClosed && !a.Boundary.NativeScalarKineticMetricClosed && !a.Boundary.NativeKappaSelected && !a.Boundary.NativeGaugeHessianSelected && !a.Boundary.NativeWZMassMatrixDerived, Detail: FormatBoundary(a.Boundary)},
			{Name: "firewall blocks electroweak and flavor promotion", Passed: a.Firewall.Executed && !a.Firewall.ObservedWMassImported && !a.Firewall.ObservedZMassImported && !a.Firewall.ObservedHiggsMassImported && !a.Firewall.FermiConstantImported && !a.Firewall.WeakAngleImported && !a.Firewall.FineStructureImported && !a.Firewall.GaugeCouplingImported && !a.Firewall.HiggsVEVImported && !a.Firewall.YukawaImported && !a.Firewall.CKMPMNSImported && !a.Firewall.NativeComplexStructureWritten && !a.Firewall.NativeScalarSU2Written && !a.Firewall.NativeGaugeOrbitWritten && !a.Firewall.NativeDphiWritten && !a.Firewall.NativeKappaWritten && !a.Firewall.NativeWZMassWritten, Detail: FormatFirewall(a.Firewall)},
		}
		return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: []string{StatusGate497Inherited, StatusAbstractComplexDoubletSocketFound, StatusComplexStructureCompatibleWithPairs, StatusAbstractSU2ClosureConfirmed, StatusPairRotationU1SelectedByScalarResponse, StatusBridgeGoldstoneOrbitRemainsConsistent, StatusFailedFullSU2NotSelectedByScalarResponse, StatusFailedComplexStructureNotNativeUnique, StatusFailedAnisotropicResponseBreaksT1T2, StatusFailedGaugeOrbitStillBridge, StatusFailedNativeDphiStillUnclosed, StatusFailedKappaStillBridge, StatusFailedWZMassStillBlocked, StatusFirewallPreserved, StatusNativeRegistryWriteBlocked, StatusGate499RedirectDefined, a.Truth}}
	}}
}
