package app

import (
	"fmt"

	"github.com/bagherbal/asha-engine/internal/report"
	"github.com/bagherbal/asha-engine/pkg/bridge/abeliancoupling"
	"github.com/bagherbal/asha-engine/pkg/bridge/abelianmixing"
	"github.com/bagherbal/asha-engine/pkg/bridge/actionscale"
	"github.com/bagherbal/asha-engine/pkg/bridge/anomaly"
	"github.com/bagherbal/asha-engine/pkg/bridge/anomalykinetic"
	"github.com/bagherbal/asha-engine/pkg/bridge/betacoeff"
	"github.com/bagherbal/asha-engine/pkg/bridge/betamatching"
	"github.com/bagherbal/asha-engine/pkg/bridge/betapermission"
	"github.com/bagherbal/asha-engine/pkg/bridge/boundaryselector"
	"github.com/bagherbal/asha-engine/pkg/bridge/branchselector"
	"github.com/bagherbal/asha-engine/pkg/bridge/brokenaction"
	"github.com/bagherbal/asha-engine/pkg/bridge/brokengaugefields"
	"github.com/bagherbal/asha-engine/pkg/bridge/brokengeneratornorm"
	"github.com/bagherbal/asha-engine/pkg/bridge/brokenmetric"
	"github.com/bagherbal/asha-engine/pkg/bridge/canonicalaction"
	"github.com/bagherbal/asha-engine/pkg/bridge/canonicalboundary"
	"github.com/bagherbal/asha-engine/pkg/bridge/casimirkernel"
	"github.com/bagherbal/asha-engine/pkg/bridge/chiraltrace"
	"github.com/bagherbal/asha-engine/pkg/bridge/coarsegrain"
	"github.com/bagherbal/asha-engine/pkg/bridge/condensate"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactautaction"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactbundle"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactcohomology"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactembedding"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactfieldmap"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactincidence"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactnaturality"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactpropagator"
	"github.com/bagherbal/asha-engine/pkg/bridge/contactsymmetry"
	"github.com/bagherbal/asha-engine/pkg/bridge/couplingnorm"
	"github.com/bagherbal/asha-engine/pkg/bridge/currentcontact"
	"github.com/bagherbal/asha-engine/pkg/bridge/currentembedding"
	"github.com/bagherbal/asha-engine/pkg/bridge/currenthessian"
	"github.com/bagherbal/asha-engine/pkg/bridge/currentprojection"
	"github.com/bagherbal/asha-engine/pkg/bridge/dualcarrier"
	"github.com/bagherbal/asha-engine/pkg/bridge/dualcoupling"
	"github.com/bagherbal/asha-engine/pkg/bridge/ewcurvature"
	"github.com/bagherbal/asha-engine/pkg/bridge/ewprojection"
	"github.com/bagherbal/asha-engine/pkg/bridge/ewquadratic"
	"github.com/bagherbal/asha-engine/pkg/bridge/exchangeaction"
	"github.com/bagherbal/asha-engine/pkg/bridge/exchangekernel"
	"github.com/bagherbal/asha-engine/pkg/bridge/exchangeselection"
	"github.com/bagherbal/asha-engine/pkg/bridge/fieldmap"
	"github.com/bagherbal/asha-engine/pkg/bridge/fierz"
	"github.com/bagherbal/asha-engine/pkg/bridge/fierzsign"
	"github.com/bagherbal/asha-engine/pkg/bridge/filtration"
	"github.com/bagherbal/asha-engine/pkg/bridge/fourfermion"
	"github.com/bagherbal/asha-engine/pkg/bridge/gapledger"
	"github.com/bagherbal/asha-engine/pkg/bridge/gaugeaction"
	"github.com/bagherbal/asha-engine/pkg/bridge/gaugeeating"
	"github.com/bagherbal/asha-engine/pkg/bridge/gaugehessian"
	"github.com/bagherbal/asha-engine/pkg/bridge/gaugekineticdiag"
	"github.com/bagherbal/asha-engine/pkg/bridge/goldstone"
	"github.com/bagherbal/asha-engine/pkg/bridge/kineticnorm"
	"github.com/bagherbal/asha-engine/pkg/bridge/loopoperator"
	"github.com/bagherbal/asha-engine/pkg/bridge/looppotential"
	"github.com/bagherbal/asha-engine/pkg/bridge/modeclass"
	"github.com/bagherbal/asha-engine/pkg/bridge/o3quotient"
	"github.com/bagherbal/asha-engine/pkg/bridge/propagatorspectrum"
	"github.com/bagherbal/asha-engine/pkg/bridge/protectedconnection"
	"github.com/bagherbal/asha-engine/pkg/bridge/protectedintertwiner"
	"github.com/bagherbal/asha-engine/pkg/bridge/protectedmetric"
	"github.com/bagherbal/asha-engine/pkg/bridge/quotientedcorrespondence"
	"github.com/bagherbal/asha-engine/pkg/bridge/rgfirewall"
	"github.com/bagherbal/asha-engine/pkg/bridge/rgflow"
	"github.com/bagherbal/asha-engine/pkg/bridge/scalarcomplex"
	"github.com/bagherbal/asha-engine/pkg/bridge/scalarcovariant"
	"github.com/bagherbal/asha-engine/pkg/bridge/scalarscale"
	"github.com/bagherbal/asha-engine/pkg/bridge/scalarsu2"
	"github.com/bagherbal/asha-engine/pkg/bridge/scalarvacuum"
	"github.com/bagherbal/asha-engine/pkg/bridge/sectoroperators"
	"github.com/bagherbal/asha-engine/pkg/bridge/sectorspectrum"
	"github.com/bagherbal/asha-engine/pkg/bridge/shellfunctor"
	"github.com/bagherbal/asha-engine/pkg/bridge/threshold"
	"github.com/bagherbal/asha-engine/pkg/bridge/thresholdactivation"
	"github.com/bagherbal/asha-engine/pkg/bridge/thresholdrep"
	"github.com/bagherbal/asha-engine/pkg/bridge/topkernel"
	"github.com/bagherbal/asha-engine/pkg/bridge/u1completion"
	"github.com/bagherbal/asha-engine/pkg/bridge/u1kinetic"
	"github.com/bagherbal/asha-engine/pkg/bridge/u1nonfactor"
	"github.com/bagherbal/asha-engine/pkg/bridge/u1orientation"
	"github.com/bagherbal/asha-engine/pkg/bridge/u1source"
	"github.com/bagherbal/asha-engine/pkg/clifford"
	"github.com/bagherbal/asha-engine/pkg/dynamics/bsector"
	"github.com/bagherbal/asha-engine/pkg/dynamics/higgspotential"
	"github.com/bagherbal/asha-engine/pkg/dynamics/scalarpotential"
	"github.com/bagherbal/asha-engine/pkg/engine/cache"
	"github.com/bagherbal/asha-engine/pkg/exterior"
	"github.com/bagherbal/asha-engine/pkg/gauge"
	"github.com/bagherbal/asha-engine/pkg/gauge/boundary"
	"github.com/bagherbal/asha-engine/pkg/gauge/connection"
	"github.com/bagherbal/asha-engine/pkg/gauge/higgs"
	"github.com/bagherbal/asha-engine/pkg/gauge/lift"
	"github.com/bagherbal/asha-engine/pkg/geometry/boolean"
	"github.com/bagherbal/asha-engine/pkg/geometry/contact"
	"github.com/bagherbal/asha-engine/pkg/geometry/g2"
	"github.com/bagherbal/asha-engine/pkg/matter"
	"github.com/bagherbal/asha-engine/pkg/matter/action"
	"github.com/bagherbal/asha-engine/pkg/matter/bfbridge"
	"github.com/bagherbal/asha-engine/pkg/matter/bfcurvature"
	"github.com/bagherbal/asha-engine/pkg/matter/bfsource"
	"github.com/bagherbal/asha-engine/pkg/matter/charge"
	"github.com/bagherbal/asha-engine/pkg/matter/electroweak"
	"github.com/bagherbal/asha-engine/pkg/matter/embedding"
	"github.com/bagherbal/asha-engine/pkg/matter/gencurvature"
	"github.com/bagherbal/asha-engine/pkg/matter/generationbreak"
	"github.com/bagherbal/asha-engine/pkg/matter/hyperaudit"
	"github.com/bagherbal/asha-engine/pkg/matter/hypercharge"
	"github.com/bagherbal/asha-engine/pkg/matter/sourceaction"
	"github.com/bagherbal/asha-engine/pkg/matter/sourcemap"
	"github.com/bagherbal/asha-engine/pkg/matter/sourcepotential"
	"github.com/bagherbal/asha-engine/pkg/matter/su2l"
	"github.com/bagherbal/asha-engine/pkg/matter/su2lgauge"
	"github.com/bagherbal/asha-engine/pkg/matter/t3r"
	"github.com/bagherbal/asha-engine/pkg/matter/tensor"
	"github.com/bagherbal/asha-engine/pkg/matter/texture"
	"github.com/bagherbal/asha-engine/pkg/matter/trialityyukawa"
	"github.com/bagherbal/asha-engine/pkg/matter/yukawa"
	"github.com/bagherbal/asha-engine/pkg/matter/yukawaintertwiner"
	"github.com/bagherbal/asha-engine/pkg/phase"
	"github.com/bagherbal/asha-engine/pkg/spinor"
	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Run() error {
	registry := theorem.NewRegistry(
		exterior.GradeStructureTheorem(8),
		clifford.StructureTheorem(clifford.Signature{Positive: 1, Negative: 7}),
		phase.CovariantPhaseSpaceTheorem(4),
		boolean.IncidenceSupportTheorem(8, 3, 4),
		g2.CalibrationSupportTheorem(),
		contact.ContactSpaceTheorem(),
		bsector.ContactVacuumTheorem(),
		gauge.ContactCentralizerTheorem(),
		lift.BooleanCompressionTheorem(),
		boundary.BoundaryFixedClosureTheorem(),
		connection.ProjectedConnectionTheorem(),
		higgs.VacuumMixingTheorem(),
		higgspotential.PotentialCandidateTheorem(),
		spinor.FockSpaceTheorem(),
		matter.FockContactBridgeTheorem(),
		action.RepresentationActionTheorem(),
		embedding.CanonicalEmbeddingTheorem(),
		charge.ChargePolarizationTheorem(),
		tensor.TensorFactorBridgeTheorem(),
		yukawa.IntertwinerSelectionTheorem(),
		electroweak.OperatorSearchTheorem(),
		hypercharge.ScalarHyperchargeBridgeTheorem(),
		t3r.MatterT3RSearchTheorem(),
		hyperaudit.HyperchargeTableAuditTheorem(),
		su2l.DoubletAuditTheorem(),
		su2lgauge.GeneratorAuditTheorem(),
		yukawaintertwiner.GaugeCompatibleYukawaTheorem(),
		trialityyukawa.GenerationTrialityYukawaTheorem(),
		texture.GenerationBreakingTextureSearchTheorem(),
		generationbreak.FiniteGenerationBreakingSearchTheorem(),
		gencurvature.CurvatureOnGenerationCarrierTheorem(),
		bfbridge.ActiveGenerationProjectionBridgeTheorem(),
		bfcurvature.FiniteMaurerCartanCurvatureTheorem(),
		bfsource.BFActionSourceTextureTheorem(),
		sourcemap.SourceTensorSelectionTheorem(),
		sourceaction.SourceTensorActionTheorem(),
		sourcepotential.SymmetryBreakingSourceActionTheorem(),
		scalarpotential.EffectivePotentialTheorem(),
		scalarscale.ScaleBridgeSearchTheorem(),
		actionscale.ActionNormalizationScaleBridgeTheorem(),
		couplingnorm.CouplingNormalizationBridgeTheorem(),
		ewprojection.ElectroweakProjectionTheorem(),
		rgflow.RGBoundaryFlowAuditTheorem(),
		betacoeff.FiniteSpectrumBetaCoefficientAuditTheorem(),
		threshold.ThresholdSpectrumMatchingAuditTheorem(),
		thresholdrep.ThresholdRepresentationAssignmentAuditTheorem(),
		thresholdactivation.ThresholdActivationDecouplingAuditTheorem(),
		fieldmap.FiniteToContinuumFieldMapAuditTheorem(),
		goldstone.GaugeEatingGoldstoneAuditTheorem(),
		scalarsu2.ScalarContactSU2ActionSearchTheorem(),
		scalarcomplex.ScalarComplexQuaternionicStructureSearchTheorem(),
		condensate.CompositeHiggsCondensateDirectionAuditTheorem(),
		looppotential.NativeOneLoopPotentialLedgerTheorem(),
		loopoperator.FiniteLoopOperatorConstructionTheorem(),
		topkernel.TopLikeOverlapKernelSearchTheorem(),
		gapledger.NJLGapKernelCriticalityLedgerTheorem(),
		fourfermion.NativeFourFermionKernelTheorem(),
		fierz.FiniteFierzProjectionAuditTheorem(),
		chiraltrace.FiniteChiralBilinearMetricTheorem(),
		currentprojection.CurrentActionScalarProjectionTheorem(),
		kineticnorm.GeneratorKineticNormalizationTheorem(),
		fierzsign.CliffordLorentzFierzSignTheorem(),
		exchangekernel.PropagatorExchangeKernelAuditTheorem(),
		exchangeaction.FiniteExchangeActionPropagatorSearchTheorem(),
		propagatorspectrum.FinitePropagatorSpectrumSearchTheorem(),
		sectorspectrum.CurrentSectorSpectralAssignmentSearchTheorem(),
		sectoroperators.CurrentSectorOperatorConstructionSearchTheorem(),
		casimirkernel.CurrentSectorCasimirPropagatorDiagnosticTheorem(),
		exchangeselection.FiniteExchangeActionSelectionTheorem(),
		currenthessian.FiniteCurrentHessianSearchTheorem(),
		currentembedding.CurrentFieldEmbeddingTheorem(),
		currentcontact.CurrentToContactEmbeddingMapSearchTheorem(),
		dualcarrier.DualCarrierGaugeArchitectureSplitTheorem(),
		dualcoupling.DualCarrierCouplingTensorActionSearchTheorem(),
		abelianmixing.AbelianMixingHyperchargeNormalizationTheorem(),
		u1kinetic.U1KineticMixingHessianSearchTheorem(),
		u1source.ContactU1BLKineticSourceSearchTheorem(),
		u1nonfactor.NonFactorizedAbelianActionSearchTheorem(),
		u1orientation.ChiralOrientationalAbelianSourceSearchTheorem(),
		anomaly.AbelianAnomalyCancellationLedgerTheorem(),
		anomalykinetic.AnomalyConstrainedU1KineticHessianSearchTheorem(),
		abeliancoupling.AbelianCouplingNormalizationFromDiagonalHessianAuditTheorem(),
		gaugeaction.GaugeKineticActionSelectionRGBoundaryAuditTheorem(),
		gaugehessian.GaugeKineticHessianSecondVariationTheorem(),
		scalarcovariant.FiniteScalarCovariantDerivativeMassMatrixTheorem(),
		gaugeeating.FiniteScalarKineticGaugeEatingSearchTheorem(),
		scalarvacuum.ScalarVacuumOrientationFiniteMinimizerSearchTheorem(),
		protectedintertwiner.ProtectedContactBrokenGeneratorIntertwinerSearchTheorem(),
		protectedmetric.ProtectedContactMetricConnectionSearchTheorem(),
		protectedconnection.ProtectedCarrierOperatorBFContactConnectionSearchTheorem(),
		o3quotient.O3GaugeQuotientPhysicalOrientationAuditTheorem(),
		quotientedcorrespondence.GaugeQuotientedProtectedBrokenCorrespondenceAuditTheorem(),
		brokenmetric.BrokenImageMetricKineticNormalizationAuditTheorem(),
		brokengeneratornorm.NormalizedBrokenGeneratorBasisGaugeKineticCandidateTheorem(),
		gaugekineticdiag.GaugeKineticDiagActionSelectionAuditTheorem(),
		brokenaction.BrokenSectorActionSecondVariationSearchTheorem(),
		brokengaugefields.FiniteBrokenGaugeFieldVariablesCurvatureSearchTheorem(),
		ewcurvature.FullElectroweakConnectionCurvatureAuditTheorem(),
		ewquadratic.FullElectroweakQuadraticActionAbelianCompletionTheorem(),
		u1completion.AbelianCoefficientU1CompletionSelectionSearchTheorem(),
		canonicalaction.CanonicalFiniteVariationalActionTheorem(),
		canonicalboundary.CanonicalFiniteRGBoundarySeedTheorem(),
		contactembedding.ContactMatterHyperchargeEmbeddingTheorem(),
		rgfirewall.FiniteRGFlowBoundaryScaleFirewallTheorem(),
		boundaryselector.BoundaryScaleOperatorAbsoluteCouplingSearchTheorem(),
		coarsegrain.NativeFiniteCoarseGrainingThresholdActivationSearchTheorem(),
		shellfunctor.FiniteShellFunctorSemigroupConstructionTheorem(),
		filtration.FiniteFiltrationOrderSelectorThresholdPredicateSearchTheorem(),
		betamatching.ThresholdRepresentationCompletionBetaMatchingTensorSearchTheorem(),
		modeclass.FiniteMassActivationClassClassifierTheorem(),
		contactpropagator.ContactOverlapKineticSignLocalityPropagatorClassifierTheorem(),
		contactfieldmap.ContactOverlapLocalFieldMapConstraintBRSTClassifierTheorem(),
		betapermission.ContactOverlapRepresentationConstraintBetaPermissionFirewallTheorem(),
		branchselector.ContactModeBranchSelectorConstructionAttemptTheorem(),
		contactcohomology.FiniteContactConstraintDifferentialCohomologyObstructionTheorem(),
		contactbundle.ContactLocalBundleObstructionRepresentationRowConstructionTheorem(),
		contactincidence.ContactIncidenceFiberFunctorSearchTheorem(),
		contactnaturality.ContactFanoNaturalityAutomorphismObstructionTheorem(),
		contactsymmetry.ContactSymmetryBreakingSelectorStabilizerSearchTheorem(),
		contactautaction.ContactSideAutomorphismActionEquivariantAssignmentSearchTheorem(),
		cache.RuntimeFixtureCacheTheorem(),
	)

	results := registry.RunAll()
	fmt.Print(report.RenderTerminal(results))
	return nil
}
