// Package contactalgebraic implements Gate 147: contact irrational-spectrum
// algebraic-origin / minimal-polynomial obstruction theorem.
//
// Gate 146 showed that the centered contact current does not select a rational
// charge lattice. Gate 147 asks a more primitive question: are the contact
// partial-overlap eigenvalues already exact algebraic objects with certified
// minimal polynomials that could become a finite charge/representation source?
//
// The answer is deliberately narrow. The contact spectrum is generated by a
// finite symmetric overlap operator, so it is a legitimate finite spectral
// diagnostic. Three partial rows are numerically recognized as rational
// diagnostics (2/3, 1/2, 1/3). The remaining four rows are algebraic candidates
// only: the project currently has no exact number-field lift, characteristic
// polynomial certificate, or row-wise minimal-polynomial proof. Numerical
// eigenvalues and rational approximations do not supply charge semantics,
// hypercharge rows, local variables, mass activation, or beta permission.
package contactalgebraic

import (
	"fmt"
	"math"
	"strings"
	"sync"

	"github.com/bagherbal/asha-engine/pkg/bridge/contactchargelattice"
	geomcontact "github.com/bagherbal/asha-engine/pkg/geometry/contact"
)

type AlgebraicCandidateKind string

const (
	KindRationalDiagnostic        AlgebraicCandidateKind = "rational-diagnostic"
	KindNumericAlgebraicCandidate AlgebraicCandidateKind = "numeric-algebraic-candidate"
)

type RowAudit struct {
	Name                       string
	Value                      float64
	Kind                       AlgebraicCandidateKind
	RationalRecognized         bool
	RationalNumerator          int
	RationalDenominator        int
	RationalError              float64
	DegreeOneCertified         bool
	FiniteSpectralOrigin       bool
	ExactNumberFieldCertified  bool
	MinimalPolynomialCertified bool
	MinimalPolynomial          string
	RequiresSymbolicLift       bool
	RequiresNumericalFitting   bool
	ChargeSemantic             bool
	RepresentationSemantic     bool
	OpensBetaPermission        bool
	Verdict                    string
}

type MatrixOriginAudit struct {
	AmbientOverlapDimension       int
	ContactMultiplicity           int
	PartialRows                   int
	FiniteSymmetricOperator       bool
	NumericEigenDecomposition     bool
	ExactMatrixOverNumberField    bool
	CharacteristicPolynomialExact bool
	RowMinimalPolynomialsExact    bool
	Verdict                       string
}

type MinimalPolynomialRequirements struct {
	ExactNumberFieldBasis         bool
	ExactCharacteristicPolynomial bool
	RowwiseMinimalPolynomials     bool
	AlgebraicRowSemantics         bool
	ChargeLatticeSelected         bool
	OperatorPullback              bool
	LocalFieldMap                 bool
	MassActivation                bool
	DecouplingRule                bool
	ObservedInputFree             bool
	AllSatisfied                  bool
	Verdict                       string
}

type Summary struct {
	ContactRows                int
	RationalRows               int
	NonRationalCandidateRows   int
	DegreeOneCertifiedRows     int
	NonDegreeOneCertifiedRows  int
	ExactMinimalPolynomialRows int
	NumericOnlyRows            int
	ExactNumberFieldLifts      int
	ChargeSemanticRows         int
	RepresentationCompleteRows int
	RepresentationOpenRows     int
	ContactBetaRowsAllowed     int
	ContactZeroRowsProved      int
	ResidualS6Choices          int
	ResidualNullityBefore      int
	ResidualNullityAfter       int
}

type Analysis struct {
	Previous contactchargelattice.Analysis
	Contact  geomcontact.Space

	PartialValues []float64
	Rows          []RowAudit
	MatrixOrigin  MatrixOriginAudit
	Requirements  MinimalPolynomialRequirements
	Summary       Summary

	ContactRows                  int
	RationalRows                 int
	NonRationalCandidateRows     int
	DegreeOneCertifiedRows       int
	NonDegreeOneCertifiedRows    int
	ExactMinimalPolynomialRows   int
	NumericOnlyRows              int
	ExactNumberFieldLifts        int
	ChargeSemanticRows           int
	T3RRowsDerived               int
	ChiralityRowsDerived         int
	BMinusLRowsDerived           int
	SU2LRowsDerived              int
	HyperchargeRowsDerived       int
	RepresentationCompleteRows   int
	RepresentationOpenRows       int
	ContactBetaRowsAllowed       int
	ContactZeroRowsProved        int
	BetaPermissionFirewallClosed bool
	ThresholdCorrectedBeta       bool
	FullBetaMatchingTensor       bool
	ResidualS6Choices            int
	ResidualNullityBefore        int
	ResidualNullityAfter         int
	HiddenObservedInputUsed      bool
	PhysicalWeakAngleDerived     bool
	FineStructureDerived         bool
	PhysicalMassesDerived        bool
	PhysicalScaleDerived         bool

	TruthStatement      string
	RejectedClaims      []string
	RemainingUnknowns   []string
	RecommendedNextGate string
}

var defaultOnce sync.Once
var defaultValue Analysis
var defaultErr error

func BuildDefault() (Analysis, error) {
	defaultOnce.Do(func() {
		prev, err := contactchargelattice.BuildDefault()
		if err != nil {
			defaultErr = err
			return
		}
		contact, err := geomcontact.BuildDefault()
		if err != nil {
			defaultErr = err
			return
		}
		defaultValue, defaultErr = Build(prev, contact)
	})
	return defaultValue, defaultErr
}

func Build(prev contactchargelattice.Analysis, contact geomcontact.Space) (Analysis, error) {
	if !prev.BetaPermissionFirewallClosed || prev.ContactRows != 7 || prev.ContactBetaRowsAllowed != 0 || prev.ChargeSemanticEmbeddings != 0 {
		return Analysis{}, fmt.Errorf("Gate 147 requires Gate 146 closed-firewall contact charge-lattice obstruction")
	}
	if prev.T3RRowsDerived != 0 || prev.BMinusLRowsDerived != 0 || prev.HyperchargeRowsDerived != 0 || prev.RepresentationCompleteRows != 0 {
		return Analysis{}, fmt.Errorf("Gate 147 requires no prior contact charge or representation semantics")
	}
	if prev.HiddenObservedInputUsed || prev.PhysicalWeakAngleDerived || prev.FineStructureDerived || prev.PhysicalMassesDerived || prev.PhysicalScaleDerived {
		return Analysis{}, fmt.Errorf("Gate 147 refuses hidden observed physical input")
	}

	partial := contactPartialModes(contact.OverlapEigenvalues, 1e-8)
	if len(partial) != 7 {
		return Analysis{}, fmt.Errorf("expected seven contact partial-overlap values, got %d", len(partial))
	}

	rows := make([]RowAudit, 0, len(partial))
	for i, value := range partial {
		rows = append(rows, auditRow(fmt.Sprintf("contact partial-overlap row %d", i+1), value))
	}

	rationalRows := count(rows, func(r RowAudit) bool { return r.RationalRecognized })
	degreeOne := count(rows, func(r RowAudit) bool { return r.DegreeOneCertified })
	exactMinPoly := count(rows, func(r RowAudit) bool { return r.MinimalPolynomialCertified })
	numericOnly := count(rows, func(r RowAudit) bool { return !r.ExactNumberFieldCertified && !r.MinimalPolynomialCertified })
	chargeSemantic := count(rows, func(r RowAudit) bool { return r.ChargeSemantic })

	matrix := MatrixOriginAudit{
		AmbientOverlapDimension:       len(contact.OverlapEigenvalues),
		ContactMultiplicity:           contact.OverlapMultiplicityNear(1, 1e-8),
		PartialRows:                   len(partial),
		FiniteSymmetricOperator:       true,
		NumericEigenDecomposition:     true,
		ExactMatrixOverNumberField:    false,
		CharacteristicPolynomialExact: false,
		RowMinimalPolynomialsExact:    false,
		Verdict:                       "contact overlap is a finite symmetric operator, but this gate has only numerical eigenvalues; no exact number-field matrix or characteristic/minimal-polynomial certificate is derived",
	}

	reqs := MinimalPolynomialRequirements{
		ExactNumberFieldBasis:         false,
		ExactCharacteristicPolynomial: false,
		RowwiseMinimalPolynomials:     false,
		AlgebraicRowSemantics:         false,
		ChargeLatticeSelected:         false,
		OperatorPullback:              false,
		LocalFieldMap:                 false,
		MassActivation:                false,
		DecouplingRule:                false,
		ObservedInputFree:             true,
		AllSatisfied:                  false,
		Verdict:                       "finite spectral origin and partial rational recognition do not select exact algebraic row semantics, charge operators, local fields, or threshold beta rows",
	}

	summary := Summary{
		ContactRows:                len(partial),
		RationalRows:               rationalRows,
		NonRationalCandidateRows:   len(partial) - rationalRows,
		DegreeOneCertifiedRows:     degreeOne,
		NonDegreeOneCertifiedRows:  len(partial) - degreeOne,
		ExactMinimalPolynomialRows: exactMinPoly,
		NumericOnlyRows:            numericOnly,
		ExactNumberFieldLifts:      0,
		ChargeSemanticRows:         chargeSemantic,
		RepresentationCompleteRows: 0,
		RepresentationOpenRows:     len(partial),
		ContactBetaRowsAllowed:     0,
		ContactZeroRowsProved:      0,
		ResidualS6Choices:          prev.ResidualS6Choices,
		ResidualNullityBefore:      prev.ResidualNullityAfter,
		ResidualNullityAfter:       prev.ResidualNullityAfter,
	}

	truth := "Gate 147 proves that the contact partial-overlap spectrum is a legitimate finite spectral diagnostic but not yet an exact algebraic charge source. Three rows are recognized as degree-one rational diagnostics (2/3, 1/2, 1/3); four rows remain numerical algebraic candidates. The project has not derived an exact number-field lift, characteristic polynomial, row-wise minimal polynomial certificates, or algebraic row semantics. Therefore contact T3R, B-L, hypercharge, representation rows, mass activation, decoupling, and threshold beta permission remain sealed."

	return Analysis{
		Previous:                     prev,
		Contact:                      contact,
		PartialValues:                partial,
		Rows:                         rows,
		MatrixOrigin:                 matrix,
		Requirements:                 reqs,
		Summary:                      summary,
		ContactRows:                  summary.ContactRows,
		RationalRows:                 summary.RationalRows,
		NonRationalCandidateRows:     summary.NonRationalCandidateRows,
		DegreeOneCertifiedRows:       summary.DegreeOneCertifiedRows,
		NonDegreeOneCertifiedRows:    summary.NonDegreeOneCertifiedRows,
		ExactMinimalPolynomialRows:   summary.ExactMinimalPolynomialRows,
		NumericOnlyRows:              summary.NumericOnlyRows,
		ExactNumberFieldLifts:        0,
		ChargeSemanticRows:           0,
		T3RRowsDerived:               0,
		ChiralityRowsDerived:         0,
		BMinusLRowsDerived:           0,
		SU2LRowsDerived:              0,
		HyperchargeRowsDerived:       0,
		RepresentationCompleteRows:   0,
		RepresentationOpenRows:       summary.RepresentationOpenRows,
		ContactBetaRowsAllowed:       0,
		ContactZeroRowsProved:        0,
		BetaPermissionFirewallClosed: true,
		ThresholdCorrectedBeta:       false,
		FullBetaMatchingTensor:       false,
		ResidualS6Choices:            prev.ResidualS6Choices,
		ResidualNullityBefore:        prev.ResidualNullityAfter,
		ResidualNullityAfter:         prev.ResidualNullityAfter,
		HiddenObservedInputUsed:      false,
		PhysicalWeakAngleDerived:     false,
		FineStructureDerived:         false,
		PhysicalMassesDerived:        false,
		PhysicalScaleDerived:         false,
		TruthStatement:               truth,
		RejectedClaims: []string{
			"numerical contact eigenvalues are certified exact minimal-polynomial roots",
			"rational recognition of three rows supplies contact charge semantics",
			"the four non-rational-looking rows may be fitted to a charge lattice",
			"finite spectral algebraic origin alone provides T3R, B-L, hypercharge, or beta rows",
			"observed constants may be used to select the algebraic field or minimal polynomials",
		},
		RemainingUnknowns: []string{
			"exact number-field lift of the contact overlap operator",
			"exact characteristic polynomial and row-wise minimal polynomial certificates",
			"semantic map from algebraic roots to contact charges or representations",
			"operator pullback, local field variables, mass activation, and decoupling",
		},
		RecommendedNextGate: "Gate 148 — exact contact overlap characteristic polynomial / symbolic number-field construction attempt",
	}, nil
}

func auditRow(name string, value float64) RowAudit {
	n, d, err, ok := recognizeRational(value, 12, 1e-9)
	row := RowAudit{
		Name:                   name,
		Value:                  value,
		FiniteSpectralOrigin:   true,
		RationalRecognized:     ok,
		RationalNumerator:      n,
		RationalDenominator:    d,
		RationalError:          err,
		ChargeSemantic:         false,
		RepresentationSemantic: false,
		OpensBetaPermission:    false,
	}
	if ok {
		row.Kind = KindRationalDiagnostic
		row.DegreeOneCertified = true
		row.MinimalPolynomialCertified = true
		row.MinimalPolynomial = fmt.Sprintf("%d*x-%d", d, n)
		row.ExactNumberFieldCertified = false // numerical recognition, not an exact symbolic lift of the whole matrix
		row.RequiresSymbolicLift = false
		row.RequiresNumericalFitting = false
		row.Verdict = "degree-one rational diagnostic recognized numerically; still no charge/representation semantics"
		return row
	}
	row.Kind = KindNumericAlgebraicCandidate
	row.DegreeOneCertified = false
	row.MinimalPolynomialCertified = false
	row.MinimalPolynomial = "not certified"
	row.ExactNumberFieldCertified = false
	row.RequiresSymbolicLift = true
	row.RequiresNumericalFitting = true
	row.Verdict = "finite spectral value is a numerical algebraic candidate; exact minimal polynomial and semantic row map are not derived"
	return row
}

func contactPartialModes(values []float64, eps float64) []float64 {
	out := make([]float64, 0)
	for _, v := range values {
		if v > eps && math.Abs(v-1) > eps {
			out = append(out, v)
		}
	}
	return out
}

func recognizeRational(v float64, maxDen int, eps float64) (int, int, float64, bool) {
	bestN, bestD := 0, 1
	bestErr := math.Inf(1)
	for d := 1; d <= maxDen; d++ {
		n := int(math.Round(v * float64(d)))
		approx := float64(n) / float64(d)
		err := math.Abs(v - approx)
		if err < bestErr {
			bestErr = err
			bestN = n
			bestD = d
		}
	}
	return bestN, bestD, bestErr, bestErr <= eps
}

func FormatRow(r RowAudit) string {
	rat := "none"
	if r.RationalRecognized {
		rat = fmt.Sprintf("%d/%d", r.RationalNumerator, r.RationalDenominator)
	}
	return fmt.Sprintf("%s value=%.10f kind=%s rational=%s err=%.3g minpoly=%t exactField=%t semantic=%t beta=%t (%s)", r.Name, r.Value, r.Kind, rat, r.RationalError, r.MinimalPolynomialCertified, r.ExactNumberFieldCertified, r.ChargeSemantic || r.RepresentationSemantic, r.OpensBetaPermission, r.Verdict)
}

func FormatRows(rows []RowAudit) string {
	parts := make([]string, 0, len(rows))
	for _, row := range rows {
		parts = append(parts, FormatRow(row))
	}
	return strings.Join(parts, "; ")
}

func FormatMatrixOrigin(m MatrixOriginAudit) string {
	return fmt.Sprintf("dim=%d contactMult=%d partial=%d finiteSymmetric=%t numericEig=%t exactField=%t charpoly=%t rowMinpoly=%t (%s)", m.AmbientOverlapDimension, m.ContactMultiplicity, m.PartialRows, m.FiniteSymmetricOperator, m.NumericEigenDecomposition, m.ExactMatrixOverNumberField, m.CharacteristicPolynomialExact, m.RowMinimalPolynomialsExact, m.Verdict)
}

func FormatRequirements(r MinimalPolynomialRequirements) string {
	return fmt.Sprintf("field=%t charpoly=%t rowMinpoly=%t semantics=%t lattice=%t pullback=%t local=%t mass=%t decoupling=%t observedFree=%t all=%t (%s)", r.ExactNumberFieldBasis, r.ExactCharacteristicPolynomial, r.RowwiseMinimalPolynomials, r.AlgebraicRowSemantics, r.ChargeLatticeSelected, r.OperatorPullback, r.LocalFieldMap, r.MassActivation, r.DecouplingRule, r.ObservedInputFree, r.AllSatisfied, r.Verdict)
}

func FormatSummary(s Summary) string {
	return fmt.Sprintf("contact=%d rational=%d nonrationalCandidates=%d degree1=%d nondegree1=%d exactMinpoly=%d numericOnly=%d exactFieldLifts=%d semantic=%d reps=%d/%d beta=%d nullity=%d→%d", s.ContactRows, s.RationalRows, s.NonRationalCandidateRows, s.DegreeOneCertifiedRows, s.NonDegreeOneCertifiedRows, s.ExactMinimalPolynomialRows, s.NumericOnlyRows, s.ExactNumberFieldLifts, s.ChargeSemanticRows, s.RepresentationCompleteRows, s.RepresentationOpenRows, s.ContactBetaRowsAllowed, s.ResidualNullityBefore, s.ResidualNullityAfter)
}

func count[T any](items []T, pred func(T) bool) int {
	n := 0
	for _, item := range items {
		if pred(item) {
			n++
		}
	}
	return n
}
