package generation2bernoullipayoffnormalizationandzerocomplementsupportaudit

import (
	"math"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2BernoulliPayoffNormalizationAndZeroComplementSupportAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 696 — Bernoulli Payoff Normalization and Zero-Complement Support Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 696 — Bernoulli Payoff Normalization and Zero-Complement Support Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate695 Bernoulli observable", Passed: a.Inherited.BernoulliObservableInherited && a.Inherited.Rho72Definition == "rho_72 = I_H72/72" && a.Inherited.EventProjector == "E_K7 = P_K7" && a.Inherited.ResponseOperator == "R_split = S_split P_K7" && math.Abs(a.Inherited.EventWeight-7.0/72.0) < tolerance && math.Abs(a.Inherited.ComplementWeight-65.0/72.0) < tolerance && a.Inherited.H72Dimension == h72Dimension && a.Inherited.K7Dimension == k7Dimension && a.Inherited.ComplementDimension == k7ComplementDim && a.Inherited.NoNativeHistoryResponse && a.Inherited.NoNativeRho72Reason && a.Inherited.NoNativePayoffReason && a.Inherited.NoNativeSevenOver72 && a.Inherited.Verdict == StatusGate695BernoulliObservableInherited, Detail: FormatInheritance(a.Inherited)},
			{Name: "define general two-payoff observable and expectation", Passed: a.General.Observable == "R_{a,b}=aP_K7+bP_perp" && a.General.ComplementProjector == "P_perp=I_H72-P_K7" && math.Abs(a.General.EventWeight-7.0/72.0) < tolerance && math.Abs(a.General.ComplementWeight-65.0/72.0) < tolerance && math.Abs(a.General.ActiveEventPayoff-a.Inherited.SSplit) < tolerance && a.General.ActiveComplementPayoff == 0 && math.Abs(a.General.ActiveExpectation-a.Inherited.ActiveExpectation) < tolerance && strings.Contains(a.General.Verdict, StatusExpectationForGeneralABComputed), Detail: FormatGeneral(a.General)},
			{Name: "audit affine payoff degeneracy", Passed: strings.Contains(a.Degeneracy.Equation, "(7/72)a") && math.Abs(a.Degeneracy.ReferenceExpectation-a.Inherited.ActiveExpectation) < tolerance && math.Abs(a.Degeneracy.ReferenceEventPayoff-a.Inherited.SSplit) < tolerance && a.Degeneracy.ReferenceComplementPayoff == 0 && a.Degeneracy.AlternativeDifferentFromActive && a.Degeneracy.ExpectationAloneDegenerate && math.Abs(a.Degeneracy.AlternativeExpectation-a.Inherited.ActiveExpectation) < tolerance && strings.Contains(a.Degeneracy.Verdict, StatusExpectationAloneDoesNotSelectPayoffNormalization), Detail: FormatDegeneracy(a.Degeneracy)},
			{Name: "define support-locality and force zero complement payoff", Passed: len(a.SupportLocality.Conditions) == 3 && strings.Contains(a.SupportLocality.PPerpLeftAction, "bP_perp") && strings.Contains(a.SupportLocality.PPerpRightAction, "bP_perp") && a.SupportLocality.ComplementPayoffForcedZero && a.SupportLocality.EventPayoffUnfixedBySupportLocality && strings.Contains(a.SupportLocality.Verdict, StatusSupportLocalityForcesZeroComplementPayoff), Detail: FormatSupportLocality(a.SupportLocality)},
			{Name: "reconstruct active payoff assignment", Passed: a.Assignment.SupportLocalObservable == "R_a=aP_K7" && a.Assignment.BoundaryPayoffAssignment == "a=S_split" && math.Abs(a.Assignment.EventPayoff-a.Inherited.SSplit) < tolerance && a.Assignment.ComplementPayoff == 0 && a.Assignment.ReconstructedOperator == "R_split=S_split P_K7" && a.Assignment.MatchesInheritedActive && a.Assignment.DoesNotProvePayoffNatively && strings.Contains(a.Assignment.Verdict, StatusActivePayoffAssignmentReconstructed), Detail: FormatAssignment(a.Assignment)},
			{Name: "audit alternative payoff observables", Passed: len(a.Alternatives.Alternatives) == 5 && a.Alternatives.FullPayoffRejected && a.Alternatives.ComplementPayoffRejected && a.Alternatives.CenteredRejected && a.Alternatives.SignedHodgeRejected && a.Alternatives.ActiveAccepted && a.Alternatives.AllAudited && a.Alternatives.Verdict == StatusAlternativePayoffObservablesAudited, Detail: FormatAlternatives(a.Alternatives)},
			{Name: "classify source types", Passed: strings.Contains(a.SourceTypes.PK7Role, "Boolean-octonionic") && strings.Contains(a.SourceTypes.PPerpRole, "no-response") && strings.Contains(a.SourceTypes.SSplitRole, "boundary") && strings.Contains(a.SourceTypes.Rho72Role, "no-bias") && strings.Contains(a.SourceTypes.RSplitRole, "support-local") && a.SourceTypes.Verdict == StatusActiveResponseSupportLocalK7PayoffObservable, Detail: FormatSourceTypes(a.SourceTypes)},
			{Name: "record missing native support/payoff theorems", Passed: len(a.Missing.Missing) == 4 && strings.Contains(a.Missing.PreciseGap, "why physical history imposes K7 support-locality") && strings.Contains(a.Missing.Verdict, StatusNoNativeReasonHistoryUsesSupportLocality) && strings.Contains(a.Missing.Verdict, StatusNoNativeReasonK7EventReceivesSSplitPayoff) && strings.Contains(a.Missing.Verdict, StatusNoNativeSevenOver72Theorem), Detail: FormatMissing(a.Missing)},
			{Name: "preserve Gate696 payoff-support firewall", Passed: !a.Firewall.ClaimsHistoryUsesSupportLocalityNatively && !a.Firewall.ClaimsK7PhysicalEventNatively && !a.Firewall.ClaimsSSplitPayoffNatively && !a.Firewall.ClaimsExpectationEqualsDBaseNatively && !a.Firewall.ClaimsResidualExplained && !a.Firewall.ClaimsNativeStateSelectionTheorem && !a.Firewall.ClaimsNativePayoffTheorem && !a.Firewall.ClaimsNativeSevenOver72Theorem && !a.Firewall.ClaimsBoundaryStress && !a.Firewall.ClaimsScalarRGMatching && !a.Firewall.ClaimsHiggsMass && !a.Firewall.ClaimsGaugeUnification && !a.Firewall.ClaimsFlavorDerivation && !a.Firewall.ClaimsCKMPMNS && a.Firewall.Verdict == StatusGate696BernoulliPayoffSupportBoundary, Detail: FormatFirewall(a.Firewall)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 696 — Bernoulli Payoff Normalization and Zero-Complement Support Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
