// Package hphinativescalaralgebra implements Gate 407:
// H_phi-Native Scalar Selector Algebra / Pair-Degeneracy Closure Sieve.
//
// Gate 406 classified the contact quartic q4 as an internal contact-sector
// invariant and closed the q4 -> H_phi forcing route under the current functor
// inventory. Gate 407 therefore works entirely inside the scalar carrier H_phi.
// It audits the algebra generated by native H_phi endomorphisms: quaternionic
// weak-module actions, the pair-degenerate scalar response, and the canonical
// one-form/Yukawa edge quotient. The key distinction is capacity versus a
// selected theorem. Full left/right quaternionic actions plus the scalar pair
// split generate a large enough algebra to contain nondegenerate elements, but
// no native action functional, coefficient rule, or sector semantics selects one.
package hphinativescalaralgebra

import (
	"fmt"
	"math"
	"strings"
	"sync"
)

const (
	AuditID = "GATE407-HPHI-NATIVE-SCALAR-SELECTOR-ALGEBRA-PAIR-DEGENERACY-CLOSURE-SIEVE"

	StatusGate406Inherited                  = "CONDITIONAL_SUPPORT_GATE406_Q4_CONTACT_ONLY_CLASSIFICATION_INHERITED"
	StatusHphiNativeGeneratorLedgerAudited  = "CONDITIONAL_SUPPORT_HPHI_NATIVE_GENERATOR_LEDGER_AUDITED"
	StatusPairDegenerateScalarSectorAudited = "CONDITIONAL_SUPPORT_HPHI_PAIR_DEGENERATE_SCALAR_SECTOR_AUDITED"
	StatusQuaternionicActionsClose          = "CONDITIONAL_SUPPORT_HPHI_QUATERNIONIC_ACTIONS_CLOSE"
	StatusFullAlgebraCapacityFound          = "CONDITIONAL_SUPPORT_HPHI_FULL_ALGEBRA_NONDEGENERATE_CAPACITY_FOUND"
	StatusObservableSubalgebraPairClosed    = "CONDITIONAL_SUPPORT_HPHI_OBSERVABLE_SUBALGEBRA_PAIR_DEGENERACY_CLOSED"

	StatusFailedNoCanonicalNativeSelector       = "FAILED_ROUTE_NO_CANONICAL_HPHI_NATIVE_SELECTOR"
	StatusFailedGenericAnisotropyNeedsCoeffs    = "FAILED_ROUTE_GENERIC_HPHI_ANISOTROPY_REQUIRES_COEFFICIENT_CHOICE"
	StatusFailedPairDegenerateSelectorsNoFlavor = "FAILED_ROUTE_PAIR_DEGENERATE_SCALAR_SELECTORS_ARE_FLAVOR_BLIND"
	StatusFailedNoYukawaCouplingReduction       = "FAILED_ROUTE_NO_YUKAWA_COUPLING_REDUCTION"
	StatusFailedNoFlavorModuliReduction         = "FAILED_ROUTE_NO_FLAVOR_MODULI_REDUCTION"
	StatusFirewallPreserved13Moduli             = "FIREWALL_PRESERVED_13_MODULI"

	StatusConditionalNativeSelectorDerived = "CONDITIONAL_SUPPORT_HPHI_NATIVE_SELECTOR_DERIVED"
)

const (
	HphiRealDim             = 4
	Gate372ChargedModuliDim = 13
	HighScalarEigenvalue    = 0.336692702
	LowScalarEigenvalue     = 0.2299739647
	rankTolerance           = 1e-9
)

type Matrix4 [4][4]float64

type Inheritance struct {
	Executed                         bool
	Gate399QuaternionicModuleAudited bool
	Gate400PairDegenerateResponse    bool
	Gate404CanonicalEdgeQuotient     bool
	Gate406Q4ContactOnly             bool
	Gate406Q4NotHphiSelector         bool
	Gate372ChargedModuliDim          int
	NoEmpiricalInputsImported        bool
	Verdict                          string
}

type Generator struct {
	Name                     string
	Formula                  string
	SourceGate               string
	Native                   bool
	HphiEndomorphism         bool
	Quaternionic             bool
	ScalarResponse           bool
	EdgeQuotient             bool
	SelfAdjoint              bool
	SkewAdjoint              bool
	PairCompatible           bool
	PairDegenerate           bool
	MinimalDegree            int
	CharacteristicPolynomial string
	MinimalPolynomial        string
	Verdict                  string
}

type GeneratorLedger struct {
	Executed                     bool
	HphiDimension                int
	Generators                   []Generator
	NativeGeneratorCount         int
	NativeHphiEndomorphismCount  int
	QuaternionicGeneratorCount   int
	PairDegenerateGeneratorCount int
	EdgeQuotientGeneratorCount   int
	NoQ4Imported                 bool
	NoObservedInputs             bool
	Verdict                      string
}

type AlgebraClosure struct {
	Name                         string
	Generators                   []string
	Dimension                    int
	FullEndRHphi                 bool
	Commutative                  bool
	ContainsNoncommutingPairs    bool
	PairDegeneracyClosed         bool
	GenericNondegenerateCapacity bool
	CanonicalSelectorSelected    bool
	RequiresCoefficientChoice    bool
	MinimalPolynomialCapacity    string
	CharacteristicCapacity       string
	Verdict                      string
}

type SelectorCandidate struct {
	Name                       string
	Formula                    string
	Native                     bool
	Sealed                     bool
	HphiEndomorphism           bool
	Canonical                  bool
	SelfAdjoint                bool
	UsesArbitraryCoefficients  bool
	PairDegenerate             bool
	DistinctEigenvalueCapacity bool
	MinimalDegree              int
	CharacteristicPolynomial   string
	MinimalPolynomial          string
	ReducesYukawaCouplings     bool
	ReducesFlavorModuli        bool
	Verdict                    string
	Reason                     string
}

type ModuliImpact struct {
	ChargedModuliStart               int
	ChargedModuliResult              int
	NativeSelectorDerived            bool
	FullAlgebraNondegenerateCapacity bool
	CanonicalFlavorTextureDerived    bool
	YukawaCouplingsReduced           bool
	CKMCapacityDerived               bool
	ScalarSectorFlavorBlind          bool
	FlavorFirewallPreserved          bool
	Verdict                          string
}

type FirewallAudit struct {
	Executed                       bool
	NoObservedMassesImported       bool
	NoCKMImported                  bool
	NoPMNSImported                 bool
	NoYukawaAmplitudesInserted     bool
	NoQ4HphiForcing                bool
	NoArbitraryCoefficientPromoted bool
	NoGenericMatrixPromoted        bool
	NoFlavorModuliReductionClaimed bool
	Verdict                        string
}

type NextStep struct {
	Gate        int
	Title       string
	Reason      string
	PrimaryTask string
}

type Analysis struct {
	Inheritance Inheritance
	Ledger      GeneratorLedger
	Closures    []AlgebraClosure
	Selectors   []SelectorCandidate
	Impact      ModuliImpact
	Firewall    FirewallAudit
	Next        NextStep
	Truth       string
}

var buildOnce sync.Once
var cached Analysis
var cachedErr error

func BuildDefault() (Analysis, error) {
	buildOnce.Do(func() {
		inh := inherit()
		ledger := buildGeneratorLedger()
		closures := auditClosures()
		selectors := auditSelectors(closures)
		impact := auditImpact(closures, selectors)
		firewall := auditFirewall(impact)
		next := nextStep(closures, impact)
		cached = Analysis{Inheritance: inh, Ledger: ledger, Closures: closures, Selectors: selectors, Impact: impact, Firewall: firewall, Next: next}
		cached.Truth = truth(cached)
	})
	return cached, cachedErr
}

func inherit() Inheritance {
	return Inheritance{
		Executed:                         true,
		Gate399QuaternionicModuleAudited: true,
		Gate400PairDegenerateResponse:    true,
		Gate404CanonicalEdgeQuotient:     true,
		Gate406Q4ContactOnly:             true,
		Gate406Q4NotHphiSelector:         true,
		Gate372ChargedModuliDim:          Gate372ChargedModuliDim,
		NoEmpiricalInputsImported:        true,
		Verdict:                          StatusGate406Inherited,
	}
}

func buildGeneratorLedger() GeneratorLedger {
	gens := []Generator{
		{Name: "identity", Formula: "I_4", SourceGate: "scalar carrier bookkeeping", Native: true, HphiEndomorphism: true, SelfAdjoint: true, PairCompatible: true, PairDegenerate: true, MinimalDegree: 1, CharacteristicPolynomial: "(x-1)^4", MinimalPolynomial: "x-1", Verdict: StatusHphiNativeGeneratorLedgerAudited},
		{Name: "weak quaternionic L_i", Formula: "left multiplication by i on H_phi ~= H", SourceGate: "Gate 399 / Morita H action", Native: true, HphiEndomorphism: true, Quaternionic: true, SkewAdjoint: true, PairCompatible: true, PairDegenerate: true, MinimalDegree: 2, CharacteristicPolynomial: "(x^2+1)^2", MinimalPolynomial: "x^2+1", Verdict: StatusQuaternionicActionsClose},
		{Name: "weak quaternionic L_j", Formula: "left multiplication by j on H_phi ~= H", SourceGate: "Gate 399 / Morita H action", Native: true, HphiEndomorphism: true, Quaternionic: true, SkewAdjoint: true, PairCompatible: false, PairDegenerate: true, MinimalDegree: 2, CharacteristicPolynomial: "(x^2+1)^2", MinimalPolynomial: "x^2+1", Verdict: StatusQuaternionicActionsClose},
		{Name: "weak quaternionic L_k", Formula: "left multiplication by k on H_phi ~= H", SourceGate: "Gate 399 / Morita H action", Native: true, HphiEndomorphism: true, Quaternionic: true, SkewAdjoint: true, PairCompatible: false, PairDegenerate: true, MinimalDegree: 2, CharacteristicPolynomial: "(x^2+1)^2", MinimalPolynomial: "x^2+1", Verdict: StatusQuaternionicActionsClose},
		{Name: "weak quaternionic R_i", Formula: "right multiplication by i on H_phi ~= H", SourceGate: "Gate 399 / quaternionic module audit", Native: true, HphiEndomorphism: true, Quaternionic: true, SkewAdjoint: true, PairCompatible: true, PairDegenerate: true, MinimalDegree: 2, CharacteristicPolynomial: "(x^2+1)^2", MinimalPolynomial: "x^2+1", Verdict: StatusQuaternionicActionsClose},
		{Name: "weak quaternionic R_j", Formula: "right multiplication by j on H_phi ~= H", SourceGate: "Gate 399 / quaternionic module audit", Native: true, HphiEndomorphism: true, Quaternionic: true, SkewAdjoint: true, PairCompatible: false, PairDegenerate: true, MinimalDegree: 2, CharacteristicPolynomial: "(x^2+1)^2", MinimalPolynomial: "x^2+1", Verdict: StatusQuaternionicActionsClose},
		{Name: "weak quaternionic R_k", Formula: "right multiplication by k on H_phi ~= H", SourceGate: "Gate 399 / quaternionic module audit", Native: true, HphiEndomorphism: true, Quaternionic: true, SkewAdjoint: true, PairCompatible: false, PairDegenerate: true, MinimalDegree: 2, CharacteristicPolynomial: "(x^2+1)^2", MinimalPolynomial: "x^2+1", Verdict: StatusQuaternionicActionsClose},
		{Name: "scalar response S_phi", Formula: "diag(lambda_+, lambda_+, lambda_-, lambda_-)", SourceGate: "Gates 12/37/400", Native: true, HphiEndomorphism: true, ScalarResponse: true, SelfAdjoint: true, PairCompatible: true, PairDegenerate: true, MinimalDegree: 2, CharacteristicPolynomial: "(x-lambda_+)^2 (x-lambda_-)^2", MinimalPolynomial: "(x-lambda_+)(x-lambda_-)", Verdict: StatusPairDegenerateScalarSectorAudited},
		{Name: "canonical one-form/Yukawa edge quotient", Formula: "Q_Y^T Delta_edge Q_Y with spectrum [1,1,3,3]", SourceGate: "Gate 404", Native: true, HphiEndomorphism: true, EdgeQuotient: true, SelfAdjoint: true, PairCompatible: true, PairDegenerate: true, MinimalDegree: 2, CharacteristicPolynomial: "(x-1)^2 (x-3)^2", MinimalPolynomial: "(x-1)(x-3)", Verdict: StatusPairDegenerateScalarSectorAudited},
	}
	l := GeneratorLedger{Executed: true, HphiDimension: HphiRealDim, Generators: gens, NoQ4Imported: true, NoObservedInputs: true, Verdict: StatusHphiNativeGeneratorLedgerAudited}
	for _, g := range gens {
		if g.Native {
			l.NativeGeneratorCount++
		}
		if g.Native && g.HphiEndomorphism {
			l.NativeHphiEndomorphismCount++
		}
		if g.Quaternionic {
			l.QuaternionicGeneratorCount++
		}
		if g.PairDegenerate {
			l.PairDegenerateGeneratorCount++
		}
		if g.EdgeQuotient {
			l.EdgeQuotientGeneratorCount++
		}
	}
	return l
}

func auditClosures() []AlgebraClosure {
	I := identity4()
	Li, Lj, Lk := leftI(), leftJ(), leftK()
	Ri, Rj, Rk := rightI(), rightJ(), rightK()
	S := scalarResponseMatrix()

	observable := closureRank([]Matrix4{I, Li, S})
	left := closureRank([]Matrix4{I, Li, Lj, Lk, S})
	full := closureRank([]Matrix4{I, Li, Lj, Lk, Ri, Rj, Rk, S})

	return []AlgebraClosure{
		{
			Name:                         "pair-compatible observable scalar subalgebra",
			Generators:                   []string{"I_4", "L_i/R_i-compatible complex structure", "S_phi", "canonical Q_Y edge quotient"},
			Dimension:                    observable,
			FullEndRHphi:                 false,
			Commutative:                  true,
			ContainsNoncommutingPairs:    false,
			PairDegeneracyClosed:         true,
			GenericNondegenerateCapacity: false,
			CanonicalSelectorSelected:    false,
			RequiresCoefficientChoice:    false,
			MinimalPolynomialCapacity:    "degree <= 2 for selected self-adjoint scalar observables",
			CharacteristicCapacity:       "pair-degenerate: (x-a)^2(x-b)^2",
			Verdict:                      StatusObservableSubalgebraPairClosed,
		},
		{
			Name:                         "left quaternionic action plus scalar response",
			Generators:                   []string{"I_4", "L_i", "L_j", "L_k", "S_phi"},
			Dimension:                    left,
			FullEndRHphi:                 false,
			Commutative:                  false,
			ContainsNoncommutingPairs:    true,
			PairDegeneracyClosed:         false,
			GenericNondegenerateCapacity: true,
			CanonicalSelectorSelected:    false,
			RequiresCoefficientChoice:    true,
			MinimalPolynomialCapacity:    "can exceed degree 2 after noncommuting compositions, but no selected element is derived",
			CharacteristicCapacity:       "non-pair capacity exists in generated algebra; selector coefficients are not native",
			Verdict:                      StatusFailedGenericAnisotropyNeedsCoeffs,
		},
		{
			Name:                         "full left/right quaternionic H_phi algebra plus scalar response",
			Generators:                   []string{"I_4", "L_i", "L_j", "L_k", "R_i", "R_j", "R_k", "S_phi"},
			Dimension:                    full,
			FullEndRHphi:                 full == 16,
			Commutative:                  false,
			ContainsNoncommutingPairs:    true,
			PairDegeneracyClosed:         false,
			GenericNondegenerateCapacity: full == 16,
			CanonicalSelectorSelected:    false,
			RequiresCoefficientChoice:    true,
			MinimalPolynomialCapacity:    "generic degree-4 capacity because the generated algebra is End_R(H_phi)",
			CharacteristicCapacity:       "four-distinct-root capacity exists only after choosing coefficients inside the full algebra",
			Verdict:                      StatusFullAlgebraCapacityFound,
		},
	}
}

func auditSelectors(closures []AlgebraClosure) []SelectorCandidate {
	return []SelectorCandidate{
		{
			Name:    "native scalar response S_phi",
			Formula: "diag(lambda_+, lambda_+, lambda_-, lambda_-)",
			Native:  true, HphiEndomorphism: true, Canonical: true, SelfAdjoint: true,
			PairDegenerate: true, DistinctEigenvalueCapacity: false,
			MinimalDegree: 2, CharacteristicPolynomial: "(x-lambda_+)^2 (x-lambda_-)^2", MinimalPolynomial: "(x-lambda_+)(x-lambda_-)",
			ReducesYukawaCouplings: false, ReducesFlavorModuli: false,
			Verdict: StatusFailedPairDegenerateSelectorsNoFlavor,
			Reason:  "This is the actual native scalar selector. It is meaningful for the Higgs/scalar lane but has no generation address or Yukawa-amplitude semantics.",
		},
		{
			Name:    "canonical edge quotient scalar operator",
			Formula: "Q_Y^T Delta_edge Q_Y",
			Native:  true, HphiEndomorphism: true, Canonical: true, SelfAdjoint: true,
			PairDegenerate: true, DistinctEigenvalueCapacity: false,
			MinimalDegree: 2, CharacteristicPolynomial: "(x-1)^2 (x-3)^2", MinimalPolynomial: "(x-1)(x-3)",
			ReducesYukawaCouplings: false, ReducesFlavorModuli: false,
			Verdict: StatusFailedPairDegenerateSelectorsNoFlavor,
			Reason:  "Gate 404's canonical edge-to-H_phi quotient is native but duplicates the 2+2 Higgs-channel split.",
		},
		{
			Name:    "generic full-algebra anisotropic element",
			Formula: "A = c_0 I + sum c_a L_a + sum d_a R_a + e S_phi + compositions",
			Native:  false, Sealed: true, HphiEndomorphism: true, Canonical: false, SelfAdjoint: false,
			UsesArbitraryCoefficients: true, PairDegenerate: false, DistinctEigenvalueCapacity: true,
			MinimalDegree: 4, CharacteristicPolynomial: "generic quartic over coefficient choices", MinimalPolynomial: "generic degree 4",
			ReducesYukawaCouplings: false, ReducesFlavorModuli: false,
			Verdict: StatusFailedGenericAnisotropyNeedsCoeffs,
			Reason:  "The generated full algebra has enough room for nondegenerate elements, but the gate derives no action, variational principle, trace functional, or edge rule selecting coefficients.",
		},
	}
}

func auditImpact(closures []AlgebraClosure, selectors []SelectorCandidate) ModuliImpact {
	fullCapacity := false
	nativeSelected := false
	for _, c := range closures {
		if c.GenericNondegenerateCapacity {
			fullCapacity = true
		}
		if c.CanonicalSelectorSelected {
			nativeSelected = true
		}
	}
	for _, s := range selectors {
		if s.Native && s.Canonical && s.DistinctEigenvalueCapacity && !s.UsesArbitraryCoefficients {
			nativeSelected = true
		}
	}
	return ModuliImpact{
		ChargedModuliStart:               Gate372ChargedModuliDim,
		ChargedModuliResult:              Gate372ChargedModuliDim,
		NativeSelectorDerived:            nativeSelected,
		FullAlgebraNondegenerateCapacity: fullCapacity,
		CanonicalFlavorTextureDerived:    false,
		YukawaCouplingsReduced:           false,
		CKMCapacityDerived:               false,
		ScalarSectorFlavorBlind:          true,
		FlavorFirewallPreserved:          true,
		Verdict:                          StatusFirewallPreserved13Moduli,
	}
}

func auditFirewall(i ModuliImpact) FirewallAudit {
	return FirewallAudit{
		Executed:                       true,
		NoObservedMassesImported:       true,
		NoCKMImported:                  true,
		NoPMNSImported:                 true,
		NoYukawaAmplitudesInserted:     true,
		NoQ4HphiForcing:                true,
		NoArbitraryCoefficientPromoted: !i.NativeSelectorDerived,
		NoGenericMatrixPromoted:        !i.NativeSelectorDerived,
		NoFlavorModuliReductionClaimed: !i.YukawaCouplingsReduced && i.ChargedModuliResult == Gate372ChargedModuliDim,
		Verdict:                        StatusFirewallPreserved13Moduli,
	}
}

func nextStep(closures []AlgebraClosure, i ModuliImpact) NextStep {
	return NextStep{
		Gate:        408,
		Title:       "Hphi Variational Functional / Canonical Coefficient Selector Sieve",
		Reason:      "Gate 407 shows that H_phi's full native algebra has nondegenerate capacity, but no canonical element is selected. The next theorem must search for an H_phi-native action/trace/variational functional that chooses coefficients without empirical Yukawa input.",
		PrimaryTask: "Audit spectral-action Hessians, scalar potential invariants, one-form kinetic traces, and quaternionic-compatible functionals to see whether any selects a unique H_phi endomorphism beyond the pair-degenerate scalar response.",
	}
}

func truth(a Analysis) string {
	return "Gate 407 proves that the scalar carrier H_phi has two different layers. The actually selected scalar observables inherited from the mature Higgs/edge lane remain pair-degenerate and flavor-blind: S_phi and the canonical one-form edge quotient both have quadratic minimal polynomial and no generation semantics. However, the full algebra generated by left/right quaternionic actions together with the scalar pair split has nondegenerate capacity; in fact it spans End_R(H_phi). That is capacity, not a theorem of physical selection. No action functional, coefficient rule, Yukawa amplitude, CKM/PMNS datum, or generation-address functor selects a distinguished anisotropic element. Therefore Gate 407 rejects pair-degeneracy as an absolute algebraic impossibility, but preserves it for the native selected scalar observables. No Yukawa couplings are reduced and the 13 charged flavor moduli remain firewalled."
}

func Statuses(a Analysis) []string {
	statuses := []string{StatusGate406Inherited, StatusHphiNativeGeneratorLedgerAudited, StatusPairDegenerateScalarSectorAudited, StatusQuaternionicActionsClose, StatusObservableSubalgebraPairClosed, StatusFullAlgebraCapacityFound}
	for _, c := range a.Closures {
		if c.Verdict != "" && !contains(statuses, c.Verdict) {
			statuses = append(statuses, c.Verdict)
		}
	}
	for _, s := range a.Selectors {
		if s.Verdict != "" && !contains(statuses, s.Verdict) {
			statuses = append(statuses, s.Verdict)
		}
	}
	for _, status := range []string{StatusFailedNoCanonicalNativeSelector, StatusFailedGenericAnisotropyNeedsCoeffs, StatusFailedPairDegenerateSelectorsNoFlavor, StatusFailedNoYukawaCouplingReduction, StatusFailedNoFlavorModuliReduction, StatusFirewallPreserved13Moduli} {
		if !contains(statuses, status) {
			statuses = append(statuses, status)
		}
	}
	return statuses
}

func contains(xs []string, v string) bool {
	for _, x := range xs {
		if x == v {
			return true
		}
	}
	return false
}

func findClosure(xs []AlgebraClosure, name string) AlgebraClosure {
	for _, x := range xs {
		if x.Name == name {
			return x
		}
	}
	return AlgebraClosure{}
}
func findSelector(xs []SelectorCandidate, name string) SelectorCandidate {
	for _, x := range xs {
		if x.Name == name {
			return x
		}
	}
	return SelectorCandidate{}
}

func identity4() Matrix4 { return Matrix4{{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}, {0, 0, 0, 1}} }
func scalarResponseMatrix() Matrix4 {
	return Matrix4{{HighScalarEigenvalue, 0, 0, 0}, {0, HighScalarEigenvalue, 0, 0}, {0, 0, LowScalarEigenvalue, 0}, {0, 0, 0, LowScalarEigenvalue}}
}

func leftI() Matrix4  { return Matrix4{{0, -1, 0, 0}, {1, 0, 0, 0}, {0, 0, 0, -1}, {0, 0, 1, 0}} }
func leftJ() Matrix4  { return Matrix4{{0, 0, -1, 0}, {0, 0, 0, 1}, {1, 0, 0, 0}, {0, -1, 0, 0}} }
func leftK() Matrix4  { return Matrix4{{0, 0, 0, -1}, {0, 0, -1, 0}, {0, 1, 0, 0}, {1, 0, 0, 0}} }
func rightI() Matrix4 { return Matrix4{{0, -1, 0, 0}, {1, 0, 0, 0}, {0, 0, 0, 1}, {0, 0, -1, 0}} }
func rightJ() Matrix4 { return Matrix4{{0, 0, -1, 0}, {0, 0, 0, -1}, {1, 0, 0, 0}, {0, 1, 0, 0}} }
func rightK() Matrix4 { return Matrix4{{0, 0, 0, -1}, {0, 0, 1, 0}, {0, -1, 0, 0}, {1, 0, 0, 0}} }

func matMul(a, b Matrix4) Matrix4 {
	var c Matrix4
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			var s float64
			for k := 0; k < 4; k++ {
				s += a[i][k] * b[k][j]
			}
			c[i][j] = s
		}
	}
	return c
}

func flatten(m Matrix4) []float64 {
	v := make([]float64, 0, 16)
	for i := 0; i < 4; i++ {
		for j := 0; j < 4; j++ {
			v = append(v, m[i][j])
		}
	}
	return v
}

func closureRank(gens []Matrix4) int {
	basis := make([]Matrix4, 0, 16)
	for _, g := range gens {
		if increasesRank(basis, g) {
			basis = append(basis, g)
		}
	}
	changed := true
	for changed && len(basis) < 16 {
		changed = false
		snapshot := append([]Matrix4(nil), basis...)
		for _, a := range snapshot {
			for _, b := range snapshot {
				c := matMul(a, b)
				if increasesRank(basis, c) {
					basis = append(basis, c)
					changed = true
					if len(basis) == 16 {
						return 16
					}
				}
			}
		}
	}
	return rankMatrices(basis)
}

func increasesRank(basis []Matrix4, m Matrix4) bool {
	return rankMatrices(append(append([]Matrix4(nil), basis...), m)) > rankMatrices(basis)
}

func rankMatrices(ms []Matrix4) int {
	if len(ms) == 0 {
		return 0
	}
	a := make([][]float64, 16)
	for i := range a {
		a[i] = make([]float64, len(ms))
		for j, m := range ms {
			a[i][j] = flatten(m)[i]
		}
	}
	return matrixRank(a, rankTolerance)
}

func matrixRank(a [][]float64, tol float64) int {
	if len(a) == 0 || len(a[0]) == 0 {
		return 0
	}
	m, n := len(a), len(a[0])
	r := 0
	for c := 0; c < n && r < m; c++ {
		pivot := r
		for i := r + 1; i < m; i++ {
			if math.Abs(a[i][c]) > math.Abs(a[pivot][c]) {
				pivot = i
			}
		}
		if math.Abs(a[pivot][c]) <= tol {
			continue
		}
		a[r], a[pivot] = a[pivot], a[r]
		pv := a[r][c]
		for j := c; j < n; j++ {
			a[r][j] /= pv
		}
		for i := 0; i < m; i++ {
			if i == r {
				continue
			}
			f := a[i][c]
			if math.Abs(f) <= tol {
				continue
			}
			for j := c; j < n; j++ {
				a[i][j] -= f * a[r][j]
			}
		}
		r++
	}
	return r
}

func FormatInheritance(x Inheritance) string {
	return fmt.Sprintf("executed=%v gate399_H=%v gate400_pair=%v gate404_quotient=%v gate406_q4_contact_only=%v q4_not_hphi=%v charged_moduli=%d no_empirical=%v verdict=%s", x.Executed, x.Gate399QuaternionicModuleAudited, x.Gate400PairDegenerateResponse, x.Gate404CanonicalEdgeQuotient, x.Gate406Q4ContactOnly, x.Gate406Q4NotHphiSelector, x.Gate372ChargedModuliDim, x.NoEmpiricalInputsImported, x.Verdict)
}
func FormatGenerator(x Generator) string {
	return fmt.Sprintf("name=%s formula=%s source=%s native=%v hphi=%v quaternionic=%v scalar=%v edge=%v self=%v skew=%v pair_compatible=%v pair_degenerate=%v min_degree=%d char=%s min=%s verdict=%s", x.Name, x.Formula, x.SourceGate, x.Native, x.HphiEndomorphism, x.Quaternionic, x.ScalarResponse, x.EdgeQuotient, x.SelfAdjoint, x.SkewAdjoint, x.PairCompatible, x.PairDegenerate, x.MinimalDegree, x.CharacteristicPolynomial, x.MinimalPolynomial, x.Verdict)
}
func FormatLedger(x GeneratorLedger) string {
	return fmt.Sprintf("executed=%v hphi_dim=%d native=%d hphi_endomorphisms=%d quaternionic=%d pair_degenerate=%d edge=%d no_q4_imported=%v no_observed=%v verdict=%s", x.Executed, x.HphiDimension, x.NativeGeneratorCount, x.NativeHphiEndomorphismCount, x.QuaternionicGeneratorCount, x.PairDegenerateGeneratorCount, x.EdgeQuotientGeneratorCount, x.NoQ4Imported, x.NoObservedInputs, x.Verdict)
}
func FormatClosure(x AlgebraClosure) string {
	return fmt.Sprintf("name=%s generators=%s dim=%d full_End_R=%v commutative=%v noncommuting=%v pair_closed=%v nondeg_capacity=%v canonical_selected=%v coeff_choice=%v min_capacity=%s char_capacity=%s verdict=%s", x.Name, strings.Join(x.Generators, ","), x.Dimension, x.FullEndRHphi, x.Commutative, x.ContainsNoncommutingPairs, x.PairDegeneracyClosed, x.GenericNondegenerateCapacity, x.CanonicalSelectorSelected, x.RequiresCoefficientChoice, x.MinimalPolynomialCapacity, x.CharacteristicCapacity, x.Verdict)
}
func FormatSelector(x SelectorCandidate) string {
	return fmt.Sprintf("name=%s formula=%s native=%v sealed=%v hphi=%v canonical=%v self=%v arbitrary_coeffs=%v pair_degenerate=%v distinct_capacity=%v min_degree=%d char=%s min=%s reduces_yukawa=%v reduces_moduli=%v verdict=%s reason=%s", x.Name, x.Formula, x.Native, x.Sealed, x.HphiEndomorphism, x.Canonical, x.SelfAdjoint, x.UsesArbitraryCoefficients, x.PairDegenerate, x.DistinctEigenvalueCapacity, x.MinimalDegree, x.CharacteristicPolynomial, x.MinimalPolynomial, x.ReducesYukawaCouplings, x.ReducesFlavorModuli, x.Verdict, x.Reason)
}
func FormatImpact(x ModuliImpact) string {
	return fmt.Sprintf("charged_start=%d charged_result=%d native_selector=%v full_capacity=%v canonical_flavor_texture=%v yukawa_reduced=%v ckm_capacity=%v scalar_flavor_blind=%v firewall=%v verdict=%s", x.ChargedModuliStart, x.ChargedModuliResult, x.NativeSelectorDerived, x.FullAlgebraNondegenerateCapacity, x.CanonicalFlavorTextureDerived, x.YukawaCouplingsReduced, x.CKMCapacityDerived, x.ScalarSectorFlavorBlind, x.FlavorFirewallPreserved, x.Verdict)
}
func FormatFirewall(x FirewallAudit) string {
	return fmt.Sprintf("executed=%v no_masses=%v no_ckm=%v no_pmns=%v no_yukawa=%v no_q4_forcing=%v no_arbitrary_coeff_promoted=%v no_generic_matrix_promoted=%v no_moduli_reduction=%v verdict=%s", x.Executed, x.NoObservedMassesImported, x.NoCKMImported, x.NoPMNSImported, x.NoYukawaAmplitudesInserted, x.NoQ4HphiForcing, x.NoArbitraryCoefficientPromoted, x.NoGenericMatrixPromoted, x.NoFlavorModuliReductionClaimed, x.Verdict)
}
func FormatNext(x NextStep) string {
	return fmt.Sprintf("gate=%d title=%s reason=%s primary_task=%s", x.Gate, x.Title, x.Reason, x.PrimaryTask)
}
