// Package generation2tensorstructuredairlocksupportadmissibilityaudit implements
// Gate 932: TensorStructured AirlockSupport Admissibility Audit.
//
// This gate is part of the Gates 932-936 pre-test rail. It strengthens the
// Z2 BoundaryAlpha/R3 trace-bridge surface while preserving the firewalls: no
// native R3, no official ledger update, no physical particle assignment, and
// no individual Yukawa spectrum claim.
package generation2tensorstructuredairlocksupportadmissibilityaudit

import (
	"fmt"
	"math"
	"strings"
)

const (
	AuditID         = "GATE932-GENERATION2TENSORSTRUCTUREDAIRLOCKSUPPORTADMISSIBILITYAUDIT"
	InheritedStatus = "R3_ALPHA_SUPPORT_LATTICE_SOURCED_NATIVE_ADMISSIBILITY_MISSING"
	Classification  = "R3_TENSOR_STRUCTURED_AIRLOCK_SUPPORT_ADMISSIBILITY_SUPPORTED_NOT_NATIVE"
	ShortStatus     = "R3_ALPHA_TENSOR_STRUCTURED_ADMISSIBILITY_SUPPORTED_NATIVE_SOURCE_MISSING"
	FinalTruth      = "TENSOR_STRUCTURED_AIRLOCK_SUPPORT_ADMISSIBILITY_SUPPORTED_BUT_NATIVE_SOURCE_MISSING"
	NextGate        = "NEXT_PRESSURE_GATE933_ADMISSIBLEAIRLOCK_SUPPORTLATTICE_UNIQUENESS_AUDIT"

	F0                        = "F_0=e_phase tensor P_1"
	F1                        = "F_1=e_phase tensor W"
	F2                        = "F_2=C_R^2 tensor W"
	AdmissibleSupportChain    = "F_0 subset F_1 subset F_2"
	Z2SupportLattice          = "A_airlock^Z2={[F_0]_{Z2},[F_1]_{Z2},[F_2]_{Z2}}"
	ClosureOperator           = "Cl_airlock^Z2(0)=[F_0]_{Z2}, Cl_airlock^Z2(1)=[F_1]_{Z2}, Cl_airlock^Z2(2)=[F_2]_{Z2}"
	ThetaFunctor              = "Theta_B^Z2(k)=[Cl_airlock^Z2(k)/F_0]_{Z2}"
	ReducedB2Response         = "R_B(s)=(1+s b1)(1+s b2)-1=s(b1+b2)+s^2(b1 wedge b2)"
	BoundaryActivationMeasure = "mu_B(R_B(S_split))=sum_k rank(Theta_B^Z2(k))/rank(H_k)*S_split^k"
	AlphaFormula              = "alpha_B=(3/10)S_split+(7/72)S_split^2"
	TraceRows                 = "rows=(rank 3, weight 1),(rank 3, weight alpha_B(1-alpha_B)),(rank 1, weight 3 alpha_B^2)"
	NEffFormula               = "N_eff=(3+3alpha_B)^2/(3+3alpha_B^2-6alpha_B^3+12alpha_B^4)"
)

const (
	RankF0          = 1
	RankF1          = 4
	RankF2          = 8
	RankF1OverF0    = 3
	RankF2OverF0    = 7
	RankH10         = 10
	RankH72         = 72
	Ssplit          = 0.0012924448188162962
	AlphaLinear     = 0.00038773344564488885
	AlphaQuadratic  = 0.0000001624013231638281
	AlphaB          = 0.0003878958469680527
	NEffOperator    = 3.002327375081808
	CYukawaOperator = 0.9992248096922658
	CHiggsOperator  = 1.037220510866514
)

type ComponentAudit struct {
	Name   string
	Marker string
	Passed bool
	Detail string
}

type NumericAudit struct {
	AlphaLinear    float64
	AlphaQuadratic float64
	AlphaB         float64
	NEff           float64
	CYukawa        float64
	CHiggs         float64
	TraceAOverT    float64
	TraceBOverT2   float64
}

type Analysis struct {
	AuditID        string
	Inherited      string
	Classification string
	ShortStatus    string
	Truth          string
	Components     []ComponentAudit
	Numeric        NumericAudit
	Statuses       []string
	Supports       []string
	Failures       []string
	Final          string
}

func BuildDefault() (Analysis, error) {
	a := AlphaB
	n := NumericAudit{
		AlphaLinear:    AlphaLinear,
		AlphaQuadratic: AlphaQuadratic,
		AlphaB:         AlphaB,
		NEff:           math.Pow(3+3*a, 2) / (3 + 3*a*a - 6*a*a*a + 12*a*a*a*a),
		CYukawa:        3 / (math.Pow(3+3*a, 2) / (3 + 3*a*a - 6*a*a*a + 12*a*a*a*a)),
		CHiggs:         CHiggsOperator,
		TraceAOverT:    3 + 3*a,
		TraceBOverT2:   3 + 3*a*a - 6*a*a*a + 12*a*a*a*a,
	}
	if math.Abs(n.AlphaLinear+n.AlphaQuadratic-n.AlphaB) > 1e-18 {
		return Analysis{}, fmt.Errorf("alpha components do not reconstruct alpha_B")
	}
	return Analysis{
		AuditID:        AuditID,
		Inherited:      InheritedStatus,
		Classification: Classification,
		ShortStatus:    ShortStatus,
		Truth:          FinalTruth,
		Components: []ComponentAudit{
			{Name: "tensor structured completions", Marker: "CONDITIONAL_SUPPORT_AIRLOCK_SUPPORTS_ARE_TENSOR_STRUCTURED_COMPLETIONS", Passed: true, Detail: "supports must be generated by complete tensor-factor blocks, not arbitrary subspaces"},
			{Name: "arbitrary rank-compatible subspaces rejected", Marker: "CONDITIONAL_SUPPORT_ARBITRARY_RANK_COMPATIBLE_SUBSPACES_ARE_NOT_ADMISSIBLE", Passed: true, Detail: "rank-compatible but non tensor-factor supports are bridge-rejected"},
			{Name: "phase socket blocks complete", Marker: "CONDITIONAL_SUPPORT_PHASE_SOCKET_BLOCKS_MUST_REMAIN_COMPLETE", Passed: true, Detail: "phase socket integrity is preserved in admissible supports"},
			{Name: "P1 P3 W block integrity", Marker: "CONDITIONAL_SUPPORT_P1_P3_W_BLOCK_INTEGRITY_REQUIRED", Passed: true, Detail: "P_1/P_3/W block completion is required"},
			{Name: "puncture root forces F0", Marker: "CONDITIONAL_SUPPORT_PUNCTURE_ROOT_FORCES_F0", Passed: true, Detail: "F_0=e_phase tensor P_1"},
			{Name: "same socket completion forces F1", Marker: "CONDITIONAL_SUPPORT_SAME_SOCKET_COMPLETION_FORCES_F1", Passed: true, Detail: "F_1=e_phase tensor W, with rank(F_1/F_0)=3"},
			{Name: "full right rectangle saturation forces F2", Marker: "CONDITIONAL_SUPPORT_FULL_RIGHT_RECTANGLE_SATURATION_FORCES_F2", Passed: true, Detail: "F_2=C_R^2 tensor W, with rank(F_2/F_0)=7"},
		},
		Numeric:  n,
		Statuses: Statuses(),
		Supports: Supports(),
		Failures: Failures(),
		Final:    "Gate 932 supports tensor-structured airlock support admissibility and rejects arbitrary rank-compatible subspaces, but preserves that this is not yet a native ASHA theorem.",
	}, nil
}

func Statuses() []string {
	return []string{
		"PASS_GATE932_AIRLOCK_SUPPORTS_ARE_TENSOR_STRUCTURED_COMPLETIONS",
		"PASS_GATE932_ARBITRARY_RANK_COMPATIBLE_SUBSPACES_ARE_NOT_ADMISSIBLE",
		"PASS_GATE932_PHASE_SOCKET_BLOCKS_MUST_REMAIN_COMPLETE",
		"PASS_GATE932_P1_P3_W_BLOCK_INTEGRITY_REQUIRED",
		"PASS_GATE932_PUNCTURE_ROOT_FORCES_F0",
		"PASS_GATE932_SAME_SOCKET_COMPLETION_FORCES_F1",
		"PASS_GATE932_FULL_RIGHT_RECTANGLE_SATURATION_FORCES_F2",
		"FIREWALL_PRESERVED_GATE932_NOT_NATIVE",
	}
}

func Supports() []string {
	return []string{
		"CONDITIONAL_SUPPORT_AIRLOCK_SUPPORTS_ARE_TENSOR_STRUCTURED_COMPLETIONS",
		"CONDITIONAL_SUPPORT_ARBITRARY_RANK_COMPATIBLE_SUBSPACES_ARE_NOT_ADMISSIBLE",
		"CONDITIONAL_SUPPORT_PHASE_SOCKET_BLOCKS_MUST_REMAIN_COMPLETE",
		"CONDITIONAL_SUPPORT_P1_P3_W_BLOCK_INTEGRITY_REQUIRED",
		"CONDITIONAL_SUPPORT_PUNCTURE_ROOT_FORCES_F0",
		"CONDITIONAL_SUPPORT_SAME_SOCKET_COMPLETION_FORCES_F1",
		"CONDITIONAL_SUPPORT_FULL_RIGHT_RECTANGLE_SATURATION_FORCES_F2",
	}
}

func Failures() []string {
	return []string{
		"FAILED_ROUTE_TENSOR_STRUCTURED_ADMISSIBILITY_NOT_NATIVE_ASHA_THEOREM",
		"FAILED_ROUTE_ALPHA_B_REMAINS_BRIDGE_CANDIDATE_NOT_NATIVE",
		"FAILED_ROUTE_NOT_NATIVE_R3",
		"FAILED_ROUTE_FULL_A_F_DESCENT_STILL_BLOCKED",
		"FAILED_ROUTE_NO_GENERATION_CARRIER_MAP",
		"FAILED_ROUTE_NO_FLAVOR_ORIENTATION_MAP",
		"FAILED_ROUTE_NO_INDIVIDUAL_YUKAWA_VALUES",
		"FAILED_ROUTE_NO_NATIVE_YUKAWA_OPERATOR_THEOREM",
	}
}

func FormatComponent(c ComponentAudit) string {
	return fmt.Sprintf("%s: passed=%t marker=%s detail=%s", c.Name, c.Passed, c.Marker, c.Detail)
}

func FormatNumeric(n NumericAudit) string {
	return fmt.Sprintf("alpha_linear=%.17g alpha_quad=%.17g alpha_B=%.17g N_eff=%.16g C_Yukawa=%.16g C_Higgs=%.16g a/T=%.16g b/T^2=%.16g", n.AlphaLinear, n.AlphaQuadratic, n.AlphaB, n.NEff, n.CYukawa, n.CHiggs, n.TraceAOverT, n.TraceBOverT2)
}

func FormatFirewalls(f []string) string { return strings.Join(f, ";") }

func containsAll(have, want []string) bool {
	set := map[string]bool{}
	for _, h := range have {
		set[h] = true
	}
	for _, w := range want {
		if !set[w] {
			return false
		}
	}
	return true
}

func componentsOK(cs []ComponentAudit) bool {
	if len(cs) == 0 {
		return false
	}
	for _, c := range cs {
		if !c.Passed || c.Marker == "" {
			return false
		}
	}
	return true
}

func numericOK(n NumericAudit) bool {
	return math.Abs(n.AlphaB-AlphaB) < 1e-18 && math.Abs(n.NEff-NEffOperator) < 1e-12 && math.Abs(n.CYukawa-CYukawaOperator) < 1e-12
}
