package contactzeta

import (
	"fmt"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func FiniteContactSpectralZetaRegularizationSevenRootActionFunctionalAuditTheorem() theorem.Theorem {
	const id = "BRIDGE-CONTACT-ZETA-SEVEN-ROOT-SPECTRAL-ACTION-FIREWALL"
	const name = "Finite contact spectral zeta regularization / seven-root action functional audit"
	return theorem.Theorem{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.Variational, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build contact zeta theorem", Passed: false, Detail: err.Error()}}}
		}
		return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.Variational, Checks: []theorem.Check{
			{Name: "Gate 161 collective spectral firewall is inherited", Passed: a.Previous.BetaPermissionFirewallClosed && a.Previous.QuarticCollectiveBlocks == 1 && a.Previous.ContactBetaRowsAllowed == 0 && a.Previous.ContactZeroRowsProved == 0 && a.Previous.BoundaryConstraintsDerived == 0 && !a.Previous.HiddenObservedInputUsed, Detail: fmt.Sprintf("collectiveBlocks=%d beta=%d zero=%d constraints=%d hiddenObserved=%t", a.Previous.QuarticCollectiveBlocks, a.Previous.ContactBetaRowsAllowed, a.Previous.ContactZeroRowsProved, a.Previous.BoundaryConstraintsDerived, a.Previous.HiddenObservedInputUsed)},
			{Name: "finite zeta ledger has exact seven-root values", Passed: len(a.ZetaValues) == 5 && a.ZetaValues[0].Full.Equal(NewRational(7, 1)) && a.ZetaValues[1].Full.Equal(NewRational(7993, 542)) && a.ZetaValues[2].Full.Equal(NewRational(10529233, 293764)) && a.ZetaValues[3].Full.Equal(NewRational(15529024549, 159220088)) && a.ZetaValues[4].Full.Equal(NewRational(24783201328945, 86297287696)), Detail: FormatZetaList(a.ZetaValues)},
			{Name: "quartic inverse Newton ledger is Galois-invariant and branch-free", Passed: a.ZetaValues[0].QuarticPart.Equal(NewRational(4, 1)) && a.ZetaValues[1].QuarticPart.Equal(NewRational(2235, 271)) && a.ZetaValues[2].QuarticPart.Equal(NewRational(1512333, 73441)) && a.ZetaValues[3].QuarticPart.Equal(NewRational(1177369209, 19902511)) && a.ZetaValues[4].QuarticPart.Equal(NewRational(998467775217, 5393580481)) && a.ZetaAudit.ExactRationalValues == 5 && a.ZetaAudit.GaloisInvariantValues == 5 && a.ZetaAudit.BranchFreeValues == 5 && a.ZetaAudit.BranchChoicesUsed == 0, Detail: FormatZetaAudit(a.ZetaAudit)},
			{Name: "finite zeta regularization is pole-free and needs no analytic continuation", Passed: a.PositiveNonzeroSpectrumRows == 7 && a.FiniteZetaPoleCount == 0 && !a.AnalyticContinuationNeeded && a.ZetaAudit.Poles == 0 && !a.ZetaAudit.AnalyticContinuationNeeded && a.ZetaAudit.PositiveNonzeroSpectrumRows == 7 && a.ZetaAudit.ZetaZeroEqualsDimension && a.ZetaAudit.FiniteRegularizationComplete, Detail: FormatZetaAudit(a.ZetaAudit)},
			{Name: "zeta/action candidates do not select boundary normalizations", Passed: a.ActionAudit.CandidatesAudited == 10 && !a.ActionAudit.ObservedInputsUsed && a.ActionAudit.BranchChoicesUsed == 0 && !a.ActionAudit.RowSemanticsUsed && a.ActionAudit.RequiresSpectralTriple == 10 && a.ActionAudit.RequiresCutoffFunction == 10 && a.ActionAudit.CanonicalCoefficients == 0 && !a.ActionAudit.FiniteDiracSelected && !a.ActionAudit.RealStructureSelected && !a.ActionAudit.GradingSelected && !a.ActionAudit.GaugeKineticMapDerived && a.ActionAudit.BoundaryConstraintsDerived == 0 && a.ActionAudit.MatchesKappaU1 == 0 && a.ActionAudit.MatchesEmbeddedBoundary == 0 && a.ActionAudit.MatchesContactWeakAngle == 0 && a.ActionAudit.MatchesGeneratorWeakAngle == 0 && !a.ActionAudit.NewActionNormalization && !a.ActionAudit.PhysicalConstantsDerived, Detail: FormatActionAudit(a.ActionAudit) + " :: " + FormatActionCandidateList(a.ActionCandidates)},
			{Name: "contact zeta data preserve the beta-permission firewall", Passed: a.BetaFirewall.FiniteZetaData && !a.BetaFirewall.SpectralTripleComplete && !a.BetaFirewall.CanonicalCutoffSelected && a.BetaFirewall.GaugeKineticMapRows == 0 && a.BetaFirewall.IndividualQuarticRows == 0 && a.BetaFirewall.GaugeRepresentationRows == 0 && a.BetaFirewall.SpinStatisticsRows == 0 && a.BetaFirewall.LocalFieldRows == 0 && a.BetaFirewall.MassActivationRows == 0 && a.BetaFirewall.DecouplingRows == 0 && a.BetaFirewall.DynkinIndexRows == 0 && a.BetaFirewall.ThresholdBetaRows == 0 && a.BetaFirewall.ProvenZeroRows == 0 && !a.BetaFirewall.PhysicalConstantsDerived && a.BetaFirewall.BetaPermissionFirewallClosed, Detail: FormatBetaFirewall(a.BetaFirewall)},
			{Name: "physical constants and threshold rows remain sealed", Passed: a.ContactRows == 7 && a.RationalSingletonRows == 3 && a.QuarticOrbitRows == 4 && a.QuarticCollectiveBlocks == 1 && a.ContactZetaValues == 5 && a.SpectralActionCandidates == 10 && !a.SpectralTripleComplete && !a.FiniteDiracSelected && !a.RealStructureSelected && !a.GradingSelected && !a.CanonicalCutoffSelected && a.GaugeKineticMapRows == 0 && a.IndividualQuarticRows == 0 && a.CanonicalQuarticBranches == 0 && a.ExternalSelectorRows == 0 && a.CanonicalTwoTwoSplits == 0 && a.BranchBreakingSources == 0 && a.GaugeRepresentationRows == 0 && a.LocalFieldRows == 0 && a.MassActivationRows == 0 && a.DecouplingRows == 0 && a.DynkinIndexRows == 0 && a.QuarticBlockBetaRows == 0 && a.ContactBetaRowsAllowed == 0 && a.ContactZeroRowsProved == 0 && a.BetaPermissionFirewallClosed && !a.ThresholdCorrectedBeta && !a.FullBetaMatchingTensor && a.BoundaryConstraintsDerived == 0 && a.ResidualNullityBefore == 3 && a.ResidualNullityAfter == 3 && !a.HiddenObservedInputUsed && !a.PhysicalWeakAngleDerived && !a.FineStructureDerived && !a.PhysicalMassesDerived && !a.PhysicalScaleDerived, Detail: FormatSummary(a.Summary) + " :: " + a.TruthStatement},
		}}
	}}
}
