package generation2finiteactionsecondvariation

import "github.com/bagherbal/asha-engine/pkg/theorem"

func Generation2FiniteElectroweakActionSecondVariationSourceAuditTheorem() theorem.Theorem {
	const id = AuditID
	const name = "Generation 2 finite electroweak action second variation source audit"
	return theorem.Theorem{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "construct Gate495 finite action second variation audit", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherits Gate494 kappa obstruction", Passed: a.Inheritance.Executed && a.Inheritance.Gate494AuditDefined && a.Inheritance.TraceNormalizationDoesNotSelectKappa && a.Inheritance.RepresentationMetricNotGaugeHessian && a.Inheritance.KappaTargetSixWhiteningCandidate && a.Inheritance.FiniteActionSecondVariationRequested && a.Inheritance.NoElectroweakFlavorDataImported, Detail: FormatInheritance(a.Inheritance)},
			{Name: "finds canonical second-variation candidate", Passed: a.Candidate.Executed && a.Candidate.CanonicalActionPackageAvailable && a.Candidate.CanonicalActionSelectedInCandidate && a.Candidate.SecondVariationComputed && a.Candidate.ScalarKineticSelectedInCandidate && a.Candidate.ActiveRealDimension == 4 && a.Candidate.BrokenImageRank == 3 && a.Candidate.BrokenDiag114, Detail: FormatCandidate(a.Candidate)},
			{Name: "candidate selects kappa_U1=6 and positive rank-four Hessian", Passed: a.Candidate.KappaSixSelectedInCandidate && a.Candidate.KappaU1 == 6 && a.Candidate.FullGaugeHessianSelectedInCandidate && a.Candidate.FullGaugeHessianPositive && a.Candidate.FullGaugeHessianRank == 4 && a.Candidate.BrokenRestrictionMatches && !a.Candidate.PhysicalCouplingsDerived && !a.Candidate.PhysicalMassesDerived && !a.Candidate.CKMPMNSDerived && !a.Candidate.HiddenObservedInputUsed, Detail: FormatCandidate(a.Candidate)},
			{Name: "blocks native promotion on provenance", Passed: a.Provenance.Executed && !a.Provenance.Gate492NativeDphiDerived && !a.Provenance.Gate492CanonicalGoldstoneIntertwiner && !a.Provenance.Gate492FullScalarSU2ActionNativeSelected && !a.Provenance.Gate492ScalarVacuumOrientationNative && !a.Provenance.Gate492ScalarKineticMetricNative && !a.Provenance.Gate493SecondVariationComputed && !a.Provenance.Gate493AbelianCoefficientSelected && !a.Provenance.Gate493GaugeHessianActionSelected && a.Provenance.CanonicalCandidateUsesDiagnosticDphi && a.Provenance.CanonicalCandidateUsesI4Metric && a.Provenance.CanonicalCandidateUsesChosenVacuum && a.Provenance.CanonicalCandidateUsesMinimalActionChoice && !a.Provenance.NativeActionProvenanceClosed && !a.Provenance.NativeKappaSelectionClosed && !a.Provenance.NativeGaugeHessianSelectionClosed, Detail: FormatProvenance(a.Provenance)},
			{Name: "accepts dimensionless Hessian only as bridge candidate", Passed: a.Boundary.Executed && a.Boundary.DimensionlessSecondVariationCandidate && a.Boundary.Diag114AcceptedAsBridgeCandidate && a.Boundary.KappaSixAcceptedAsBridgeCandidate && a.Boundary.FullHessianAcceptedAsBridgeCandidate && !a.Boundary.NativeKappaSelected && !a.Boundary.NativeGaugeHessianSelected && !a.Boundary.NativeWeakAngleDerived && !a.Boundary.NativeGaugeCouplingsDerived && !a.Boundary.NativeWZMassesDerived && !a.Boundary.NativeHiggsVEVDerived && !a.Boundary.PhysicalElectroweakRegistryWrite, Detail: FormatBoundary(a.Boundary)},
			{Name: "preserves electroweak and flavor firewall", Passed: a.Firewall.Executed && !a.Firewall.ObservedWMassImported && !a.Firewall.ObservedZMassImported && !a.Firewall.ObservedHiggsMassImported && !a.Firewall.FermiConstantImported && !a.Firewall.WeakAngleImported && !a.Firewall.FineStructureImported && !a.Firewall.GaugeCouplingImported && !a.Firewall.YukawaImported && !a.Firewall.CKMPMNSImported && !a.Firewall.NativeKappaWritten && !a.Firewall.NativeGaugeHessianWritten && !a.Firewall.NativeWeakAngleWritten && !a.Firewall.NativeGaugeCouplingWritten && !a.Firewall.NativeWZMassWritten && !a.Firewall.NativeHiggsVEVWritten, Detail: FormatFirewall(a.Firewall)},
		}
		return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: []string{StatusGate494Inherited, StatusCanonicalActionCandidateFound, StatusBrokenOrbitDiag114Reproduced, StatusKappaSixSelectedInsideCandidate, StatusFullHessianCandidatePositive, StatusDimensionlessHessianBridgeAccepted, StatusProvenanceAirlockDefined, StatusFailedCanonicalActionNotNativeClosed, StatusFailedNativeDphiStillAbstract, StatusFailedScalarKineticMetricNotNative, StatusFailedVacuumOrientationNotNative, StatusFailedFullScalarSU2ActionNotSelected, StatusFailedGaugeHessianNativeNotSelected, StatusFailedPhysicalCouplingsNotDerived, StatusFailedWeakAngleNotDerived, StatusFailedWZMassesNotDerived, StatusFirewallPreserved, StatusNativeRegistryWriteBlocked, StatusGate496RedirectDefined, a.Truth}}
	}}
}
