package g2

import (
	"fmt"
	"math"

	"github.com/bagherbal/asha-engine/pkg/combinatorics"
	"github.com/bagherbal/asha-engine/pkg/linear"
	"github.com/bagherbal/asha-engine/pkg/octonion"
)

type CalibrationSupport struct {
	VectorDimension int
	MiddleGrade     int
	Basis           []combinatorics.Subset
	Associative     octonion.AssociativeForm
	Coassociative   octonion.CoassociativeForm
	RawColumns      linear.Matrix
	Orthonormal     linear.Matrix
	Support         linear.Projector
	GramEigenvalues []float64
}

func BuildCalibrationSupport() (CalibrationSupport, error) {
	const vectorDimension = 8
	const middleGrade = 4
	basis, err := combinatorics.Subsets(vectorDimension, middleGrade)
	if err != nil {
		return CalibrationSupport{}, err
	}
	basisIndex := combinatorics.IndexByKey(basis)
	phi := octonion.StandardAssociativeForm()
	psi := octonion.StandardCoassociativeForm(phi)

	cols := linear.NewMatrix(len(basis), 14)

	// First copy: 7_t inside e₀ ∧ Λ³R⁷, generated by contractions of *φ.
	for a := 0; a < 7; a++ {
		col := a
		for _, triple := range mustSubsets(7, 3) {
			coeff := psi.Value(a, triple[0], triple[1], triple[2])
			if math.Abs(coeff) == 0 {
				continue
			}
			subset := combinatorics.Subset{0, triple[0] + 1, triple[1] + 1, triple[2] + 1}
			row, ok := basisIndex[subset.Key()]
			if !ok {
				return CalibrationSupport{}, fmt.Errorf("missing Λ⁴ basis row for subset %v", subset)
			}
			cols.Set(row, col, cols.At(row, col)+coeff)
		}
	}

	// Second copy: 7_s inside Λ⁴R⁷, generated by φ through the Hodge-dual copy.
	for a := 0; a < 7; a++ {
		col := 7 + a
		for _, quad := range mustSubsets(7, 4) {
			if !containsInt(quad, a) {
				continue
			}
			rest := make([]int, 0, 3)
			for _, v := range quad {
				if v != a {
					rest = append(rest, v)
				}
			}
			seq := append([]int{a}, rest...)
			coeff := float64(paritySign(seq)) * phi.Value(rest[0], rest[1], rest[2])
			if math.Abs(coeff) == 0 {
				continue
			}
			subset := combinatorics.Subset{quad[0] + 1, quad[1] + 1, quad[2] + 1, quad[3] + 1}
			row, ok := basisIndex[subset.Key()]
			if !ok {
				return CalibrationSupport{}, fmt.Errorf("missing Λ⁴ basis row for subset %v", subset)
			}
			cols.Set(row, col, cols.At(row, col)+coeff)
		}
	}

	orthonormal, values, err := orthonormalizeColumns(cols)
	if err != nil {
		return CalibrationSupport{}, err
	}
	projectorMatrix, err := orthonormal.Mul(orthonormal.Transpose())
	if err != nil {
		return CalibrationSupport{}, err
	}
	projector, err := linear.NewProjector("P_G", projectorMatrix)
	if err != nil {
		return CalibrationSupport{}, err
	}
	return CalibrationSupport{
		VectorDimension: vectorDimension,
		MiddleGrade:     middleGrade,
		Basis:           basis,
		Associative:     phi,
		Coassociative:   psi,
		RawColumns:      cols,
		Orthonormal:     orthonormal,
		Support:         projector,
		GramEigenvalues: values,
	}, nil
}

func (s CalibrationSupport) MiddleDimension() int { return len(s.Basis) }

func (s CalibrationSupport) SectorDimension() int { return s.Orthonormal.Cols() }

func (s CalibrationSupport) IsometryResidual() (float64, error) {
	qtq, err := s.Orthonormal.Transpose().Mul(s.Orthonormal)
	if err != nil {
		return 0, err
	}
	diff, err := qtq.Sub(linear.Identity(s.SectorDimension()))
	if err != nil {
		return 0, err
	}
	return diff.FrobeniusNorm(), nil
}

func (s CalibrationSupport) RankFromGram(eps float64) int {
	return linear.RankFromEigenvalues(s.GramEigenvalues, eps)
}

func orthonormalizeColumns(cols linear.Matrix) (linear.Matrix, []float64, error) {
	gram, err := cols.Transpose().Mul(cols)
	if err != nil {
		return linear.Matrix{}, nil, err
	}
	eig, err := linear.SymmetricEigenJacobi(gram, 1e-13, 0)
	if err != nil {
		return linear.Matrix{}, nil, err
	}
	values, vectors, err := linear.SortEigenDescending(eig.Values, eig.Vectors)
	if err != nil {
		return linear.Matrix{}, nil, err
	}
	invSqrt := linear.NewMatrix(len(values), len(values))
	for i, value := range values {
		if value <= 0 {
			return linear.Matrix{}, nil, fmt.Errorf("G₂ calibration Gram matrix has non-positive eigenvalue at %d: %.16g", i, value)
		}
		invSqrt.Set(i, i, 1/math.Sqrt(value))
	}
	cv, err := cols.Mul(vectors)
	if err != nil {
		return linear.Matrix{}, nil, err
	}
	cvis, err := cv.Mul(invSqrt)
	if err != nil {
		return linear.Matrix{}, nil, err
	}
	q, err := cvis.Mul(vectors.Transpose())
	if err != nil {
		return linear.Matrix{}, nil, err
	}
	return q, values, nil
}

func mustSubsets(n, k int) []combinatorics.Subset {
	sets, err := combinatorics.Subsets(n, k)
	if err != nil {
		panic(err)
	}
	return sets
}

func containsInt(values []int, needle int) bool {
	for _, v := range values {
		if v == needle {
			return true
		}
	}
	return false
}

func paritySign(values []int) int {
	inv := 0
	for i := 0; i < len(values); i++ {
		for j := i + 1; j < len(values); j++ {
			if values[i] > values[j] {
				inv++
			}
		}
	}
	if inv%2 == 0 {
		return 1
	}
	return -1
}
