package generation2scalarbaselineandk7boundarysplitupliftobservableaudit

import (
	"math"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2ScalarBaselineAndK7BoundarySplitUpliftObservableAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 705 — Scalar Baseline and K7 Boundary-Split Uplift Observable Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 705 — Scalar Baseline and K7 Boundary-Split Uplift Observable Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate704 boundary wound mixture", Passed: a.Inherited.BoundaryWoundMixtureInherited && a.Inherited.EventComplementMeaning && a.Inherited.KSumExpectedBoundaryWound && math.Abs(a.Inherited.K7EventProbability-pK7) < tolerance && math.Abs(a.Inherited.ComplementEventProbability-pComplement) < tolerance && math.Abs(a.Inherited.ExpectedWound-0.0498265964350682) < 5e-16 && math.Abs(a.Inherited.Residual-8.5258344e-10) < 1e-16 && a.Inherited.NoNativeBoundaryWoundMixture && a.Inherited.NoNativeHistoryResponse && a.Inherited.NoNativeSevenOver72 && a.Inherited.Verdict == StatusGate704BoundaryWoundMixtureInherited, Detail: FormatInheritance(a.Inherited)},
			{Name: "rewrite two-payoff observable", Passed: strings.Contains(a.Rewrite.Gate704Observable, "P_perp") && strings.Contains(a.Rewrite.ProjectorIdentity, "I_H72-P_K7") && strings.Contains(a.Rewrite.RewrittenObservable, "|lambda|I_H72") && strings.Contains(a.Rewrite.RewrittenObservable, "S_split P_K7") && math.Abs(a.Rewrite.K7PayoffBefore-r3Minus1) < tolerance && math.Abs(a.Rewrite.ComplementPayoffBefore-math.Abs(lambdaLambda12)) < tolerance && a.Rewrite.AlgebraicEquivalence && a.Rewrite.Verdict == StatusTwoPayoffObservableRewritten, Detail: FormatRewrite(a.Rewrite)},
			{Name: "compute scalar baseline plus K7 uplift", Passed: math.Abs(a.Decomposition.ScalarBaseline-math.Abs(lambdaLambda12)) < tolerance && math.Abs(a.Decomposition.BoundarySplitUplift-(r3Minus1-math.Abs(lambdaLambda12))) < tolerance && math.Abs(a.Decomposition.SFromSignedSplit-(lambdaLambda12+r3Minus1)) < tolerance && math.Abs(a.Decomposition.K7PayoffAfterUplift-r3Minus1) < tolerance && a.Decomposition.FullChamberBaseline && a.Decomposition.K7LocalizedUplift && a.Decomposition.K7PayoffEqualsGaugeWound && strings.Contains(a.Decomposition.Verdict, StatusScalarBaselineK7UpliftDecompositionComputed) && strings.Contains(a.Decomposition.Verdict, StatusK7ReceivesSplitUpliftNotPrimitiveGaugeWound), Detail: FormatDecomposition(a.Decomposition)},
			{Name: "expectation reproduces K_sum closure", Passed: strings.Contains(a.Expectation.Formula, "|lambda|") && strings.Contains(a.Expectation.Formula, "p_K7 S_split") && math.Abs(a.Expectation.BaselineExpectation-math.Abs(lambdaLambda12)) < tolerance && math.Abs(a.Expectation.UpliftExpectation-pK7*(lambdaLambda12+r3Minus1)) < tolerance && math.Abs(a.Expectation.TotalExpectation-0.0498265964350682) < 5e-16 && math.Abs(a.Expectation.KSum-0.0498265972876517) < 5e-16 && math.Abs(a.Expectation.Residual-8.5258344e-10) < 1e-16 && a.Expectation.ReproducesKSumClosure && a.Expectation.EquivalentToGate704 && strings.Contains(a.Expectation.Verdict, StatusKSumScalarBaselineExpectedK7SplitUplift), Detail: FormatExpectation(a.Expectation)},
			{Name: "audit relation to Gate700 response law", Passed: strings.Contains(a.Relation.Gate700ResponseLaw, "D_base") && strings.Contains(a.Relation.PositiveDistanceLaw, "K_sum") && math.Abs(a.Relation.DBase-(kappaLambda+kappaE+lambdaLambda12)) < tolerance && math.Abs(a.Relation.KSum-(kappaLambda+kappaE)) < tolerance && math.Abs(a.Relation.ScalarDepth-math.Abs(lambdaLambda12)) < tolerance && math.Abs(a.Relation.ExpectedSplitUplift-pK7*(lambdaLambda12+r3Minus1)) < tolerance && strings.Contains(a.Relation.BaselineIdentity, "K_sum=|lambda|+D_base") && a.Relation.NotNewNumericalRelation && a.Relation.Verdict == StatusRelationToGate700ResponseLawAudited, Detail: FormatRelation(a.Relation)},
			{Name: "audit source-type upgrade", Passed: strings.Contains(a.SourceUpgrade.Gate704Reading, "gauge wound") && strings.Contains(a.SourceUpgrade.Gate705Reading, "scalar wound baseline") && a.SourceUpgrade.RemovesPrimitiveGaugeAssignment && a.SourceUpgrade.K7ReceivesBoundarySplitUplift && a.SourceUpgrade.ScalarWallAirlockSupportsBaseline && strings.Contains(a.SourceUpgrade.Verdict, StatusSourceTypeUpgradeAudited) && strings.Contains(a.SourceUpgrade.Verdict, StatusScalarWallAirlockSupportsScalarBaseline), Detail: FormatSourceUpgrade(a.SourceUpgrade)},
			{Name: "audit alternative baseline decompositions", Passed: len(a.Alternatives.Alternatives) == 4 && a.Alternatives.GaugeBaselineRejected && a.Alternatives.MidpointBaselineRejected && a.Alternatives.HodgeSignedUpliftRejected && a.Alternatives.ActiveBaselineAccepted && a.Alternatives.Alternatives[0].Equivalent && !a.Alternatives.Alternatives[1].Equivalent && !a.Alternatives.Alternatives[2].Equivalent && a.Alternatives.Alternatives[3].Active && a.Alternatives.Verdict == StatusAlternativeBaselineDecompositionsAudited, Detail: FormatAlternatives(a.Alternatives)},
			{Name: "preserve missing theorem boundary", Passed: len(a.Missing.Missing) == 5 && strings.Contains(a.Missing.Verdict, StatusNoNativeScalarWoundFullChamberBaseline) && strings.Contains(a.Missing.Verdict, StatusNoNativeK7ReceivesSplitUplift) && strings.Contains(a.Missing.Verdict, StatusNoNativeBoundaryWoundUpliftTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeHistoryResponseTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeSevenOver72Theorem), Detail: FormatMissing(a.Missing)},
			{Name: "preserve Gate705 scalar baseline/K7 uplift firewall", Passed: !a.Firewall.ClaimsScalarWoundFullChamberBaselineNative && !a.Firewall.ClaimsK7ReceivesSplitUpliftNative && !a.Firewall.ClaimsNativeBoundaryWoundUpliftTheorem && !a.Firewall.ClaimsNativeHistoryResponseTheorem && !a.Firewall.ClaimsNativeSevenOver72Theorem && !a.Firewall.ClaimsBoundaryStressDerived && !a.Firewall.ClaimsScalarRGMatching && !a.Firewall.ClaimsHiggsMass && !a.Firewall.ClaimsGaugeUnification && !a.Firewall.ClaimsFlavorDerivation && !a.Firewall.ClaimsCKMPMNS && a.Firewall.Verdict == StatusGate705ScalarBaselineK7UpliftBoundary, Detail: FormatFirewall(a.Firewall)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 705 — Scalar Baseline and K7 Boundary-Split Uplift Observable Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
