// Package generation2ssplitnativeh72scalarsourceaudit implements
// Gate 944: S_split Native H72 Scalar Source Audit.
//
// Gate 944 follows Gate 943's support for the H72-to-B2 descent map. It asks
// the remaining scalar-origin question: is S_split itself a native H72 scalar
// generated by finite chamber data, or does it remain a bridge/history scalar
// inherited from earlier environmental response lanes? The result is
// deliberately conservative: S_split is H72-compatible and response-usable, but
// its expression still contains bridge/history ingredients whose native finite
// chamber derivation is not certified.
package generation2ssplitnativeh72scalarsourceaudit

import (
	"fmt"
	"strings"
)

const (
	AuditID         = "GATE944-GENERATION2SSPLITNATIVEH72SCALARSOURCEAUDIT"
	InheritedStatus = "R3_S_SPLIT_DESCENT_TO_B2_SUPPORTED_SOURCE_NATIVE_STATUS_OPEN"
	Verdict         = "S_SPLIT_IS_H72_COMPATIBLE_AND_DESCENT_READY_BUT_NATIVE_FINITE_CHAMBER_SCALAR_SOURCE_REMAINS_UNCERTIFIED"
	Classification  = "R3_S_SPLIT_NATIVE_H72_SCALAR_SOURCE_AUDITED_NOT_NATIVE"
	ShortStatus     = "R3_S_SPLIT_SOURCE_REMAINS_BRIDGE_HISTORY_SCALAR"
	NextGate        = "NEXT_PRESSURE_GATE945_S_SPLIT_SOURCE_FAILURE_LOCALIZATION_AND_NATIVE_INPUT_OPTIONS_AUDIT"
)

const (
	Ssplit = 0.0012924448188162962
)

type SourceStatus string

const (
	SourceBridgeHistory SourceStatus = "BRIDGE_HISTORY_SCALAR_NOT_NATIVE"
	SourceNativeMissing SourceStatus = "NATIVE_FINITE_CHAMBER_SOURCE_MISSING"
)

type SsplitExpression struct {
	Expression      string
	Value           float64
	Components      []string
	Dimensionless   bool
	H72Compatible   bool
	NativeCertified bool
	Supports        []string
	Failures        []string
}

type ComponentSource struct {
	Name             string
	Role             string
	H72ScalarTyped   bool
	NativeCertified  bool
	BridgeHistoryUse bool
	Supports         []string
	Failures         []string
}

type NativeCriteria struct {
	Required []string
	Passed   []string
	Blocked  []string
	Status   SourceStatus
	Supports []string
	Failures []string
}

type CertificateIIStatus struct {
	DescentSupported  bool
	SourceNative      bool
	CertificatePassed bool
	Status            string
	Supports          []string
	Failures          []string
}

type Analysis struct {
	AuditID        string
	Inherited      string
	Verdict        string
	Classification string
	ShortStatus    string
	Expression     SsplitExpression
	Components     []ComponentSource
	Criteria       NativeCriteria
	Certificate    CertificateIIStatus
	Supports       []string
	Failures       []string
	Final          string
}

func BuildDefault() (Analysis, error) {
	expr := DefaultSsplitExpression()
	components := DefaultComponents()
	criteria := DefaultNativeCriteria()
	certificate := DefaultCertificateIIStatus()
	if expr.Value != Ssplit {
		return Analysis{}, fmt.Errorf("S_split value changed: got %.19g want %.19g", expr.Value, Ssplit)
	}
	if !expr.Dimensionless || !expr.H72Compatible {
		return Analysis{}, fmt.Errorf("S_split must remain dimensionless and H72-compatible: %#v", expr)
	}
	if expr.NativeCertified {
		return Analysis{}, fmt.Errorf("Gate 944 must not certify native S_split source")
	}
	for _, c := range components {
		if c.NativeCertified {
			return Analysis{}, fmt.Errorf("component %s unexpectedly native-certified", c.Name)
		}
	}
	if certificate.SourceNative || certificate.CertificatePassed {
		return Analysis{}, fmt.Errorf("Certificate II must remain blocked by native source status: %#v", certificate)
	}
	return Analysis{
		AuditID:        AuditID,
		Inherited:      InheritedStatus,
		Verdict:        Verdict,
		Classification: Classification,
		ShortStatus:    ShortStatus,
		Expression:     expr,
		Components:     components,
		Criteria:       criteria,
		Certificate:    certificate,
		Supports:       Supports(),
		Failures:       Failures(),
		Final:          "Gate 944 resolves the post-Gate-943 pressure point conservatively: S_split descends correctly once treated as a central H72 scalar, but the scalar itself is not certified as a native finite H72 datum. Its known expression still depends on R3 and lambda(Lambda_12) bridge/history ingredients, so Certificate II and native R3 remain blocked.",
	}, nil
}

func DefaultSsplitExpression() SsplitExpression {
	return SsplitExpression{
		Expression:      "S_split=(R_3-1)+lambda(Lambda_12)",
		Value:           Ssplit,
		Components:      []string{"R_3-1", "lambda(Lambda_12)"},
		Dimensionless:   true,
		H72Compatible:   true,
		NativeCertified: false,
		Supports: []string{
			"CONDITIONAL_SUPPORT_S_SPLIT_IS_DIMENSIONLESS_H72_COMPATIBLE_SCALAR",
			"CONDITIONAL_SUPPORT_GATE943_DESCENT_APPLIES_IF_S_SPLIT_IS_ACCEPTED_AS_H72_SCALAR",
			"CONDITIONAL_SUPPORT_S_SPLIT_EXPRESSION_SOURCE_IS_NOW_EXPLICIT",
		},
		Failures: []string{
			"FAILED_ROUTE_S_SPLIT_NATIVE_H72_SCALAR_SOURCE_NOT_CERTIFIED",
		},
	}
}

func DefaultComponents() []ComponentSource {
	return []ComponentSource{
		{
			Name:             "R_3-1",
			Role:             "dimensionless response deviation component",
			H72ScalarTyped:   true,
			NativeCertified:  false,
			BridgeHistoryUse: true,
			Supports: []string{
				"CONDITIONAL_SUPPORT_R3_MINUS_ONE_HAS_SCALAR_DEVIATION_TYPE",
			},
			Failures: []string{
				"FAILED_ROUTE_R3_MINUS_ONE_NOT_DERIVED_AS_NATIVE_H72_SCALAR",
			},
		},
		{
			Name:             "lambda(Lambda_12)",
			Role:             "history/scale scalar component inherited by the split expression",
			H72ScalarTyped:   true,
			NativeCertified:  false,
			BridgeHistoryUse: true,
			Supports: []string{
				"CONDITIONAL_SUPPORT_LAMBDA_LAMBDA12_HAS_SCALAR_ADDEND_TYPE",
			},
			Failures: []string{
				"FAILED_ROUTE_LAMBDA_LAMBDA12_NOT_DERIVED_AS_NATIVE_H72_SCALAR",
			},
		},
	}
}

func DefaultNativeCriteria() NativeCriteria {
	return NativeCriteria{
		Required: []string{
			"finite H72 chamber derivation of R_3-1",
			"finite H72 chamber derivation of lambda(Lambda_12)",
			"canonical addition law inside H72 scalar lane",
			"no environmental/history matching input",
		},
		Passed: []string{
			"dimensionless scalar type",
			"H72 compatibility",
			"Gate943 central scalar descent readiness",
		},
		Blocked: []string{
			"native finite chamber derivation of R_3-1",
			"native finite chamber derivation of lambda(Lambda_12)",
			"proof that S_split is not an inherited bridge/history scalar",
		},
		Status: SourceNativeMissing,
		Supports: []string{
			"CONDITIONAL_SUPPORT_S_SPLIT_NATIVE_CRITERIA_ARE_NOW_EXPLICIT",
			"CONDITIONAL_SUPPORT_TRANSPORT_NO_LONGER_MAIN_WOUND_AFTER_GATE943",
		},
		Failures: []string{
			"FAILED_ROUTE_NO_FINITE_H72_CHAMBER_DERIVATION_OF_S_SPLIT",
			"FAILED_ROUTE_S_SPLIT_REMAINS_BRIDGE_HISTORY_SCALAR_INPUT",
		},
	}
}

func DefaultCertificateIIStatus() CertificateIIStatus {
	return CertificateIIStatus{
		DescentSupported:  true,
		SourceNative:      false,
		CertificatePassed: false,
		Status:            "DESCENT_SUPPORTED_BUT_NATIVE_SOURCE_BLOCKED",
		Supports: []string{
			"CONDITIONAL_SUPPORT_CERTIFICATE_II_TRANSPORT_LAYER_SUPPORTED_BY_GATE943",
			"CONDITIONAL_SUPPORT_CERTIFICATE_II_REDUCED_TO_NATIVE_S_SPLIT_SOURCE",
		},
		Failures: []string{
			"FAILED_ROUTE_CERTIFICATE_II_NOT_PASSED_BECAUSE_S_SPLIT_SOURCE_NOT_NATIVE",
			"FAILED_ROUTE_NATIVE_R3_NOT_GRANTED",
		},
	}
}

func Supports() []string {
	return []string{
		"CONDITIONAL_SUPPORT_S_SPLIT_IS_DIMENSIONLESS_H72_COMPATIBLE_SCALAR",
		"CONDITIONAL_SUPPORT_GATE943_DESCENT_APPLIES_IF_S_SPLIT_IS_ACCEPTED_AS_H72_SCALAR",
		"CONDITIONAL_SUPPORT_S_SPLIT_EXPRESSION_SOURCE_IS_NOW_EXPLICIT",
		"CONDITIONAL_SUPPORT_R3_MINUS_ONE_HAS_SCALAR_DEVIATION_TYPE",
		"CONDITIONAL_SUPPORT_LAMBDA_LAMBDA12_HAS_SCALAR_ADDEND_TYPE",
		"CONDITIONAL_SUPPORT_S_SPLIT_NATIVE_CRITERIA_ARE_NOW_EXPLICIT",
		"CONDITIONAL_SUPPORT_TRANSPORT_NO_LONGER_MAIN_WOUND_AFTER_GATE943",
		"CONDITIONAL_SUPPORT_CERTIFICATE_II_TRANSPORT_LAYER_SUPPORTED_BY_GATE943",
		"CONDITIONAL_SUPPORT_CERTIFICATE_II_REDUCED_TO_NATIVE_S_SPLIT_SOURCE",
	}
}

func Failures() []string {
	return []string{
		"FAILED_ROUTE_NO_NATIVE_S_SPLIT_RESPONSE_PARAMETER_THEOREM",
		"FAILED_ROUTE_S_SPLIT_NATIVE_H72_SCALAR_SOURCE_NOT_CERTIFIED",
		"FAILED_ROUTE_R3_MINUS_ONE_NOT_DERIVED_AS_NATIVE_H72_SCALAR",
		"FAILED_ROUTE_LAMBDA_LAMBDA12_NOT_DERIVED_AS_NATIVE_H72_SCALAR",
		"FAILED_ROUTE_NO_FINITE_H72_CHAMBER_DERIVATION_OF_S_SPLIT",
		"FAILED_ROUTE_S_SPLIT_REMAINS_BRIDGE_HISTORY_SCALAR_INPUT",
		"FAILED_ROUTE_CERTIFICATE_II_NOT_PASSED_BECAUSE_S_SPLIT_SOURCE_NOT_NATIVE",
		"FAILED_ROUTE_NATIVE_R3_NOT_GRANTED",
		"FAILED_ROUTE_NO_OFFICIAL_LEDGER_UPDATE_ALLOWED",
		"FAILED_ROUTE_NO_INDIVIDUAL_YUKAWA_VALUES",
		"FAILED_ROUTE_NO_PHYSICAL_PARTICLE_ASSIGNMENT",
		"FAILED_ROUTE_NO_GENERATION_CARRIER_MAP",
		"FAILED_ROUTE_NO_FLAVOR_ORIENTATION_MAP",
		"FAILED_ROUTE_NO_R4_NATIVE_YUKAWA_SPECTRUM_THEOREM",
	}
}

func FormatExpression(e SsplitExpression) string {
	return fmt.Sprintf("%s = %.19g; components=%s; H72Compatible=%v native=%v", e.Expression, e.Value, strings.Join(e.Components, "+"), e.H72Compatible, e.NativeCertified)
}

func FormatComponent(c ComponentSource) string {
	return fmt.Sprintf("%s: %s; H72Scalar=%v native=%v bridgeHistory=%v", c.Name, c.Role, c.H72ScalarTyped, c.NativeCertified, c.BridgeHistoryUse)
}

func FormatCriteria(c NativeCriteria) string {
	return fmt.Sprintf("status=%s; required=%s; passed=%s; blocked=%s", c.Status, strings.Join(c.Required, ","), strings.Join(c.Passed, ","), strings.Join(c.Blocked, ","))
}

func FormatCertificate(c CertificateIIStatus) string {
	return fmt.Sprintf("%s; descent=%v sourceNative=%v certificatePassed=%v", c.Status, c.DescentSupported, c.SourceNative, c.CertificatePassed)
}

func containsAll(haystack, needles []string) bool {
	set := map[string]struct{}{}
	for _, h := range haystack {
		set[h] = struct{}{}
	}
	for _, n := range needles {
		if _, ok := set[n]; !ok {
			return false
		}
	}
	return true
}

func appendAll(items ...[]string) []string {
	var out []string
	for _, group := range items {
		out = append(out, group...)
	}
	return out
}

func componentSupports(components []ComponentSource) []string {
	var out []string
	for _, c := range components {
		out = append(out, c.Supports...)
	}
	return out
}

func componentFailures(components []ComponentSource) []string {
	var out []string
	for _, c := range components {
		out = append(out, c.Failures...)
	}
	return out
}

func stringsJoin(items []string) string { return strings.Join(items, " | ") }
