package generation2socketorderorientededgeairlockconsolidationaudit

import "github.com/bagherbal/asha-engine/pkg/theorem"

const (
	theoremID   = "GENERATION2_SOCKET_ORDER_ORIENTED_EDGE_AIRLOCK_CONSOLIDATION_AUDIT"
	theoremName = "Gate 897 — SocketOrder / OrientedEdgeOrdering / NeutralPunctureAirlock Consolidation Audit"
)

func Generation2SocketOrderOrientedEdgeAirlockConsolidationAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: theoremID, Name: theoremName, Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: theoremID, Name: theoremName, Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build audit", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "Gate 896 airlock functional obstruction inherited", Passed: containsAll(Statuses(), []string{StatusGate896Inherited}) && a.AirlockFamily.Z2Family, Detail: FormatAirlockFamily(a.AirlockFamily)},
			{Name: "right socket character pair is typed but unordered", Passed: a.SocketOrder.PairTyped && !a.SocketOrder.NativeOrder && !a.SocketOrder.PlusSelected && a.SocketOrder.RequiresSelector && containsAll(a.SocketOrder.Failures, []string{FailureNoNativeSocketOrderSelector, FailureCharacterConjugationNoPlus}), Detail: FormatSocketOrder(a.SocketOrder)},
			{Name: "boundary degree, J/chirality, and B-L do not select plus", Passed: !a.SocketOrder.BoundaryDegreeSelectsPlus && !a.SocketOrder.JOrChiralitySelectsPlus && !a.SocketOrder.BMinusLSelectsPlus && containsAll(a.SocketOrder.Failures, []string{FailureBoundaryDegreeNoPlus, FailureJChiralityNoPlus, FailureBMinusLNoPlus}), Detail: FormatSocketOrder(a.SocketOrder)},
			{Name: "edge table is generated by ordered airlock rule but does not select order", Passed: a.EdgeOrdering.CurrentFollowsIfPlusExposed && a.EdgeOrdering.MirrorExistsIfMinusExposed && a.EdgeOrdering.SameRankPattern && !a.EdgeOrdering.SelectsPlusByItself && a.EdgeOrdering.ReducesToSocketOrder && containsAll(a.EdgeOrdering.Failures, []string{FailureEdgeTableNoPlusByItself, FailureEdgeOrderingCircular}), Detail: FormatEdgeOrdering(a.EdgeOrdering)},
			{Name: "Z2 mirror airlock family reconstructs alpha ranks for plus and minus", Passed: a.AirlockFamily.BothReconstructAlpha && a.AirlockFamily.Z2Family && !a.AirlockFamily.OrderedRepresentativeCertified && near(a.AirlockFamily.PlusAlpha, AlphaB) && near(a.AirlockFamily.MinusAlpha, AlphaB) && containsAll(a.AirlockFamily.Failures, []string{FailureNoNativeOrderedAirlock, FailureNoNativeSelectionSigmaPlus}), Detail: FormatAirlockFamily(a.AirlockFamily)},
			{Name: "official diagnostics remain frozen", Passed: a.Freeze.Frozen && a.Freeze.DiagnosticOnly && !a.Freeze.CanUpdate && near(a.Freeze.OperatorNEff, OperatorNEffDiagnostic) && !near(a.Freeze.OperatorNEff, a.Freeze.OfficialNEff), Detail: FormatFreeze(a.Freeze)},
			{Name: "native R3/R4, alpha, Higgs orientation, socket-order, airlock, and official-ledger firewalls preserved", Passed: firewallsOK(a.Firewalls) && containsAll(a.FirewallsList(), []string{FailureNotNativeR3, FailureAlphaStillSealed, FailureHiggsOrientationStillSealed, FailureNoNativeSocketOrderSelector, FailureNoNativeOrderedAirlock}), Detail: FormatFirewalls(a.Firewalls)},
		}
		ok := true
		for _, c := range checks {
			if !c.Passed {
				ok = false
				break
			}
		}
		status := theorem.BridgeRequired
		if !ok {
			status = theorem.FailedRoute
		}
		notes := []string{a.Truth, FormatSocketOrder(a.SocketOrder), FormatEdgeOrdering(a.EdgeOrdering), FormatAirlockFamily(a.AirlockFamily), FormatFreeze(a.Freeze), FormatFirewalls(a.Firewalls), a.Final}
		notes = append(notes, Statuses()...)
		return theorem.Result{ID: theoremID, Name: theoremName, Layer: theorem.LayerBridge, Status: status, Checks: checks, Notes: notes}
	}}
}
