package contactquarticcompression

import (
	"fmt"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func QuarticOrbitSemanticCompressionFourRowBlockBetaFirewallTheorem() theorem.Theorem {
	const id = "BRIDGE-QUARTIC-ORBIT-SEMANTIC-COMPRESSION-FOUR-ROW-BLOCK-BETA-FIREWALL"
	const name = "Quartic orbit semantic compression / four-row block beta firewall theorem"
	return theorem.Theorem{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.Variational, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build quartic orbit compression theorem", Passed: false, Detail: err.Error()}}}
		}
		return theorem.Result{ID: id, Name: name, Layer: theorem.LayerBridge, Status: theorem.Variational, Checks: []theorem.Check{
			{Name: "Gate 153 Galois-invariant 1+1+1+4 partition is inherited", Passed: a.Previous.BetaPermissionFirewallClosed && a.Previous.ExactRationalOverlapMatrix && a.Previous.ExactCharacteristicCertified && a.Previous.ExactRootIsolationCertified && a.Previous.GaloisInvariantOrbits == 4 && a.Previous.RationalSingletonRows == 3 && a.Previous.QuarticOrbitRows == 4 && a.Previous.IndividualQuarticRows == 0 && a.Previous.ContactBetaRowsAllowed == 0, Detail: fmt.Sprintf("matrix=%t char=%t rootIso=%t orbits=%d rational=%d quartic=%d individual=%d beta=%d", a.Previous.ExactRationalOverlapMatrix, a.Previous.ExactCharacteristicCertified, a.Previous.ExactRootIsolationCertified, a.Previous.GaloisInvariantOrbits, a.Previous.RationalSingletonRows, a.Previous.QuarticOrbitRows, a.Previous.IndividualQuarticRows, a.Previous.ContactBetaRowsAllowed)},
			{Name: "quartic block has exact Q-symmetric invariants", Passed: a.BlockInvariant.Degree == 4 && a.BlockInvariant.BlockRows == 4 && a.BlockInvariant.SumRootsNumerator == 71 && a.BlockInvariant.SumRootsDenominator == 30 && a.BlockInvariant.MeanNumerator == 71 && a.BlockInvariant.MeanDenominator == 120 && a.BlockInvariant.PairSumNumerator == 119 && a.BlockInvariant.PairSumDenominator == 60 && a.BlockInvariant.TripleSumNumerator == 149 && a.BlockInvariant.TripleSumDenominator == 216 && a.BlockInvariant.ProductNumerator == 271 && a.BlockInvariant.ProductDenominator == 3240 && a.BlockInvariant.SymmetricInvariants == 4 && a.BlockInvariant.ExactOverQ && a.BlockInvariant.GaloisInvariant && !a.BlockInvariant.IndividualRowsSplit, Detail: FormatBlockInvariant(a.BlockInvariant)},
			{Name: "compression is branch-free but not row-complete", Passed: a.Compression.InputPattern == "1+1+1+4" && a.Compression.CompressedPattern == "1+1+1+[4]" && a.Compression.QuarticBlockRows == 4 && a.Compression.CompressedBlocks == 4 && a.Compression.RowLevelQuarticSemantics == 0 && a.Compression.BlockLevelSpectralSemantic && !a.Compression.RowComplete && a.Compression.BranchFree && a.Compression.HiddenBranchChoices == 4, Detail: FormatCompression(a.Compression)},
			{Name: "four-row block lacks beta-permission data", Passed: a.BlockBeta.BlockRows == 4 && a.BlockBeta.GaugeRepresentationRows == 0 && a.BlockBeta.SpinStatisticsRows == 0 && a.BlockBeta.LocalFieldRows == 0 && a.BlockBeta.LorentzKineticRows == 0 && a.BlockBeta.MassActivationRows == 0 && a.BlockBeta.DecouplingRows == 0 && a.BlockBeta.DynkinIndexRows == 0 && a.BlockBeta.ThresholdBetaRowsAllowed == 0 && !a.BlockBeta.BlockCanContributeAsMultiplet, Detail: FormatBlockBeta(a.BlockBeta)},
			{Name: "compressed block pattern still mismatches current/contact/Fano semantics", Passed: a.Pattern.GaloisSafePattern == "1+1+1+4" && a.Pattern.QuarticBlockPattern == "1+1+1+[4]" && a.Pattern.CurrentQuotientPattern == "1+6" && a.Pattern.ContactSingletonPattern == "1+1+1+1+1+1+1" && a.Pattern.FanoPattern == "7-transitive" && !a.Pattern.MatchesCurrent && !a.Pattern.MatchesContact && !a.Pattern.MatchesFano, Detail: FormatPattern(a.Pattern)},
			{Name: "physics firewall remains closed after block compression", Passed: a.Firewall.ObservedInputFree && a.Firewall.ExactMatrix && a.Firewall.ExactCharpoly && a.Firewall.ExactRootIsolation && a.Firewall.RationalPrimaryIdempotents && a.Firewall.GaloisInvariantPartition && a.Firewall.QuarticBlockInvariants && !a.Firewall.IndividualQuarticSplit && !a.Firewall.GaugeRepresentation && !a.Firewall.LocalFieldMap && !a.Firewall.MassActivation && !a.Firewall.Decoupling && !a.Firewall.BetaRows && !a.Firewall.PhysicalConstants && !a.Firewall.AllSatisfiedForPhysics, Detail: FormatFirewall(a.Firewall)},
			{Name: "contact beta and physical constants remain sealed", Passed: a.ContactRows == 7 && a.GaloisInvariantOrbits == 4 && a.RationalSingletonRows == 3 && a.QuarticOrbitRows == 4 && a.QuarticCompressedBlocks == 1 && a.QuarticBlockInvariants == 4 && a.IndividualQuarticRows == 0 && a.CanonicalQuarticBranches == 0 && a.ExactNumberFieldProjectors == 0 && a.IndividualQuarticProjectors == 0 && a.RowwiseRootAssignmentProofs == 0 && a.ChargeSemanticRows == 0 && a.T3RRowsDerived == 0 && a.BMinusLRowsDerived == 0 && a.HyperchargeRowsDerived == 0 && a.GaugeRepresentationRows == 0 && a.LocalFieldRows == 0 && a.MassActivationRows == 0 && a.DecouplingRows == 0 && a.RepresentationCompleteRows == 0 && a.RepresentationOpenRows == 7 && a.QuarticBlockBetaRows == 0 && a.ContactBetaRowsAllowed == 0 && a.ContactZeroRowsProved == 0 && a.BetaPermissionFirewallClosed && a.ResidualS6Choices == 720 && a.ResidualNullityBefore == 3 && a.ResidualNullityAfter == 3 && !a.ThresholdCorrectedBeta && !a.FullBetaMatchingTensor && !a.HiddenObservedInputUsed && !a.PhysicalWeakAngleDerived && !a.FineStructureDerived && !a.PhysicalMassesDerived && !a.PhysicalScaleDerived, Detail: FormatSummary(a.Summary) + " :: " + a.TruthStatement},
		}}
	}}
}
