// Package generation2flavorspectralorientationbalancefunctionalaudit implements
// Gate 594: Flavor Spectral Orientation Balance Functional Audit.
//
// Gate 593 rewrote the strongest current bridge-layer orientation balance as
//
//	1 - 8*pi*epsilon(Y_e) ~= (1/4)Tr(P_e U_PMNS P_3^nu U_PMNS^dagger) - J(Y_u,Y_d).
//
// Gate 594 places all three terms into one observed flavor spectral algebra
// generated by Hermitian Yukawa bilinears H_e,H_nu,H_u,H_d.  The result is a
// precise functional target B_flav(H_e,H_nu,H_u,H_d) ~= 0.  This remains an
// environmental audit: no Koide, PMNS, CKM, Yukawa, neutrino, or flavor texture
// derivation is promoted to ASHA-native law.
package generation2flavorspectralorientationbalancefunctionalaudit

import (
	"fmt"
	"math"
	"strings"
	"sync"

	"github.com/bagherbal/asha-engine/pkg/bridge/generation2orientationbalanceinvariantmatrixformaudit"
)

const (
	AuditID = "GATE594-FLAVOR-SPECTRAL-ORIENTATION-BALANCE-FUNCTIONAL-AUDIT"

	StatusGate593Inherited             = "PASS_GATE593_ORIENTATION_BALANCE_INVARIANT_FORM_INHERITED"
	StatusFlavorSpectralAlgebraDefined = "PASS_FLAVOR_SPECTRAL_ALGEBRA_DEFINED"
	StatusRootSpectrumFunctional       = "PASS_CHARGED_LEPTON_ROOT_SPECTRUM_FUNCTIONAL_DEFINED"
	StatusPMNSSpectralProjectors       = "PASS_PMNS_PROJECTOR_OVERLAP_WRITTEN_IN_FLAVOR_SPECTRAL_ALGEBRA"
	StatusCKMNormalizedCommutator      = "PASS_CKM_NORMALIZED_COMMUTATOR_AREA_WRITTEN_IN_FLAVOR_SPECTRAL_ALGEBRA"
	StatusBalanceFunctionalConstructed = "PASS_B_FLAV_FUNCTIONAL_CONSTRUCTED"
	StatusNumericReproducesGate590593  = "PASS_B_FLAV_NUMERICALLY_REPRODUCES_GATE590_593_RESIDUAL"
	StatusInvarianceAuditComplete      = "PASS_FLAVOR_SPECTRAL_INVARIANCE_AND_LABEL_SEALS_AUDITED"
	StatusASHAAvailabilityAudited      = "PASS_CURRENT_ASHA_FLAVOR_SPECTRAL_AVAILABILITY_AUDITED"
	StatusOperatorTargetSharpened      = "CONDITIONAL_SUPPORT_B_FLAV_SHARPENS_NATIVE_THEOREM_TARGET"
	StatusSpectralBalanceEnvironmental = "CONDITIONAL_SUPPORT_FLAVOR_SPECTRAL_ORIENTATION_BALANCE_ENVIRONMENTAL_ONLY"
	StatusNoNativeFlavorSpectralOp     = "FAILED_ROUTE_NO_NATIVE_FLAVOR_SPECTRAL_BALANCE_OPERATOR"
	StatusNoNativeEpsilonHE            = "FAILED_ROUTE_NO_NATIVE_EPSILON_OF_H_E_FUNCTIONAL"
	StatusNoNativePMNSProjector        = "FAILED_ROUTE_NO_NATIVE_PMNS_PROJECTOR_OVERLAP_DERIVATION"
	StatusNoNativeCKMCommutator        = "FAILED_ROUTE_NO_NATIVE_NORMALIZED_CKM_COMMUTATOR_DERIVATION"
	StatusNoBFlavZeroTheorem           = "FAILED_ROUTE_NO_NATIVE_B_FLAV_ZERO_THEOREM"
	StatusNoCrossSectorIntertwiner     = "FAILED_ROUTE_NO_CROSS_SECTOR_ORIENTATION_INTERTWINER"
	StatusBFlavEnvironmental           = "FAILED_ROUTE_B_FLAV_REMAINS_ENVIRONMENTAL"
	StatusGate352Preserved             = "FIREWALL_PRESERVED_GATE352_ROOT_TRACE_OBSTRUCTION_REMAINS_BINDING"
	StatusNoFlavorDerivation           = "FIREWALL_PRESERVED_NO_KOIDE_PMNS_CKM_YUKAWA_NEUTRINO_OR_FLAVOR_DERIVATION"
	StatusObservedDataFirewalled       = "FIREWALL_PRESERVED_FLAVOR_SPECTRAL_INPUTS_REMAIN_OBSERVED_ENVIRONMENTAL_DATA"
	StatusNoNewCarrierSelector         = "FIREWALL_PRESERVED_NO_NEW_CARRIER_OR_SELECTOR_ADDED"
	StatusGate594Boundary              = "FIREWALL_PRESERVED_GATE594_FLAVOR_SPECTRAL_BALANCE_BOUNDARY"
)

type InheritedRelation struct {
	EpsilonObsRad        float64
	KappaObs             float64
	PMNSTrace            float64
	PMNSQuarter          float64
	JCKM                 float64
	RightHandCandidate   float64
	Delta590             float64
	BFlavValue           float64
	EpsilonPredictionRad float64
	EpsilonResidualRad   float64
	ResidualInsideSigma  bool
	Verdict              string
}

type SpectralAlgebraAudit struct {
	Name                 string
	Generators           []string
	Definition           string
	CommonCarrier        string
	ObservedOnly         bool
	NativeAlgebraPresent bool
	Verdict              string
}

type ChargedLeptonRootFunctional struct {
	HermitianObject             string
	SpectralData                string
	SingularValueExtraction     string
	SquareRootVectorExtraction  string
	KoideChamberCoordinate      string
	EpsilonFunctional           string
	RequiresSpectralCalculus    bool
	RequiresFourthRootOfHE      bool
	RequiresChamberOrderSeal    bool
	NativeFunctionalPresent     bool
	Gate352ObstructionPreserved bool
	Verdict                     string
}

type PMNSSpectralProjectorAudit struct {
	HermitianObject   string
	ElectronProjector string
	NeutrinoProjector string
	ProjectorOverlap  string
	TraceValue        float64
	QuarterValue      float64
	RequiredLabels    []string
	BasisStatement    string
	NativeDerivation  bool
	ObservedLedger    bool
	Verdict           string
}

type CKMSpectralCommutatorAudit struct {
	UpHermitian                  string
	DownHermitian                string
	JarlskogArea                 string
	NormalizedCommutator         string
	JValue                       float64
	RequiresNondegenerateSpectra bool
	RequiredLabels               []string
	NativeDerivation             bool
	ObservedLedger               bool
	Verdict                      string
}

type BalanceFunctionalAudit struct {
	Name                string
	Definition          string
	ExpandedDefinition  string
	LeftKappa           float64
	ProjectorQuarter    float64
	JCKM                float64
	RightHandCandidate  float64
	BFlav               float64
	Delta590            float64
	SignConvention      string
	ResidualInsideSigma bool
	Verdict             string
}

type InvarianceItem struct {
	Transformation string
	InvariantPart  string
	RequiredSeal   string
	Conclusion     string
	Verdict        string
}

type InvarianceAudit struct {
	Items                   []InvarianceItem
	AllRequiredSealsNamed   bool
	BasisInvariantWithSeals bool
	Verdict                 string
}

type AvailabilityItem struct {
	Object         string
	ObservedLedger bool
	NativeOperator bool
	CanForceBZero  bool
	Reason         string
	Verdict        string
}

type AvailabilityAudit struct {
	Items                       []AvailabilityItem
	NativeFlavorSpectralAlgebra bool
	NativeEpsilonFunctional     bool
	NativePMNSProjector         bool
	NativeCKMCommutator         bool
	NativeBFlavZeroTheorem      bool
	Verdict                     string
}

type OperatorTarget struct {
	Name                          string
	Domain                        []string
	Codomain                      string
	Functional                    string
	NativeTheoremRequired         string
	MustUseSpectralCalculus       bool
	MustBeBasisInvariantWithSeals bool
	MustPreserveSectorTyping      bool
	NativePresent                 bool
	Verdict                       string
}

type FirewallAudit struct {
	DerivesKoide         bool
	DerivesPMNS          bool
	DerivesCKM           bool
	DerivesYukawas       bool
	DerivesNeutrinoData  bool
	DerivesFlavorTexture bool
	PromotesObservedData bool
	AddsNewCarrier       bool
	AddsNewSelector      bool
	PreservesGate352     bool
	Verdict              string
}

type FinalVerdict struct {
	AllTermsInOneSpectralAlgebra bool
	RequiredLabels               string
	NativeBFlavOperatorPresent   bool
	BFlavEnvironmental           bool
	PromotionTheoremNeeded       string
	Decision                     string
	Verdict                      string
}

type Analysis struct {
	Inherited     InheritedRelation
	Algebra       SpectralAlgebraAudit
	ChargedLepton ChargedLeptonRootFunctional
	PMNS          PMNSSpectralProjectorAudit
	CKM           CKMSpectralCommutatorAudit
	Balance       BalanceFunctionalAudit
	Invariance    InvarianceAudit
	Availability  AvailabilityAudit
	Target        OperatorTarget
	Firewalls     FirewallAudit
	Final         FinalVerdict
	Truth         string
}

var cache struct {
	sync.Once
	a   Analysis
	err error
}

func BuildDefault() (Analysis, error) {
	cache.Once.Do(func() { cache.a, cache.err = Build() })
	return cache.a, cache.err
}

func Build() (Analysis, error) {
	g593, err := generation2orientationbalanceinvariantmatrixformaudit.BuildDefault()
	if err != nil {
		return Analysis{}, fmt.Errorf("build Gate593 predecessor: %w", err)
	}
	inherited := inheritGate593(g593)
	algebra := defineFlavorSpectralAlgebra()
	charged := defineChargedLeptonRootFunctional()
	pmns := definePMNSSpectralProjectors(inherited)
	ckm := defineCKMSpectralCommutator(inherited)
	balance := constructBFlav(inherited)
	invariance := auditInvarianceAndLabels()
	availability := auditAvailability()
	target := defineOperatorTarget()
	firewalls := auditFirewalls()
	final := compileFinal(invariance, availability, target)
	truth := "Gate 594 places the OrientationBalanceSeal inside one observed flavor spectral algebra A_flav=Alg(H_e,H_nu,H_u,H_d).  In that algebra epsilon(H_e) is a root-spectrum chamber functional, Tr(P_e P_3^nu) is the PMNS reactor projector overlap, and J(H_u,H_d) is the normalized CKM commutator area.  The resulting B_flav functional numerically reproduces the Gate 590/593 residual with sign B_flav=-Delta_590, but current ASHA has no native epsilon(H_e), PMNS projector, normalized CKM commutator-to-Koide-wall map, or theorem forcing B_flav=0."
	return Analysis{Inherited: inherited, Algebra: algebra, ChargedLepton: charged, PMNS: pmns, CKM: ckm, Balance: balance, Invariance: invariance, Availability: availability, Target: target, Firewalls: firewalls, Final: final, Truth: truth}, nil
}

func inheritGate593(g593 generation2orientationbalanceinvariantmatrixformaudit.Analysis) InheritedRelation {
	b := g593.Balance.LeftKappa - g593.Balance.RightProjectorMinusCKM
	return InheritedRelation{
		EpsilonObsRad:        g593.Inherited.EpsilonObsRad,
		KappaObs:             g593.Balance.LeftKappa,
		PMNSTrace:            g593.PMNS.TraceValue,
		PMNSQuarter:          g593.PMNS.ReactorQuarter,
		JCKM:                 g593.CKM.JCKM,
		RightHandCandidate:   g593.Balance.RightProjectorMinusCKM,
		Delta590:             g593.Balance.Residual,
		BFlavValue:           b,
		EpsilonPredictionRad: g593.Balance.EpsilonPredictionRad,
		EpsilonResidualRad:   g593.Balance.EpsilonResidualRad,
		ResidualInsideSigma:  g593.Balance.ResidualInsideSigma,
		Verdict:              StatusGate593Inherited,
	}
}

func defineFlavorSpectralAlgebra() SpectralAlgebraAudit {
	return SpectralAlgebraAudit{
		Name:                 "A_flav",
		Generators:           []string{"H_e=Y_e Y_e^dagger", "H_nu=neutrino Hermitian flavor object", "H_u=Y_u Y_u^dagger", "H_d=Y_d Y_d^dagger"},
		Definition:           "A_flav = Alg(H_e,H_nu,H_u,H_d) with observed flavor ledgers supplying spectra/projectors/orientations",
		CommonCarrier:        "three-generation flavor Hilbert space after empirical charged-lepton, neutrino, up-quark, and down-quark ledgers are chosen",
		ObservedOnly:         true,
		NativeAlgebraPresent: false,
		Verdict:              strings.Join([]string{StatusFlavorSpectralAlgebraDefined, StatusNoNativeFlavorSpectralOp}, ";"),
	}
}

func defineChargedLeptonRootFunctional() ChargedLeptonRootFunctional {
	return ChargedLeptonRootFunctional{
		HermitianObject:             "H_e=Y_e Y_e^dagger",
		SpectralData:                "eig(H_e)=(y_e^2,y_mu^2,y_tau^2) after charged-lepton generation ordering",
		SingularValueExtraction:     "y_i = sqrt(eig_i(H_e))",
		SquareRootVectorExtraction:  "x_i=sqrt(y_i)=eig_i(H_e)^(1/4)",
		KoideChamberCoordinate:      "x_j=A[1+sqrt(2)R cos(delta+2*pi*j/3)], chamber (e,mu,tau), epsilon(H_e)=135deg-delta",
		EpsilonFunctional:           "epsilon(H_e) is the electron-wall coordinate of the charged-lepton root-spectrum ray; kappa(H_e)=1-8*pi*epsilon(H_e)",
		RequiresSpectralCalculus:    true,
		RequiresFourthRootOfHE:      true,
		RequiresChamberOrderSeal:    true,
		NativeFunctionalPresent:     false,
		Gate352ObstructionPreserved: true,
		Verdict:                     strings.Join([]string{StatusRootSpectrumFunctional, StatusNoNativeEpsilonHE, StatusGate352Preserved}, ";"),
	}
}

func definePMNSSpectralProjectors(in InheritedRelation) PMNSSpectralProjectorAudit {
	return PMNSSpectralProjectorAudit{
		HermitianObject:   "H_nu=Y_nu Y_nu^dagger or effective Majorana/Weinberg Hermitian proxy, depending on neutrino scenario",
		ElectronProjector: "P_e=spectral projector of H_e for the electron eigenline",
		NeutrinoProjector: "P_3^nu=spectral projector of H_nu for the third neutrino mass eigenstate",
		ProjectorOverlap:  "Tr(P_e P_3^nu)=Tr(P_e U_PMNS P_3^nu U_PMNS^dagger)=|U_e3|^2=sin^2(theta13)",
		TraceValue:        in.PMNSTrace,
		QuarterValue:      in.PMNSQuarter,
		RequiredLabels:    []string{"electron spectral projector", "third neutrino mass projector", "normal ordering / PMNS convention", "charged-lepton mass basis"},
		BasisStatement:    "The trace is invariant under common flavor-basis conjugation once P_e and P_3^nu are labeled.",
		NativeDerivation:  false,
		ObservedLedger:    true,
		Verdict:           strings.Join([]string{StatusPMNSSpectralProjectors, StatusNoNativePMNSProjector}, ";"),
	}
}

func defineCKMSpectralCommutator(in InheritedRelation) CKMSpectralCommutatorAudit {
	return CKMSpectralCommutatorAudit{
		UpHermitian:                  "H_u=Y_u Y_u^dagger",
		DownHermitian:                "H_d=Y_d Y_d^dagger",
		JarlskogArea:                 "J(H_u,H_d)=Im(V_us V_cb V_ub^* V_cs^*) with orientation convention",
		NormalizedCommutator:         "J(H_u,H_d)=det([H_u,H_d])/(2 i prod_{i<j}(y_{u_i}^2-y_{u_j}^2) prod_{i<j}(y_{d_i}^2-y_{d_j}^2)), up to sign/convention",
		JValue:                       in.JCKM,
		RequiresNondegenerateSpectra: true,
		RequiredLabels:               []string{"up-generation ordering", "down-generation ordering", "CKM orientation sign", "nondegenerate quark spectra"},
		NativeDerivation:             false,
		ObservedLedger:               true,
		Verdict:                      strings.Join([]string{StatusCKMNormalizedCommutator, StatusNoNativeCKMCommutator}, ";"),
	}
}

func constructBFlav(in InheritedRelation) BalanceFunctionalAudit {
	return BalanceFunctionalAudit{
		Name:                "B_flav",
		Definition:          "B_flav(H_e,H_nu,H_u,H_d)=1-8*pi*epsilon(H_e)-(1/4)Tr(P_e P_3^nu)+J(H_u,H_d)",
		ExpandedDefinition:  "B_flav = kappa_e - sin^2(theta13)/4 + J_CKM = kappa_e - [(1/4)|U_e3|^2 - J_CKM]",
		LeftKappa:           in.KappaObs,
		ProjectorQuarter:    in.PMNSQuarter,
		JCKM:                in.JCKM,
		RightHandCandidate:  in.RightHandCandidate,
		BFlav:               in.BFlavValue,
		Delta590:            in.Delta590,
		SignConvention:      "Gate590 Delta_590 = [(1/4)|U_e3|^2 - J_CKM] - kappa_e; therefore B_flav = -Delta_590.",
		ResidualInsideSigma: in.ResidualInsideSigma,
		Verdict:             strings.Join([]string{StatusBalanceFunctionalConstructed, StatusNumericReproducesGate590593, StatusSpectralBalanceEnvironmental}, ";"),
	}
}

func auditInvarianceAndLabels() InvarianceAudit {
	items := []InvarianceItem{
		{Transformation: "common flavor-basis unitary conjugation", InvariantPart: "spectra of H_e, projector trace Tr(P_e P_3^nu), and normalized commutator J(H_u,H_d)", RequiredSeal: "all projectors transformed by the same basis change", Conclusion: "B_flav is basis-covariant/invariant once spectral labels are fixed.", Verdict: "PASS_BASIS_UNITARY_INVARIANCE_WITH_LABELS"},
		{Transformation: "field rephasings", InvariantPart: "projector overlap and Jarlskog invariant", RequiredSeal: "signed CKM orientation convention", Conclusion: "Magnitudes are rephasing invariant; signed J still needs orientation convention.", Verdict: "PASS_REPHASING_INVARIANCE_WITH_SIGN_SEAL"},
		{Transformation: "charged-lepton generation relabeling", InvariantPart: "unordered spectrum", RequiredSeal: "canonical chamber (e,mu,tau) and electron-zero wall", Conclusion: "epsilon(H_e) is not S3-invariant without chamber/wall labeling.", Verdict: "PASS_CHARGED_LEPTON_CHAMBER_LABEL_REQUIRED"},
		{Transformation: "neutrino mass ordering relabeling", InvariantPart: "projector trace after a mass projector is chosen", RequiredSeal: "third mass eigenstate P_3^nu and normal/inverted ordering convention", Conclusion: "The reactor overlap is label-dependent but projector-invariant once the label is sealed.", Verdict: "PASS_NEUTRINO_ORDERING_LABEL_REQUIRED"},
		{Transformation: "quark generation orientation reversal", InvariantPart: "|J| and normalized commutator magnitude", RequiredSeal: "signed CKM orientation convention", Conclusion: "The balance uses signed +J in B_flav; sign is a true orientation seal.", Verdict: "PASS_QUARK_ORIENTATION_SIGN_REQUIRED"},
	}
	return InvarianceAudit{Items: items, AllRequiredSealsNamed: true, BasisInvariantWithSeals: true, Verdict: StatusInvarianceAuditComplete}
}

func auditAvailability() AvailabilityAudit {
	items := []AvailabilityItem{
		{Object: "A_flav=Alg(H_e,H_nu,H_u,H_d)", ObservedLedger: true, NativeOperator: false, CanForceBZero: false, Reason: "The common algebra is constructed from observed flavor ledgers, not derived from ASHA finite law-space.", Verdict: StatusNoNativeFlavorSpectralOp},
		{Object: "epsilon(H_e)", ObservedLedger: true, NativeOperator: false, CanForceBZero: false, Reason: "Requires root-spectrum/fourth-root spectral calculus and a chamber wall; Gate352 root-trace obstruction remains binding.", Verdict: StatusNoNativeEpsilonHE},
		{Object: "Tr(P_e P_3^nu)", ObservedLedger: true, NativeOperator: false, CanForceBZero: false, Reason: "PMNS reactor data supplies it; no native PMNS projector theorem exists.", Verdict: StatusNoNativePMNSProjector},
		{Object: "J(H_u,H_d)", ObservedLedger: true, NativeOperator: false, CanForceBZero: false, Reason: "CKM ledger supplies J; no native normalized commutator-to-Koide-wall theorem exists.", Verdict: StatusNoNativeCKMCommutator},
		{Object: "B_flav=0 theorem", ObservedLedger: false, NativeOperator: false, CanForceBZero: false, Reason: "This is the missing theorem target isolated by Gate594.", Verdict: StatusNoBFlavZeroTheorem},
	}
	return AvailabilityAudit{Items: items, NativeFlavorSpectralAlgebra: false, NativeEpsilonFunctional: false, NativePMNSProjector: false, NativeCKMCommutator: false, NativeBFlavZeroTheorem: false, Verdict: strings.Join([]string{StatusASHAAvailabilityAudited, StatusNoNativeFlavorSpectralOp, StatusNoBFlavZeroTheorem}, ";")}
}

func defineOperatorTarget() OperatorTarget {
	return OperatorTarget{
		Name:                          "FlavorSpectralOrientationBalanceFunctional",
		Domain:                        []string{"H_e=Y_eY_e^dagger", "H_nu neutrino Hermitian object", "H_u=Y_uY_u^dagger", "H_d=Y_dY_d^dagger", "label seals for chambers/projectors/orientation"},
		Codomain:                      "real scalar balance residual",
		Functional:                    "B_flav(H_e,H_nu,H_u,H_d)=1-8*pi*epsilon(H_e)-(1/4)Tr(P_e P_3^nu)+J(H_u,H_d)",
		NativeTheoremRequired:         "A native ASHA theorem must construct B_flav from finite law-space data and prove B_flav=0, including the root-spectrum epsilon map and cross-sector projector/commutator orientation coupling.",
		MustUseSpectralCalculus:       true,
		MustBeBasisInvariantWithSeals: true,
		MustPreserveSectorTyping:      true,
		NativePresent:                 false,
		Verdict:                       strings.Join([]string{StatusOperatorTargetSharpened, StatusNoCrossSectorIntertwiner, StatusNoBFlavZeroTheorem}, ";"),
	}
}

func auditFirewalls() FirewallAudit {
	return FirewallAudit{DerivesKoide: false, DerivesPMNS: false, DerivesCKM: false, DerivesYukawas: false, DerivesNeutrinoData: false, DerivesFlavorTexture: false, PromotesObservedData: false, AddsNewCarrier: false, AddsNewSelector: false, PreservesGate352: true, Verdict: strings.Join([]string{StatusNoFlavorDerivation, StatusObservedDataFirewalled, StatusGate352Preserved, StatusNoNewCarrierSelector, StatusGate594Boundary}, ";")}
}

func compileFinal(inv InvarianceAudit, availability AvailabilityAudit, target OperatorTarget) FinalVerdict {
	native := availability.NativeBFlavZeroTheorem || target.NativePresent
	decision := "Gate 594 expresses all OrientationBalance terms inside the observed flavor spectral algebra A_flav=Alg(H_e,H_nu,H_u,H_d) and defines B_flav(H_e,H_nu,H_u,H_d)=1-8*pi*epsilon(H_e)-(1/4)Tr(P_e P_3^nu)+J(H_u,H_d).  It reproduces the Gate590/593 residual with sign B_flav=-Delta_590, but ASHA currently lacks the native root-spectrum epsilon functional, PMNS projector derivation, normalized CKM commutator-to-Koide-wall map, and theorem forcing B_flav=0.  B_flav=0 remains an environmental balance seal."
	return FinalVerdict{AllTermsInOneSpectralAlgebra: true, RequiredLabels: fmt.Sprintf("%d label/invariance seals", len(inv.Items)), NativeBFlavOperatorPresent: native, BFlavEnvironmental: !native, PromotionTheoremNeeded: target.NativeTheoremRequired, Decision: decision, Verdict: strings.Join([]string{StatusBalanceFunctionalConstructed, StatusNoBFlavZeroTheorem, StatusBFlavEnvironmental, StatusGate594Boundary}, ";")}
}

func Statuses() []string {
	return []string{StatusGate593Inherited, StatusFlavorSpectralAlgebraDefined, StatusRootSpectrumFunctional, StatusPMNSSpectralProjectors, StatusCKMNormalizedCommutator, StatusBalanceFunctionalConstructed, StatusNumericReproducesGate590593, StatusInvarianceAuditComplete, StatusASHAAvailabilityAudited, StatusOperatorTargetSharpened, StatusSpectralBalanceEnvironmental, StatusNoNativeFlavorSpectralOp, StatusNoNativeEpsilonHE, StatusNoNativePMNSProjector, StatusNoNativeCKMCommutator, StatusNoBFlavZeroTheorem, StatusNoCrossSectorIntertwiner, StatusBFlavEnvironmental, StatusGate352Preserved, StatusNoFlavorDerivation, StatusObservedDataFirewalled, StatusNoNewCarrierSelector, StatusGate594Boundary}
}

func almostEqual(a, b, tol float64) bool { return math.Abs(a-b) <= tol }
