package generation2k7complementboundarywoundmixtureobservableaudit

import (
	"math"
	"strings"

	"github.com/bagherbal/asha-engine/pkg/theorem"
)

func Generation2K7ComplementBoundaryWoundMixtureObservableAuditTheorem() theorem.Theorem {
	return theorem.Theorem{ID: AuditID, Name: "Gate 704 — K7/Complement Boundary Wound Mixture Observable Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Verify: func() theorem.Result {
		a, err := BuildDefault()
		if err != nil {
			return theorem.Result{ID: AuditID, Name: "Gate 704 — K7/Complement Boundary Wound Mixture Observable Audit", Layer: theorem.LayerBridge, Status: theorem.FailedRoute, Checks: []theorem.Check{{Name: "build", Passed: false, Detail: err.Error()}}}
		}
		checks := []theorem.Check{
			{Name: "inherit Gate703 scalar-wall airlock", Passed: a.Inherited.ScalarWallAirlockInherited && a.Inherited.UnitScalarWallGlue && math.Abs(a.Inherited.EventProbability-pK7) < tolerance && math.Abs(a.Inherited.ResponseCoefficient-pK7) < tolerance && a.Inherited.NonTautologyInherited && a.Inherited.NoNativeScalarWallAirlock && a.Inherited.NoNativeBoundaryHistory && a.Inherited.NoNativeSevenOver72 && a.Inherited.Verdict == StatusGate703ScalarWallAirlockInherited, Detail: FormatInheritance(a.Inherited)},
			{Name: "rearrange Gate700 response law", Passed: strings.Contains(a.Rearrangement.StartingEquation, "p_K7") && strings.Contains(a.Rearrangement.RearrangedEquation, "p_perp") && a.Rearrangement.LambdaNegative && math.Abs(a.Rearrangement.KSum-(kappaLambda+kappaE)) < tolerance && math.Abs(a.Rearrangement.PositiveScalarDepth-math.Abs(lambdaLambda12)) < tolerance && math.Abs(a.Rearrangement.GaugeWound-r3Minus1) < tolerance && math.Abs(a.Rearrangement.WeightedClosureRight-(pComplement*math.Abs(lambdaLambda12)+pK7*r3Minus1)) < tolerance && a.Rearrangement.SameAsGate700Residual && strings.Contains(a.Rearrangement.Verdict, StatusGate700ResponseLawRearranged), Detail: FormatRearrangement(a.Rearrangement)},
			{Name: "compute K7 and complement probabilities", Passed: a.Probabilities.K7Rank == k7Dimension && a.Probabilities.ComplementRank == complementDim && a.Probabilities.TotalDimension == h72Dimension && math.Abs(a.Probabilities.PK7Probability-pK7) < tolerance && math.Abs(a.Probabilities.ComplementProb-pComplement) < tolerance && a.Probabilities.ProbabilitiesSumTo1 && strings.Contains(a.Probabilities.Verdict, StatusK7AndComplementProbabilitiesComputed) && strings.Contains(a.Probabilities.Verdict, Status7Over72K7EventProbability) && strings.Contains(a.Probabilities.Verdict, Status65Over72ComplementEventProbability), Detail: FormatProbabilities(a.Probabilities)},
			{Name: "define two-payoff boundary wound observable", Passed: strings.Contains(a.Observable.Observable, "P_K7") && strings.Contains(a.Observable.Observable, "P_perp") && math.Abs(a.Observable.K7Payoff-r3Minus1) < tolerance && math.Abs(a.Observable.ComplementPayoff-math.Abs(lambdaLambda12)) < tolerance && strings.Contains(a.Observable.K7PayoffRole, "gauge") && strings.Contains(a.Observable.ComplementPayoffRole, "scalar") && a.Observable.IsTwoPayoffObservable && a.Observable.Verdict == StatusTwoPayoffBoundaryWoundObservableDefined, Detail: FormatObservable(a.Observable)},
			{Name: "expectation reproduces weighted closure", Passed: strings.Contains(a.Expectation.Formula, "p_K7") && strings.Contains(a.Expectation.Formula, "p_perp") && math.Abs(a.Expectation.ExpectedBoundaryWound-a.Rearrangement.WeightedClosureRight) < tolerance && math.Abs(a.Expectation.KSum-a.Rearrangement.KSum) < tolerance && math.Abs(a.Expectation.Residual-a.Rearrangement.Residual) < 1e-17 && a.Expectation.ReproducesWeightedClosure && strings.Contains(a.Expectation.Verdict, StatusExpectationReproducesWeightedClosure), Detail: FormatExpectation(a.Expectation)},
			{Name: "record numerical residual", Passed: math.Abs(a.Numerical.KSum-0.0498265972876517) < 5e-16 && math.Abs(a.Numerical.ExpectedWound-0.0498265964350682) < 5e-16 && math.Abs(a.Numerical.Residual-8.5258344e-10) < 1e-16 && a.Numerical.SameResidual && a.Numerical.Verdict == StatusNumericalResidualRecorded, Detail: FormatNumerical(a.Numerical)},
			{Name: "interpret event/complement payoffs", Passed: strings.Contains(a.Interpretation.K7EventPayoff, "gauge") && strings.Contains(a.Interpretation.ComplementPayoff, "scalar") && strings.Contains(a.Interpretation.Observer, "rho_72") && strings.Contains(a.Interpretation.Output, "K_sum") && strings.Contains(a.Interpretation.Reading, "expected boundary wound") && strings.Contains(a.Interpretation.Verdict, StatusKappaSumNoBiasExpectedBoundaryWound), Detail: FormatInterpretation(a.Interpretation)},
			{Name: "audit equivalence to previous forms", Passed: len(a.Equivalence.Forms) == 4 && !a.Equivalence.IntroducesNewNumericalRelation && a.Equivalence.UpgradesSourceType && a.Equivalence.Verdict == StatusEquivalenceToPreviousFormsAudited, Detail: FormatEquivalence(a.Equivalence)},
			{Name: "audit alternative mixture observables", Passed: len(a.Alternatives.Alternatives) == 5 && a.Alternatives.ReversedPayoffRejected && a.Alternatives.SupportLocalFormSeparated && a.Alternatives.MidpointRejected && a.Alternatives.HodgeSignedRejected && a.Alternatives.ActiveMixtureAccepted && a.Alternatives.Verdict == StatusAlternativeMixtureObservablesAudited, Detail: FormatAlternatives(a.Alternatives)},
			{Name: "preserve missing theorem boundary", Passed: len(a.Missing.Missing) == 5 && strings.Contains(a.Missing.Verdict, StatusNoNativeK7ReceivesGaugeWound) && strings.Contains(a.Missing.Verdict, StatusNoNativeComplementReceivesScalarWound) && strings.Contains(a.Missing.Verdict, StatusNoNativeBoundaryWoundMixtureTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeHistoryResponseTheorem) && strings.Contains(a.Missing.Verdict, StatusNoNativeSevenOver72Theorem), Detail: FormatMissing(a.Missing)},
			{Name: "preserve Gate704 boundary wound mixture firewall", Passed: !a.Firewall.ClaimsK7ReceivesGaugeWoundNative && !a.Firewall.ClaimsComplementReceivesScalarWoundNative && !a.Firewall.ClaimsNativeBoundaryWoundMixtureTheorem && !a.Firewall.ClaimsNativeHistoryResponseTheorem && !a.Firewall.ClaimsNativeSevenOver72Theorem && !a.Firewall.ClaimsBoundaryStressDerived && !a.Firewall.ClaimsScalarRGMatching && !a.Firewall.ClaimsHiggsMass && !a.Firewall.ClaimsGaugeUnification && !a.Firewall.ClaimsFlavorDerivation && !a.Firewall.ClaimsCKMPMNS && a.Firewall.Verdict == StatusGate704BoundaryWoundMixtureBoundary, Detail: FormatFirewall(a.Firewall)},
		}
		notes := append(Statuses(), a.Truth)
		return theorem.Result{ID: AuditID, Name: "Gate 704 — K7/Complement Boundary Wound Mixture Observable Audit", Layer: theorem.LayerBridge, Status: theorem.BridgeRequired, Checks: checks, Notes: notes}
	}}
}
